<?php

// Data functions (insert, update, delete, form) for table actividades

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function actividades_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('actividades');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'actividad_id' => Request::val('actividad_id', ''),
		'referencia' => Request::val('referencia', ''),
		'usuario_id' => Request::val('usuario_id', ''),
		'cliente_id' => Request::val('cliente_id', ''),
		'asunto' => Request::val('asunto', ''),
		'tipo_actividad_id' => Request::val('tipo_actividad_id', ''),
		'modalidad_contacto_id' => Request::val('modalidad_contacto_id', ''),
		'fecha' => Request::dateComponents('fecha', ''),
		'hora_inicio' => Request::val('hora_inicio', ''),
		'hora_fin' => Request::val('hora_fin', ''),
		'duracion_minutos' => Request::val('duracion_minutos', ''),
		'prioridad_id' => Request::val('prioridad_id', ''),
		'estado_id' => Request::val('estado_id', ''),
		'descripcion' => br2nl(Request::val('descripcion', '')),
		'resultado' => br2nl(Request::val('resultado', '')),
		'fecha_creacion' => parseCode('<%%creationDateTime%%><%%creationTimestamp%%>current_timestamp()', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('actividades', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		actividades_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function actividades_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function actividades_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('actividades', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: actividades_before_delete
	if(function_exists('actividades_before_delete')) {
		$args = [];
		if(!actividades_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `actividades` WHERE `actividad_id`='{$selected_id}'", $eo);

	// hook: actividades_after_delete
	if(function_exists('actividades_after_delete')) {
		$args = [];
		actividades_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='actividades' AND `pkValue`='{$selected_id}'", $eo);
}

function actividades_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('actividades', $selected_id, 'edit')) return false;

	$data = [
		'actividad_id' => Request::val('actividad_id', ''),
		'referencia' => Request::val('referencia', ''),
		'usuario_id' => Request::val('usuario_id', ''),
		'cliente_id' => Request::val('cliente_id', ''),
		'asunto' => Request::val('asunto', ''),
		'tipo_actividad_id' => Request::val('tipo_actividad_id', ''),
		'modalidad_contacto_id' => Request::val('modalidad_contacto_id', ''),
		'fecha' => Request::dateComponents('fecha', ''),
		'hora_inicio' => Request::val('hora_inicio', ''),
		'hora_fin' => Request::val('hora_fin', ''),
		'duracion_minutos' => Request::val('duracion_minutos', ''),
		'prioridad_id' => Request::val('prioridad_id', ''),
		'estado_id' => Request::val('estado_id', ''),
		'descripcion' => br2nl(Request::val('descripcion', '')),
		'resultado' => br2nl(Request::val('resultado', '')),
		'fecha_modificacion' => parseCode('<%%editingDateTime%%>current_timestamp()', false, true),
	];

	if($data['actividad_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Actividad id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['asunto'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Asunto': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['fecha'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fecha': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('actividades', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: actividades_before_update
	if(function_exists('actividades_before_update')) {
		$args = ['old_data' => $old_data];
		if(!actividades_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'actividades',
		backtick_keys_once($set),
		['`actividad_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="actividades_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['actividad_id'];
	$newID = $data['actividad_id'];

	update_calc_fields('actividades', $data['selectedID'], calculated_fields()['actividades']);

	// hook: actividades_after_update
	if(function_exists('actividades_after_update')) {
		if($row = getRecord('actividades', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['actividad_id'];
		$args = ['old_data' => $old_data];
		if(!actividades_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('actividades', $selected_id);

	// if PK value changed, update ownership and $selected_id
	if($selected_id != $newID) {
		update('membership_userrecords', ['pkValue' => $newID], ['pkValue' => $selected_id, 'tableName' => 'actividades']);
		$selected_id = $newID;
	}
}

function actividades_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('actividades');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('actividades', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('actividades', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('actividades', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: fecha
	$combo_fecha = new DateCombo;
	$combo_fecha->DateFormat = "dmy";
	$combo_fecha->MinYear = defined('actividades.fecha.MinYear') ? constant('actividades.fecha.MinYear') : 1900;
	$combo_fecha->MaxYear = defined('actividades.fecha.MaxYear') ? constant('actividades.fecha.MaxYear') : 2100;
	$combo_fecha->DefaultDate = parseMySQLDate('', '');
	$combo_fecha->MonthNames = $Translation['month names'];
	$combo_fecha->NamePrefix = 'fecha';

	if($hasSelectedId) {
		if(!($row = getRecord('actividades', $selectedId))) {
			return error_message($Translation['No records found'], 'actividades_view.php', false);
		}
		$combo_fecha->DefaultDate = $row['fecha'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/actividades_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/actividades_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#actividad_id').replaceWith('<div class=\"form-control-static\" id=\"actividad_id\">' + (\$j('#actividad_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#referencia').replaceWith('<div class=\"form-control-static\" id=\"referencia\">' + (\$j('#referencia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#usuario_id').replaceWith('<div class=\"form-control-static\" id=\"usuario_id\">' + (\$j('#usuario_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#cliente_id').replaceWith('<div class=\"form-control-static\" id=\"cliente_id\">' + (\$j('#cliente_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#asunto').replaceWith('<div class=\"form-control-static\" id=\"asunto\">' + (\$j('#asunto').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#tipo_actividad_id').replaceWith('<div class=\"form-control-static\" id=\"tipo_actividad_id\">' + (\$j('#tipo_actividad_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#modalidad_contacto_id').replaceWith('<div class=\"form-control-static\" id=\"modalidad_contacto_id\">' + (\$j('#modalidad_contacto_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#fecha').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fechaDay, #fechaMonth, #fechaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#hora_inicio').replaceWith('<div class=\"form-control-static\" id=\"hora_inicio\">' + (\$j('#hora_inicio').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#hora_fin').replaceWith('<div class=\"form-control-static\" id=\"hora_fin\">' + (\$j('#hora_fin').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#duracion_minutos').replaceWith('<div class=\"form-control-static\" id=\"duracion_minutos\">' + (\$j('#duracion_minutos').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#prioridad_id').replaceWith('<div class=\"form-control-static\" id=\"prioridad_id\">' + (\$j('#prioridad_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado_id').replaceWith('<div class=\"form-control-static\" id=\"estado_id\">' + (\$j('#estado_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#descripcion').replaceWith('<div class=\"form-control-static\" id=\"descripcion\">' + (\$j('#descripcion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#resultado').replaceWith('<div class=\"form-control-static\" id=\"resultado\">' + (\$j('#resultado').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('#hora_inicio').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: false, showInputs: false, disableFocus: true, minuteStep: AppGini.config.timeFieldMinutesStep || 5 });";
		$jsEditable .= "\t\$j('#hora_fin').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: false, showInputs: false, disableFocus: true, minuteStep: AppGini.config.timeFieldMinutesStep || 5 });";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(fecha)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha->GetHTML(true) . '</div>' :
			$combo_fecha->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha)%%>', $combo_fecha->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(actividad_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(referencia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(usuario_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cliente_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(asunto)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipo_actividad_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(modalidad_contacto_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hora_inicio)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hora_fin)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(duracion_minutos)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prioridad_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(descripcion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(resultado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_creacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_modificacion)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(actividad_id)%%>', safe_html($urow['actividad_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(actividad_id)%%>', html_attr($row['actividad_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(actividad_id)%%>', urlencode($urow['actividad_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', safe_html($urow['referencia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', html_attr($row['referencia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode($urow['referencia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(usuario_id)%%>', safe_html($urow['usuario_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(usuario_id)%%>', html_attr($row['usuario_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usuario_id)%%>', urlencode($urow['usuario_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', safe_html($urow['cliente_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', html_attr($row['cliente_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode($urow['cliente_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(asunto)%%>', safe_html($urow['asunto']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(asunto)%%>', html_attr($row['asunto']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(asunto)%%>', urlencode($urow['asunto']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipo_actividad_id)%%>', safe_html($urow['tipo_actividad_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipo_actividad_id)%%>', html_attr($row['tipo_actividad_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_actividad_id)%%>', urlencode($urow['tipo_actividad_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(modalidad_contacto_id)%%>', safe_html($urow['modalidad_contacto_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(modalidad_contacto_id)%%>', html_attr($row['modalidad_contacto_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(modalidad_contacto_id)%%>', urlencode($urow['modalidad_contacto_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha)%%>', app_datetime($row['fecha']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha)%%>', urlencode(app_datetime($urow['fecha'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hora_inicio)%%>', safe_html($urow['hora_inicio']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hora_inicio)%%>', html_attr($row['hora_inicio']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hora_inicio)%%>', urlencode($urow['hora_inicio']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hora_fin)%%>', safe_html($urow['hora_fin']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hora_fin)%%>', html_attr($row['hora_fin']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hora_fin)%%>', urlencode($urow['hora_fin']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(duracion_minutos)%%>', safe_html($urow['duracion_minutos']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(duracion_minutos)%%>', html_attr($row['duracion_minutos']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(duracion_minutos)%%>', urlencode($urow['duracion_minutos']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prioridad_id)%%>', safe_html($urow['prioridad_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prioridad_id)%%>', html_attr($row['prioridad_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prioridad_id)%%>', urlencode($urow['prioridad_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado_id)%%>', safe_html($urow['estado_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado_id)%%>', html_attr($row['estado_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_id)%%>', urlencode($urow['estado_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(descripcion)%%>', safe_html($urow['descripcion'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(descripcion)%%>', urlencode($urow['descripcion']), $templateCode);
		$templateCode = str_replace('<%%VALUE(resultado)%%>', safe_html($urow['resultado'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(resultado)%%>', urlencode($urow['resultado']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_creacion)%%>', app_datetime($row['fecha_creacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_creacion)%%>', urlencode(app_datetime($urow['fecha_creacion'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_modificacion)%%>', app_datetime($row['fecha_modificacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_modificacion)%%>', urlencode(app_datetime($urow['fecha_modificacion'], 'dt')), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(actividad_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(actividad_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(referencia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(usuario_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usuario_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cliente_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(asunto)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(asunto)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipo_actividad_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_actividad_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(modalidad_contacto_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(modalidad_contacto_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hora_inicio)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hora_inicio)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hora_fin)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hora_fin)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(duracion_minutos)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(duracion_minutos)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prioridad_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prioridad_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(descripcion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(descripcion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(resultado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(resultado)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_creacion)%%>', '<%%creationDateTime%%><%%creationTimestamp%%>current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_creacion)%%>', urlencode('<%%creationDateTime%%><%%creationTimestamp%%>current_timestamp()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_modificacion)%%>', '<%%editingDateTime%%>current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_modificacion)%%>', urlencode('<%%editingDateTime%%>current_timestamp()'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('actividades');
	if($hasSelectedId) {
		$jdata = get_joined_record('actividades', $selectedId);
		if($jdata === false) $jdata = get_defaults('actividades');
		$rdata = $row;
	}
	$templateCode .= loadView('actividades-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: actividades_dv
	if(function_exists('actividades_dv')) {
		$args = [];
		actividades_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}