<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/actividades_encargos.php');
	include_once(__DIR__ . '/actividades_encargos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('actividades_encargos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'actividades_encargos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`actividades_encargos`.`actividad_id`" => "actividad_id",
		"`actividades_encargos`.`encargo_id`" => "encargo_id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`actividades_encargos`.`actividad_id`" => "actividad_id",
		"`actividades_encargos`.`encargo_id`" => "encargo_id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`actividades_encargos`.`actividad_id`" => "Actividad id",
		"`actividades_encargos`.`encargo_id`" => "Encargo id",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`actividades_encargos`.`actividad_id`" => "actividad_id",
		"`actividades_encargos`.`encargo_id`" => "encargo_id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`actividades_encargos` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'actividades_encargos_view.php';
	$x->TableTitle = 'Actividades encargos';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`actividades_encargos`.`actividad_id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Actividad id', 'Encargo id', ];
	$x->ColFieldName = ['actividad_id', 'encargo_id', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/actividades_encargos_templateTV.html';
	$x->SelectedTemplate = 'templates/actividades_encargos_templateTVS.html';
	$x->TemplateDV = 'templates/actividades_encargos_templateDV.html';
	$x->TemplateDVP = 'templates/actividades_encargos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: actividades_encargos_init
	$render = true;
	if(function_exists('actividades_encargos_init')) {
		$args = [];
		$render = actividades_encargos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: actividades_encargos_header
	$headerCode = '';
	if(function_exists('actividades_encargos_header')) {
		$args = [];
		$headerCode = actividades_encargos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: actividades_encargos_footer
	$footerCode = '';
	if(function_exists('actividades_encargos_footer')) {
		$args = [];
		$footerCode = actividades_encargos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
