<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/actividades.php');
	include_once(__DIR__ . '/actividades_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('actividades');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'actividades';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`actividades`.`actividad_id`" => "actividad_id",
		"`actividades`.`referencia`" => "referencia",
		"`actividades`.`usuario_id`" => "usuario_id",
		"`actividades`.`cliente_id`" => "cliente_id",
		"`actividades`.`asunto`" => "asunto",
		"`actividades`.`tipo_actividad_id`" => "tipo_actividad_id",
		"`actividades`.`modalidad_contacto_id`" => "modalidad_contacto_id",
		"if(`actividades`.`fecha`,date_format(`actividades`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"`actividades`.`hora_inicio`" => "hora_inicio",
		"`actividades`.`hora_fin`" => "hora_fin",
		"`actividades`.`duracion_minutos`" => "duracion_minutos",
		"`actividades`.`prioridad_id`" => "prioridad_id",
		"`actividades`.`estado_id`" => "estado_id",
		"`actividades`.`descripcion`" => "descripcion",
		"`actividades`.`resultado`" => "resultado",
		"if(`actividades`.`fecha_creacion`,date_format(`actividades`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`actividades`.`fecha_modificacion`,date_format(`actividades`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`actividades`.`tipo_actividad_id`',
		7 => '`actividades`.`modalidad_contacto_id`',
		8 => '`actividades`.`fecha`',
		9 => '`actividades`.`hora_inicio`',
		10 => '`actividades`.`hora_fin`',
		11 => '`actividades`.`duracion_minutos`',
		12 => '`actividades`.`prioridad_id`',
		13 => '`actividades`.`estado_id`',
		14 => 14,
		15 => 15,
		16 => '`actividades`.`fecha_creacion`',
		17 => '`actividades`.`fecha_modificacion`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`actividades`.`actividad_id`" => "actividad_id",
		"`actividades`.`referencia`" => "referencia",
		"`actividades`.`usuario_id`" => "usuario_id",
		"`actividades`.`cliente_id`" => "cliente_id",
		"`actividades`.`asunto`" => "asunto",
		"`actividades`.`tipo_actividad_id`" => "tipo_actividad_id",
		"`actividades`.`modalidad_contacto_id`" => "modalidad_contacto_id",
		"if(`actividades`.`fecha`,date_format(`actividades`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"`actividades`.`hora_inicio`" => "hora_inicio",
		"`actividades`.`hora_fin`" => "hora_fin",
		"`actividades`.`duracion_minutos`" => "duracion_minutos",
		"`actividades`.`prioridad_id`" => "prioridad_id",
		"`actividades`.`estado_id`" => "estado_id",
		"`actividades`.`descripcion`" => "descripcion",
		"`actividades`.`resultado`" => "resultado",
		"if(`actividades`.`fecha_creacion`,date_format(`actividades`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`actividades`.`fecha_modificacion`,date_format(`actividades`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`actividades`.`actividad_id`" => "Actividad id",
		"`actividades`.`referencia`" => "Referencia",
		"`actividades`.`usuario_id`" => "Usuario id",
		"`actividades`.`cliente_id`" => "Cliente id",
		"`actividades`.`asunto`" => "Asunto",
		"`actividades`.`tipo_actividad_id`" => "Tipo actividad id",
		"`actividades`.`modalidad_contacto_id`" => "Modalidad contacto id",
		"`actividades`.`fecha`" => "Fecha",
		"`actividades`.`hora_inicio`" => "Hora inicio",
		"`actividades`.`hora_fin`" => "Hora fin",
		"`actividades`.`duracion_minutos`" => "Duracion minutos",
		"`actividades`.`prioridad_id`" => "Prioridad id",
		"`actividades`.`estado_id`" => "Estado id",
		"`actividades`.`descripcion`" => "Descripcion",
		"`actividades`.`resultado`" => "Resultado",
		"`actividades`.`fecha_creacion`" => "Fecha creacion",
		"`actividades`.`fecha_modificacion`" => "Fecha modificacion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`actividades`.`actividad_id`" => "actividad_id",
		"`actividades`.`referencia`" => "referencia",
		"`actividades`.`usuario_id`" => "usuario_id",
		"`actividades`.`cliente_id`" => "cliente_id",
		"`actividades`.`asunto`" => "asunto",
		"`actividades`.`tipo_actividad_id`" => "tipo_actividad_id",
		"`actividades`.`modalidad_contacto_id`" => "modalidad_contacto_id",
		"if(`actividades`.`fecha`,date_format(`actividades`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"`actividades`.`hora_inicio`" => "hora_inicio",
		"`actividades`.`hora_fin`" => "hora_fin",
		"`actividades`.`duracion_minutos`" => "duracion_minutos",
		"`actividades`.`prioridad_id`" => "prioridad_id",
		"`actividades`.`estado_id`" => "estado_id",
		"`actividades`.`descripcion`" => "descripcion",
		"`actividades`.`resultado`" => "resultado",
		"if(`actividades`.`fecha_creacion`,date_format(`actividades`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`actividades`.`fecha_modificacion`,date_format(`actividades`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`actividades` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'actividades_view.php';
	$x->TableTitle = 'Actividades';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`actividades`.`actividad_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Actividad id', 'Referencia', 'Usuario id', 'Cliente id', 'Asunto', 'Tipo actividad id', 'Modalidad contacto id', 'Fecha', 'Hora inicio', 'Hora fin', 'Duracion minutos', 'Prioridad id', 'Estado id', 'Descripcion', 'Resultado', 'Fecha creacion', 'Fecha modificacion', ];
	$x->ColFieldName = ['actividad_id', 'referencia', 'usuario_id', 'cliente_id', 'asunto', 'tipo_actividad_id', 'modalidad_contacto_id', 'fecha', 'hora_inicio', 'hora_fin', 'duracion_minutos', 'prioridad_id', 'estado_id', 'descripcion', 'resultado', 'fecha_creacion', 'fecha_modificacion', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/actividades_templateTV.html';
	$x->SelectedTemplate = 'templates/actividades_templateTVS.html';
	$x->TemplateDV = 'templates/actividades_templateDV.html';
	$x->TemplateDVP = 'templates/actividades_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: actividades_init
	$render = true;
	if(function_exists('actividades_init')) {
		$args = [];
		$render = actividades_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: actividades_header
	$headerCode = '';
	if(function_exists('actividades_header')) {
		$args = [];
		$headerCode = actividades_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: actividades_footer
	$footerCode = '';
	if(function_exists('actividades_footer')) {
		$args = [];
		$footerCode = actividades_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
