<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/agencias.php');
	include_once(__DIR__ . '/agencias_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('agencias');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'agencias';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`agencias`.`agencia_id`" => "agencia_id",
		"`agencias`.`nombre`" => "nombre",
		"`agencias`.`direccion`" => "direccion",
		"`agencias`.`codigo_postal`" => "codigo_postal",
		"`agencias`.`localidad`" => "localidad",
		"`agencias`.`provincia`" => "provincia",
		"`agencias`.`telefono`" => "telefono",
		"`agencias`.`email`" => "email",
		"`agencias`.`responsable_id`" => "responsable_id",
		"if(`agencias`.`fecha_alta`,date_format(`agencias`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"`agencias`.`activo`" => "activo",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => '`agencias`.`fecha_alta`',
		11 => '`agencias`.`activo`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`agencias`.`agencia_id`" => "agencia_id",
		"`agencias`.`nombre`" => "nombre",
		"`agencias`.`direccion`" => "direccion",
		"`agencias`.`codigo_postal`" => "codigo_postal",
		"`agencias`.`localidad`" => "localidad",
		"`agencias`.`provincia`" => "provincia",
		"`agencias`.`telefono`" => "telefono",
		"`agencias`.`email`" => "email",
		"`agencias`.`responsable_id`" => "responsable_id",
		"if(`agencias`.`fecha_alta`,date_format(`agencias`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"`agencias`.`activo`" => "activo",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`agencias`.`agencia_id`" => "Agencia id",
		"`agencias`.`nombre`" => "Nombre",
		"`agencias`.`direccion`" => "Direccion",
		"`agencias`.`codigo_postal`" => "Codigo postal",
		"`agencias`.`localidad`" => "Localidad",
		"`agencias`.`provincia`" => "Provincia",
		"`agencias`.`telefono`" => "Telefono",
		"`agencias`.`email`" => "Email",
		"`agencias`.`responsable_id`" => "Responsable id",
		"`agencias`.`fecha_alta`" => "Fecha alta",
		"`agencias`.`activo`" => "Activo",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`agencias`.`agencia_id`" => "agencia_id",
		"`agencias`.`nombre`" => "nombre",
		"`agencias`.`direccion`" => "direccion",
		"`agencias`.`codigo_postal`" => "codigo_postal",
		"`agencias`.`localidad`" => "localidad",
		"`agencias`.`provincia`" => "provincia",
		"`agencias`.`telefono`" => "telefono",
		"`agencias`.`email`" => "email",
		"`agencias`.`responsable_id`" => "responsable_id",
		"if(`agencias`.`fecha_alta`,date_format(`agencias`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"`agencias`.`activo`" => "activo",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`agencias` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'agencias_view.php';
	$x->TableTitle = 'Agencias';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`agencias`.`agencia_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Agencia id', 'Nombre', 'Direccion', 'Codigo postal', 'Localidad', 'Provincia', 'Telefono', 'Email', 'Responsable id', 'Fecha alta', 'Activo', ];
	$x->ColFieldName = ['agencia_id', 'nombre', 'direccion', 'codigo_postal', 'localidad', 'provincia', 'telefono', 'email', 'responsable_id', 'fecha_alta', 'activo', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/agencias_templateTV.html';
	$x->SelectedTemplate = 'templates/agencias_templateTVS.html';
	$x->TemplateDV = 'templates/agencias_templateDV.html';
	$x->TemplateDVP = 'templates/agencias_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: agencias_init
	$render = true;
	if(function_exists('agencias_init')) {
		$args = [];
		$render = agencias_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: agencias_header
	$headerCode = '';
	if(function_exists('agencias_header')) {
		$args = [];
		$headerCode = agencias_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: agencias_footer
	$footerCode = '';
	if(function_exists('agencias_footer')) {
		$args = [];
		$footerCode = agencias_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
