<?php

// Data functions (insert, update, delete, form) for table clientes

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function clientes_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('clientes');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'cliente_id' => Request::val('cliente_id', ''),
		'nombre' => Request::val('nombre', ''),
		'apellidos' => Request::val('apellidos', ''),
		'nombre_completo' => Request::val('nombre_completo', ''),
		'tratamiento' => Request::val('tratamiento', ''),
		'genero' => Request::val('genero', ''),
		'fecha_nacimiento' => Request::dateComponents('fecha_nacimiento', ''),
		'documento_id' => Request::val('documento_id', ''),
		'nacionalidad' => Request::val('nacionalidad', ''),
		'estado_civil' => Request::val('estado_civil', ''),
		'telefono_fijo' => Request::val('telefono_fijo', ''),
		'telefono_movil' => Request::val('telefono_movil', ''),
		'telefono_adicional' => Request::val('telefono_adicional', ''),
		'email' => Request::val('email', ''),
		'cliente_telefonico' => Request::val('cliente_telefonico', '0'),
		'profesion' => Request::val('profesion', ''),
		'sector_actividad' => Request::val('sector_actividad', ''),
		'empresa' => Request::val('empresa', ''),
		'fecha_alta' => Request::dateComponents('fecha_alta', 'curdate()'),
		'agencia_id' => Request::val('agencia_id', ''),
		'usuario_id' => Request::val('usuario_id', ''),
		'observaciones' => br2nl(Request::val('observaciones', '')),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('clientes', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		clientes_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function clientes_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function clientes_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('clientes', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: clientes_before_delete
	if(function_exists('clientes_before_delete')) {
		$args = [];
		if(!clientes_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `clientes` WHERE `cliente_id`='{$selected_id}'", $eo);

	// hook: clientes_after_delete
	if(function_exists('clientes_after_delete')) {
		$args = [];
		clientes_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='clientes' AND `pkValue`='{$selected_id}'", $eo);
}

function clientes_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('clientes', $selected_id, 'edit')) return false;

	$data = [
		'cliente_id' => Request::val('cliente_id', ''),
		'nombre' => Request::val('nombre', ''),
		'apellidos' => Request::val('apellidos', ''),
		'nombre_completo' => Request::val('nombre_completo', ''),
		'tratamiento' => Request::val('tratamiento', ''),
		'genero' => Request::val('genero', ''),
		'fecha_nacimiento' => Request::dateComponents('fecha_nacimiento', ''),
		'documento_id' => Request::val('documento_id', ''),
		'nacionalidad' => Request::val('nacionalidad', ''),
		'estado_civil' => Request::val('estado_civil', ''),
		'telefono_fijo' => Request::val('telefono_fijo', ''),
		'telefono_movil' => Request::val('telefono_movil', ''),
		'telefono_adicional' => Request::val('telefono_adicional', ''),
		'email' => Request::val('email', ''),
		'cliente_telefonico' => Request::val('cliente_telefonico', ''),
		'profesion' => Request::val('profesion', ''),
		'sector_actividad' => Request::val('sector_actividad', ''),
		'empresa' => Request::val('empresa', ''),
		'fecha_alta' => Request::dateComponents('fecha_alta', ''),
		'ultima_modificacion' => parseCode('<%%editingDateTime%%>current_timestamp()', false, true),
		'agencia_id' => Request::val('agencia_id', ''),
		'usuario_id' => Request::val('usuario_id', ''),
		'observaciones' => br2nl(Request::val('observaciones', '')),
	];

	if($data['cliente_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cliente id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['nombre'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombre': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['apellidos'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Apellidos': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('clientes', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: clientes_before_update
	if(function_exists('clientes_before_update')) {
		$args = ['old_data' => $old_data];
		if(!clientes_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'clientes',
		backtick_keys_once($set),
		['`cliente_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="clientes_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['cliente_id'];
	$newID = $data['cliente_id'];

	update_calc_fields('clientes', $data['selectedID'], calculated_fields()['clientes']);

	// hook: clientes_after_update
	if(function_exists('clientes_after_update')) {
		if($row = getRecord('clientes', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['cliente_id'];
		$args = ['old_data' => $old_data];
		if(!clientes_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('clientes', $selected_id);

	// if PK value changed, update ownership and $selected_id
	if($selected_id != $newID) {
		update('membership_userrecords', ['pkValue' => $newID], ['pkValue' => $selected_id, 'tableName' => 'clientes']);
		$selected_id = $newID;
	}
}

function clientes_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('clientes');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('clientes', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('clientes', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('clientes', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: genero
	$combo_genero = new Combo;
	$combo_genero->ListType = 0;
	$combo_genero->MultipleSeparator = ', ';
	$combo_genero->ListBoxHeight = 10;
	$combo_genero->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/clientes.genero.csv')) {
		$genero_data = addslashes(implode('', @file(__DIR__ . '/hooks/clientes.genero.csv')));
		$combo_genero->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($genero_data))));
		$combo_genero->ListData = $combo_genero->ListItem;
	} else {
		$combo_genero->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Masculino;;Femenino;;Binario"))));
		$combo_genero->ListData = $combo_genero->ListItem;
	}
	$combo_genero->SelectName = 'genero';
	// combobox: fecha_nacimiento
	$combo_fecha_nacimiento = new DateCombo;
	$combo_fecha_nacimiento->DateFormat = "dmy";
	$combo_fecha_nacimiento->MinYear = defined('clientes.fecha_nacimiento.MinYear') ? constant('clientes.fecha_nacimiento.MinYear') : 1900;
	$combo_fecha_nacimiento->MaxYear = defined('clientes.fecha_nacimiento.MaxYear') ? constant('clientes.fecha_nacimiento.MaxYear') : 2100;
	$combo_fecha_nacimiento->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_nacimiento->MonthNames = $Translation['month names'];
	$combo_fecha_nacimiento->NamePrefix = 'fecha_nacimiento';
	// combobox: fecha_alta
	$combo_fecha_alta = new DateCombo;
	$combo_fecha_alta->DateFormat = "dmy";
	$combo_fecha_alta->MinYear = defined('clientes.fecha_alta.MinYear') ? constant('clientes.fecha_alta.MinYear') : 1900;
	$combo_fecha_alta->MaxYear = defined('clientes.fecha_alta.MaxYear') ? constant('clientes.fecha_alta.MaxYear') : 2100;
	$combo_fecha_alta->DefaultDate = parseMySQLDate('curdate()', 'curdate()');
	$combo_fecha_alta->MonthNames = $Translation['month names'];
	$combo_fecha_alta->NamePrefix = 'fecha_alta';

	if($hasSelectedId) {
		if(!($row = getRecord('clientes', $selectedId))) {
			return error_message($Translation['No records found'], 'clientes_view.php', false);
		}
		$combo_genero->SelectedData = $row['genero'];
		$combo_fecha_nacimiento->DefaultDate = $row['fecha_nacimiento'];
		$combo_fecha_alta->DefaultDate = $row['fecha_alta'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_genero->SelectedText = (isset($filterField[1]) && $filterField[1] == '6' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_genero->Render();

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/clientes_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/clientes_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#cliente_id').replaceWith('<div class=\"form-control-static\" id=\"cliente_id\">' + (\$j('#cliente_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#nombre').replaceWith('<div class=\"form-control-static\" id=\"nombre\">' + (\$j('#nombre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#apellidos').replaceWith('<div class=\"form-control-static\" id=\"apellidos\">' + (\$j('#apellidos').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#nombre_completo').replaceWith('<div class=\"form-control-static\" id=\"nombre_completo\">' + (\$j('#nombre_completo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#tratamiento').replaceWith('<div class=\"form-control-static\" id=\"tratamiento\">' + (\$j('#tratamiento').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#genero').replaceWith('<div class=\"form-control-static\" id=\"genero\">' + (\$j('#genero').val() || '') + '</div>'); \$j('#genero-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#fecha_nacimiento').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_nacimientoDay, #fecha_nacimientoMonth, #fecha_nacimientoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#documento_id').replaceWith('<div class=\"form-control-static\" id=\"documento_id\">' + (\$j('#documento_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#nacionalidad').replaceWith('<div class=\"form-control-static\" id=\"nacionalidad\">' + (\$j('#nacionalidad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado_civil').replaceWith('<div class=\"form-control-static\" id=\"estado_civil\">' + (\$j('#estado_civil').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#telefono_fijo').replaceWith('<div class=\"form-control-static\" id=\"telefono_fijo\">' + (\$j('#telefono_fijo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#telefono_movil').replaceWith('<div class=\"form-control-static\" id=\"telefono_movil\">' + (\$j('#telefono_movil').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#telefono_adicional').replaceWith('<div class=\"form-control-static\" id=\"telefono_adicional\">' + (\$j('#telefono_adicional').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (\$j('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#cliente_telefonico').replaceWith('<div class=\"form-control-static\" id=\"cliente_telefonico\">' + (\$j('#cliente_telefonico').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#profesion').replaceWith('<div class=\"form-control-static\" id=\"profesion\">' + (\$j('#profesion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#sector_actividad').replaceWith('<div class=\"form-control-static\" id=\"sector_actividad\">' + (\$j('#sector_actividad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#empresa').replaceWith('<div class=\"form-control-static\" id=\"empresa\">' + (\$j('#empresa').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#fecha_alta').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_altaDay, #fecha_altaMonth, #fecha_altaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#agencia_id').replaceWith('<div class=\"form-control-static\" id=\"agencia_id\">' + (\$j('#agencia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#usuario_id').replaceWith('<div class=\"form-control-static\" id=\"usuario_id\">' + (\$j('#usuario_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#observaciones').replaceWith('<div class=\"form-control-static\" id=\"observaciones\">' + (\$j('#observaciones').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(genero)%%>', $combo_genero->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(genero)%%>', $combo_genero->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_nacimiento)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_nacimiento->GetHTML(true) . '</div>' :
			$combo_fecha_nacimiento->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_nacimiento)%%>', $combo_fecha_nacimiento->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_alta)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_alta->GetHTML(true) . '</div>' :
			$combo_fecha_alta->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_alta)%%>', $combo_fecha_alta->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(cliente_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nombre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(apellidos)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nombre_completo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tratamiento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(genero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_nacimiento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(documento_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nacionalidad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado_civil)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(telefono_fijo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(telefono_movil)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(telefono_adicional)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cliente_telefonico)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(profesion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sector_actividad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(empresa)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_alta)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ultima_modificacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(agencia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(usuario_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(observaciones)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', safe_html($urow['cliente_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', html_attr($row['cliente_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode($urow['cliente_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nombre)%%>', safe_html($urow['nombre']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nombre)%%>', html_attr($row['nombre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombre)%%>', urlencode($urow['nombre']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(apellidos)%%>', safe_html($urow['apellidos']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(apellidos)%%>', html_attr($row['apellidos']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(apellidos)%%>', urlencode($urow['apellidos']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nombre_completo)%%>', safe_html($urow['nombre_completo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nombre_completo)%%>', html_attr($row['nombre_completo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombre_completo)%%>', urlencode($urow['nombre_completo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tratamiento)%%>', safe_html($urow['tratamiento']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tratamiento)%%>', html_attr($row['tratamiento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tratamiento)%%>', urlencode($urow['tratamiento']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(genero)%%>', safe_html($urow['genero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(genero)%%>', html_attr($row['genero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(genero)%%>', urlencode($urow['genero']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_nacimiento)%%>', app_datetime($row['fecha_nacimiento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_nacimiento)%%>', urlencode(app_datetime($urow['fecha_nacimiento'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(documento_id)%%>', safe_html($urow['documento_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(documento_id)%%>', html_attr($row['documento_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(documento_id)%%>', urlencode($urow['documento_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nacionalidad)%%>', safe_html($urow['nacionalidad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nacionalidad)%%>', html_attr($row['nacionalidad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nacionalidad)%%>', urlencode($urow['nacionalidad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado_civil)%%>', safe_html($urow['estado_civil']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado_civil)%%>', html_attr($row['estado_civil']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_civil)%%>', urlencode($urow['estado_civil']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(telefono_fijo)%%>', safe_html($urow['telefono_fijo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(telefono_fijo)%%>', html_attr($row['telefono_fijo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono_fijo)%%>', urlencode($urow['telefono_fijo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(telefono_movil)%%>', safe_html($urow['telefono_movil']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(telefono_movil)%%>', html_attr($row['telefono_movil']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono_movil)%%>', urlencode($urow['telefono_movil']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(telefono_adicional)%%>', safe_html($urow['telefono_adicional']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(telefono_adicional)%%>', html_attr($row['telefono_adicional']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono_adicional)%%>', urlencode($urow['telefono_adicional']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cliente_telefonico)%%>', safe_html($urow['cliente_telefonico']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cliente_telefonico)%%>', html_attr($row['cliente_telefonico']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_telefonico)%%>', urlencode($urow['cliente_telefonico']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(profesion)%%>', safe_html($urow['profesion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(profesion)%%>', html_attr($row['profesion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(profesion)%%>', urlencode($urow['profesion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(sector_actividad)%%>', safe_html($urow['sector_actividad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(sector_actividad)%%>', html_attr($row['sector_actividad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sector_actividad)%%>', urlencode($urow['sector_actividad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(empresa)%%>', safe_html($urow['empresa']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(empresa)%%>', html_attr($row['empresa']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empresa)%%>', urlencode($urow['empresa']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_alta)%%>', app_datetime($row['fecha_alta']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_alta)%%>', urlencode(app_datetime($urow['fecha_alta'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(ultima_modificacion)%%>', app_datetime($row['ultima_modificacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ultima_modificacion)%%>', urlencode(app_datetime($urow['ultima_modificacion'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(agencia_id)%%>', safe_html($urow['agencia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(agencia_id)%%>', html_attr($row['agencia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(agencia_id)%%>', urlencode($urow['agencia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(usuario_id)%%>', safe_html($urow['usuario_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(usuario_id)%%>', html_attr($row['usuario_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usuario_id)%%>', urlencode($urow['usuario_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(observaciones)%%>', safe_html($urow['observaciones'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(observaciones)%%>', urlencode($urow['observaciones']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(cliente_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nombre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(apellidos)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(apellidos)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nombre_completo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombre_completo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tratamiento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tratamiento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(genero)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(genero)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_nacimiento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_nacimiento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(documento_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(documento_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nacionalidad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nacionalidad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado_civil)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_civil)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(telefono_fijo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono_fijo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(telefono_movil)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono_movil)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(telefono_adicional)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono_adicional)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cliente_telefonico)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_telefonico)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(profesion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(profesion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sector_actividad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sector_actividad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(empresa)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empresa)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_alta)%%>', 'curdate()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_alta)%%>', urlencode('curdate()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(ultima_modificacion)%%>', '<%%editingDateTime%%>current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ultima_modificacion)%%>', urlencode('<%%editingDateTime%%>current_timestamp()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(agencia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(agencia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(usuario_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usuario_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(observaciones)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(observaciones)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('clientes');
	if($hasSelectedId) {
		$jdata = get_joined_record('clientes', $selectedId);
		if($jdata === false) $jdata = get_defaults('clientes');
		$rdata = $row;
	}
	$templateCode .= loadView('clientes-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: clientes_dv
	if(function_exists('clientes_dv')) {
		$args = [];
		clientes_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}