<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/clientes.php');
	include_once(__DIR__ . '/clientes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('clientes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'clientes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`clientes`.`cliente_id`" => "cliente_id",
		"`clientes`.`nombre`" => "nombre",
		"`clientes`.`apellidos`" => "apellidos",
		"`clientes`.`nombre_completo`" => "nombre_completo",
		"`clientes`.`tratamiento`" => "tratamiento",
		"`clientes`.`genero`" => "genero",
		"if(`clientes`.`fecha_nacimiento`,date_format(`clientes`.`fecha_nacimiento`,'%d/%m/%Y'),'')" => "fecha_nacimiento",
		"`clientes`.`documento_id`" => "documento_id",
		"`clientes`.`nacionalidad`" => "nacionalidad",
		"`clientes`.`estado_civil`" => "estado_civil",
		"`clientes`.`telefono_fijo`" => "telefono_fijo",
		"`clientes`.`telefono_movil`" => "telefono_movil",
		"`clientes`.`telefono_adicional`" => "telefono_adicional",
		"`clientes`.`email`" => "email",
		"`clientes`.`cliente_telefonico`" => "cliente_telefonico",
		"`clientes`.`profesion`" => "profesion",
		"`clientes`.`sector_actividad`" => "sector_actividad",
		"`clientes`.`empresa`" => "empresa",
		"if(`clientes`.`fecha_alta`,date_format(`clientes`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"if(`clientes`.`ultima_modificacion`,date_format(`clientes`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
		"`clientes`.`agencia_id`" => "agencia_id",
		"`clientes`.`usuario_id`" => "usuario_id",
		"`clientes`.`observaciones`" => "observaciones",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`clientes`.`fecha_nacimiento`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => '`clientes`.`cliente_telefonico`',
		16 => 16,
		17 => 17,
		18 => 18,
		19 => '`clientes`.`fecha_alta`',
		20 => '`clientes`.`ultima_modificacion`',
		21 => 21,
		22 => 22,
		23 => 23,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`clientes`.`cliente_id`" => "cliente_id",
		"`clientes`.`nombre`" => "nombre",
		"`clientes`.`apellidos`" => "apellidos",
		"`clientes`.`nombre_completo`" => "nombre_completo",
		"`clientes`.`tratamiento`" => "tratamiento",
		"`clientes`.`genero`" => "genero",
		"if(`clientes`.`fecha_nacimiento`,date_format(`clientes`.`fecha_nacimiento`,'%d/%m/%Y'),'')" => "fecha_nacimiento",
		"`clientes`.`documento_id`" => "documento_id",
		"`clientes`.`nacionalidad`" => "nacionalidad",
		"`clientes`.`estado_civil`" => "estado_civil",
		"`clientes`.`telefono_fijo`" => "telefono_fijo",
		"`clientes`.`telefono_movil`" => "telefono_movil",
		"`clientes`.`telefono_adicional`" => "telefono_adicional",
		"`clientes`.`email`" => "email",
		"`clientes`.`cliente_telefonico`" => "cliente_telefonico",
		"`clientes`.`profesion`" => "profesion",
		"`clientes`.`sector_actividad`" => "sector_actividad",
		"`clientes`.`empresa`" => "empresa",
		"if(`clientes`.`fecha_alta`,date_format(`clientes`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"if(`clientes`.`ultima_modificacion`,date_format(`clientes`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
		"`clientes`.`agencia_id`" => "agencia_id",
		"`clientes`.`usuario_id`" => "usuario_id",
		"`clientes`.`observaciones`" => "observaciones",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`clientes`.`cliente_id`" => "Cliente id",
		"`clientes`.`nombre`" => "Nombre",
		"`clientes`.`apellidos`" => "Apellidos",
		"`clientes`.`nombre_completo`" => "Nombre completo",
		"`clientes`.`tratamiento`" => "Tratamiento",
		"`clientes`.`genero`" => "Genero",
		"`clientes`.`fecha_nacimiento`" => "Fecha nacimiento",
		"`clientes`.`documento_id`" => "Documento id",
		"`clientes`.`nacionalidad`" => "Nacionalidad",
		"`clientes`.`estado_civil`" => "Estado civil",
		"`clientes`.`telefono_fijo`" => "Telefono fijo",
		"`clientes`.`telefono_movil`" => "Telefono movil",
		"`clientes`.`telefono_adicional`" => "Telefono adicional",
		"`clientes`.`email`" => "Email",
		"`clientes`.`cliente_telefonico`" => "Cliente telefonico",
		"`clientes`.`profesion`" => "Profesion",
		"`clientes`.`sector_actividad`" => "Sector actividad",
		"`clientes`.`empresa`" => "Empresa",
		"`clientes`.`fecha_alta`" => "Fecha alta",
		"`clientes`.`ultima_modificacion`" => "Ultima modificacion",
		"`clientes`.`agencia_id`" => "Agencia id",
		"`clientes`.`usuario_id`" => "Usuario id",
		"`clientes`.`observaciones`" => "Observaciones",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`clientes`.`cliente_id`" => "cliente_id",
		"`clientes`.`nombre`" => "nombre",
		"`clientes`.`apellidos`" => "apellidos",
		"`clientes`.`nombre_completo`" => "nombre_completo",
		"`clientes`.`tratamiento`" => "tratamiento",
		"`clientes`.`genero`" => "genero",
		"if(`clientes`.`fecha_nacimiento`,date_format(`clientes`.`fecha_nacimiento`,'%d/%m/%Y'),'')" => "fecha_nacimiento",
		"`clientes`.`documento_id`" => "documento_id",
		"`clientes`.`nacionalidad`" => "nacionalidad",
		"`clientes`.`estado_civil`" => "estado_civil",
		"`clientes`.`telefono_fijo`" => "telefono_fijo",
		"`clientes`.`telefono_movil`" => "telefono_movil",
		"`clientes`.`telefono_adicional`" => "telefono_adicional",
		"`clientes`.`email`" => "email",
		"`clientes`.`cliente_telefonico`" => "cliente_telefonico",
		"`clientes`.`profesion`" => "profesion",
		"`clientes`.`sector_actividad`" => "sector_actividad",
		"`clientes`.`empresa`" => "empresa",
		"if(`clientes`.`fecha_alta`,date_format(`clientes`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"if(`clientes`.`ultima_modificacion`,date_format(`clientes`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
		"`clientes`.`agencia_id`" => "agencia_id",
		"`clientes`.`usuario_id`" => "usuario_id",
		"`clientes`.`observaciones`" => "observaciones",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`clientes` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'clientes_view.php';
	$x->TableTitle = 'Clientes';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`clientes`.`cliente_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Cliente id', 'Nombre', 'Apellidos', 'Nombre completo', 'Tratamiento', 'Genero', 'Fecha nacimiento', 'Documento id', 'Nacionalidad', 'Estado civil', 'Telefono fijo', 'Telefono movil', 'Telefono adicional', 'Email', 'Cliente telefonico', 'Profesion', 'Sector actividad', 'Empresa', 'Fecha alta', 'Ultima modificacion', 'Agencia id', 'Usuario id', 'Observaciones', ];
	$x->ColFieldName = ['cliente_id', 'nombre', 'apellidos', 'nombre_completo', 'tratamiento', 'genero', 'fecha_nacimiento', 'documento_id', 'nacionalidad', 'estado_civil', 'telefono_fijo', 'telefono_movil', 'telefono_adicional', 'email', 'cliente_telefonico', 'profesion', 'sector_actividad', 'empresa', 'fecha_alta', 'ultima_modificacion', 'agencia_id', 'usuario_id', 'observaciones', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/clientes_templateTV.html';
	$x->SelectedTemplate = 'templates/clientes_templateTVS.html';
	$x->TemplateDV = 'templates/clientes_templateDV.html';
	$x->TemplateDVP = 'templates/clientes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: clientes_init
	$render = true;
	if(function_exists('clientes_init')) {
		$args = [];
		$render = clientes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: clientes_header
	$headerCode = '';
	if(function_exists('clientes_header')) {
		$args = [];
		$headerCode = clientes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: clientes_footer
	$footerCode = '';
	if(function_exists('clientes_footer')) {
		$args = [];
		$footerCode = clientes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
