<?php

// Data functions (insert, update, delete, form) for table direcciones

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function direcciones_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('direcciones');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'cliente_id' => Request::val('cliente_id', ''),
		'inmueble_id' => Request::val('inmueble_id', ''),
		'tipo_direccion' => Request::val('tipo_direccion', ''),
		'calle' => Request::val('calle', ''),
		'numero' => Request::val('numero', ''),
		'piso' => Request::val('piso', ''),
		'puerta' => Request::val('puerta', ''),
		'escalera' => Request::val('escalera', ''),
		'codigo_postal' => Request::val('codigo_postal', ''),
		'localidad' => Request::val('localidad', ''),
		'provincia' => Request::val('provincia', ''),
		'pais' => Request::val('pais', 'Espana'),
		'referencia_catastral' => Request::val('referencia_catastral', ''),
		'coordenadas_latitud' => Request::val('coordenadas_latitud', ''),
		'coordenadas_longitud' => Request::val('coordenadas_longitud', ''),
		'principal' => Request::val('principal', '0'),
		'fecha_alta' => parseCode('<%%creationDateTime%%>curdate()', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('direcciones', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		direcciones_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function direcciones_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function direcciones_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('direcciones', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: direcciones_before_delete
	if(function_exists('direcciones_before_delete')) {
		$args = [];
		if(!direcciones_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `direcciones` WHERE `direccion_id`='{$selected_id}'", $eo);

	// hook: direcciones_after_delete
	if(function_exists('direcciones_after_delete')) {
		$args = [];
		direcciones_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='direcciones' AND `pkValue`='{$selected_id}'", $eo);
}

function direcciones_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('direcciones', $selected_id, 'edit')) return false;

	$data = [
		'cliente_id' => Request::val('cliente_id', ''),
		'inmueble_id' => Request::val('inmueble_id', ''),
		'tipo_direccion' => Request::val('tipo_direccion', ''),
		'calle' => Request::val('calle', ''),
		'numero' => Request::val('numero', ''),
		'piso' => Request::val('piso', ''),
		'puerta' => Request::val('puerta', ''),
		'escalera' => Request::val('escalera', ''),
		'codigo_postal' => Request::val('codigo_postal', ''),
		'localidad' => Request::val('localidad', ''),
		'provincia' => Request::val('provincia', ''),
		'pais' => Request::val('pais', ''),
		'referencia_catastral' => Request::val('referencia_catastral', ''),
		'coordenadas_latitud' => Request::val('coordenadas_latitud', ''),
		'coordenadas_longitud' => Request::val('coordenadas_longitud', ''),
		'principal' => Request::val('principal', ''),
		'ultima_modificacion' => parseCode('<%%editingDateTime%%>current_timestamp()', false, true),
	];

	if($data['tipo_direccion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Tipo direccion': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['calle'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Calle': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['localidad'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Localidad': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['provincia'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Provincia': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('direcciones', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: direcciones_before_update
	if(function_exists('direcciones_before_update')) {
		$args = ['old_data' => $old_data];
		if(!direcciones_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'direcciones',
		backtick_keys_once($set),
		['`direccion_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="direcciones_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('direcciones', $data['selectedID'], calculated_fields()['direcciones']);

	// hook: direcciones_after_update
	if(function_exists('direcciones_after_update')) {
		if($row = getRecord('direcciones', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['direccion_id'];
		$args = ['old_data' => $old_data];
		if(!direcciones_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('direcciones', $selected_id);
}

function direcciones_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('direcciones');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('direcciones', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('direcciones', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('direcciones', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: tipo_direccion
	$combo_tipo_direccion = new Combo;
	$combo_tipo_direccion->ListType = 0;
	$combo_tipo_direccion->MultipleSeparator = ', ';
	$combo_tipo_direccion->ListBoxHeight = 10;
	$combo_tipo_direccion->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/direcciones.tipo_direccion.csv')) {
		$tipo_direccion_data = addslashes(implode('', @file(__DIR__ . '/hooks/direcciones.tipo_direccion.csv')));
		$combo_tipo_direccion->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($tipo_direccion_data))));
		$combo_tipo_direccion->ListData = $combo_tipo_direccion->ListItem;
	} else {
		$combo_tipo_direccion->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Calle;;Avenida;;Paseo;;Plaza;;Camino;;Carretera;;Ronda;;Glorieta;;Traves&#237;a;;Pasaje;;V&#237;a;;Autov&#237;a;;Autopista;;Callej&#243;n;;Pista;;Sendero;;Boulevard;;Alameda;;Pol&#237;gono;;Urbanizaci&#243;n;;Vereda;;Barrio;;Ensanche;;Cuesta;;Costanilla;;Plazoleta;;Parque;;Ramblas;;Rotonda;;Zona"))));
		$combo_tipo_direccion->ListData = $combo_tipo_direccion->ListItem;
	}
	$combo_tipo_direccion->SelectName = 'tipo_direccion';
	$combo_tipo_direccion->AllowNull = false;

	if($hasSelectedId) {
		if(!($row = getRecord('direcciones', $selectedId))) {
			return error_message($Translation['No records found'], 'direcciones_view.php', false);
		}
		$combo_tipo_direccion->SelectedData = $row['tipo_direccion'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_tipo_direccion->SelectedText = (isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_tipo_direccion->Render();

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/direcciones_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/direcciones_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#cliente_id').replaceWith('<div class=\"form-control-static\" id=\"cliente_id\">' + (\$j('#cliente_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#inmueble_id').replaceWith('<div class=\"form-control-static\" id=\"inmueble_id\">' + (\$j('#inmueble_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#tipo_direccion').replaceWith('<div class=\"form-control-static\" id=\"tipo_direccion\">' + (\$j('#tipo_direccion').val() || '') + '</div>'); \$j('#tipo_direccion-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#calle').replaceWith('<div class=\"form-control-static\" id=\"calle\">' + (\$j('#calle').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#numero').replaceWith('<div class=\"form-control-static\" id=\"numero\">' + (\$j('#numero').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#piso').replaceWith('<div class=\"form-control-static\" id=\"piso\">' + (\$j('#piso').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#puerta').replaceWith('<div class=\"form-control-static\" id=\"puerta\">' + (\$j('#puerta').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#escalera').replaceWith('<div class=\"form-control-static\" id=\"escalera\">' + (\$j('#escalera').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#codigo_postal').replaceWith('<div class=\"form-control-static\" id=\"codigo_postal\">' + (\$j('#codigo_postal').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#localidad').replaceWith('<div class=\"form-control-static\" id=\"localidad\">' + (\$j('#localidad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#provincia').replaceWith('<div class=\"form-control-static\" id=\"provincia\">' + (\$j('#provincia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#pais').replaceWith('<div class=\"form-control-static\" id=\"pais\">' + (\$j('#pais').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#referencia_catastral').replaceWith('<div class=\"form-control-static\" id=\"referencia_catastral\">' + (\$j('#referencia_catastral').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#coordenadas_latitud').replaceWith('<div class=\"form-control-static\" id=\"coordenadas_latitud\">' + (\$j('#coordenadas_latitud').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#coordenadas_longitud').replaceWith('<div class=\"form-control-static\" id=\"coordenadas_longitud\">' + (\$j('#coordenadas_longitud').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#principal').replaceWith('<div class=\"form-control-static\" id=\"principal\">' + (\$j('#principal').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(tipo_direccion)%%>', $combo_tipo_direccion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(tipo_direccion)%%>', $combo_tipo_direccion->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(direccion_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cliente_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(inmueble_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipo_direccion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(calle)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(numero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(piso)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(puerta)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(escalera)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(codigo_postal)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(localidad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(provincia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pais)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(referencia_catastral)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(coordenadas_latitud)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(coordenadas_longitud)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(principal)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_alta)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ultima_modificacion)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(direccion_id)%%>', safe_html($urow['direccion_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(direccion_id)%%>', urlencode($urow['direccion_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', safe_html($urow['cliente_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', html_attr($row['cliente_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode($urow['cliente_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', safe_html($urow['inmueble_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', html_attr($row['inmueble_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode($urow['inmueble_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipo_direccion)%%>', safe_html($urow['tipo_direccion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipo_direccion)%%>', html_attr($row['tipo_direccion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_direccion)%%>', urlencode($urow['tipo_direccion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(calle)%%>', safe_html($urow['calle']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(calle)%%>', html_attr($row['calle']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calle)%%>', urlencode($urow['calle']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(numero)%%>', safe_html($urow['numero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(numero)%%>', html_attr($row['numero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(numero)%%>', urlencode($urow['numero']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(piso)%%>', safe_html($urow['piso']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(piso)%%>', html_attr($row['piso']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(piso)%%>', urlencode($urow['piso']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(puerta)%%>', safe_html($urow['puerta']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(puerta)%%>', html_attr($row['puerta']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(puerta)%%>', urlencode($urow['puerta']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(escalera)%%>', safe_html($urow['escalera']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(escalera)%%>', html_attr($row['escalera']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(escalera)%%>', urlencode($urow['escalera']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(codigo_postal)%%>', safe_html($urow['codigo_postal']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(codigo_postal)%%>', html_attr($row['codigo_postal']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(codigo_postal)%%>', urlencode($urow['codigo_postal']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(localidad)%%>', safe_html($urow['localidad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(localidad)%%>', html_attr($row['localidad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(localidad)%%>', urlencode($urow['localidad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(provincia)%%>', safe_html($urow['provincia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(provincia)%%>', html_attr($row['provincia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(provincia)%%>', urlencode($urow['provincia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pais)%%>', safe_html($urow['pais']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pais)%%>', html_attr($row['pais']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pais)%%>', urlencode($urow['pais']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(referencia_catastral)%%>', safe_html($urow['referencia_catastral']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(referencia_catastral)%%>', html_attr($row['referencia_catastral']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia_catastral)%%>', urlencode($urow['referencia_catastral']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(coordenadas_latitud)%%>', safe_html($urow['coordenadas_latitud']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(coordenadas_latitud)%%>', html_attr($row['coordenadas_latitud']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(coordenadas_latitud)%%>', urlencode($urow['coordenadas_latitud']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(coordenadas_longitud)%%>', safe_html($urow['coordenadas_longitud']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(coordenadas_longitud)%%>', html_attr($row['coordenadas_longitud']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(coordenadas_longitud)%%>', urlencode($urow['coordenadas_longitud']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(principal)%%>', safe_html($urow['principal']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(principal)%%>', html_attr($row['principal']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(principal)%%>', urlencode($urow['principal']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_alta)%%>', app_datetime($row['fecha_alta'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_alta)%%>', urlencode(app_datetime($urow['fecha_alta'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(ultima_modificacion)%%>', app_datetime($row['ultima_modificacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ultima_modificacion)%%>', urlencode(app_datetime($urow['ultima_modificacion'], 'dt')), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(direccion_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(direccion_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cliente_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(inmueble_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipo_direccion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_direccion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(calle)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calle)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(numero)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(numero)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(piso)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(piso)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(puerta)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(puerta)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(escalera)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(escalera)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(codigo_postal)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(codigo_postal)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(localidad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(localidad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(provincia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(provincia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pais)%%>', 'Espana', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pais)%%>', urlencode('Espana'), $templateCode);
		$templateCode = str_replace('<%%VALUE(referencia_catastral)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia_catastral)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(coordenadas_latitud)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(coordenadas_latitud)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(coordenadas_longitud)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(coordenadas_longitud)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(principal)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(principal)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_alta)%%>', '<%%creationDateTime%%>curdate()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_alta)%%>', urlencode('<%%creationDateTime%%>curdate()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(ultima_modificacion)%%>', '<%%editingDateTime%%>current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ultima_modificacion)%%>', urlencode('<%%editingDateTime%%>current_timestamp()'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('direcciones');
	if($hasSelectedId) {
		$jdata = get_joined_record('direcciones', $selectedId);
		if($jdata === false) $jdata = get_defaults('direcciones');
		$rdata = $row;
	}
	$templateCode .= loadView('direcciones-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: direcciones_dv
	if(function_exists('direcciones_dv')) {
		$args = [];
		direcciones_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}