<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/direcciones.php');
	include_once(__DIR__ . '/direcciones_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('direcciones');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'direcciones';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`direcciones`.`direccion_id`" => "direccion_id",
		"`direcciones`.`cliente_id`" => "cliente_id",
		"`direcciones`.`inmueble_id`" => "inmueble_id",
		"`direcciones`.`tipo_direccion`" => "tipo_direccion",
		"`direcciones`.`calle`" => "calle",
		"`direcciones`.`numero`" => "numero",
		"`direcciones`.`piso`" => "piso",
		"`direcciones`.`puerta`" => "puerta",
		"`direcciones`.`escalera`" => "escalera",
		"`direcciones`.`codigo_postal`" => "codigo_postal",
		"`direcciones`.`localidad`" => "localidad",
		"`direcciones`.`provincia`" => "provincia",
		"`direcciones`.`pais`" => "pais",
		"`direcciones`.`referencia_catastral`" => "referencia_catastral",
		"`direcciones`.`coordenadas_latitud`" => "coordenadas_latitud",
		"`direcciones`.`coordenadas_longitud`" => "coordenadas_longitud",
		"`direcciones`.`principal`" => "principal",
		"if(`direcciones`.`fecha_alta`,date_format(`direcciones`.`fecha_alta`,'%d/%m/%Y %H:%i'),'')" => "fecha_alta",
		"if(`direcciones`.`ultima_modificacion`,date_format(`direcciones`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`direcciones`.`direccion_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => '`direcciones`.`coordenadas_latitud`',
		16 => '`direcciones`.`coordenadas_longitud`',
		17 => '`direcciones`.`principal`',
		18 => '`direcciones`.`fecha_alta`',
		19 => '`direcciones`.`ultima_modificacion`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`direcciones`.`direccion_id`" => "direccion_id",
		"`direcciones`.`cliente_id`" => "cliente_id",
		"`direcciones`.`inmueble_id`" => "inmueble_id",
		"`direcciones`.`tipo_direccion`" => "tipo_direccion",
		"`direcciones`.`calle`" => "calle",
		"`direcciones`.`numero`" => "numero",
		"`direcciones`.`piso`" => "piso",
		"`direcciones`.`puerta`" => "puerta",
		"`direcciones`.`escalera`" => "escalera",
		"`direcciones`.`codigo_postal`" => "codigo_postal",
		"`direcciones`.`localidad`" => "localidad",
		"`direcciones`.`provincia`" => "provincia",
		"`direcciones`.`pais`" => "pais",
		"`direcciones`.`referencia_catastral`" => "referencia_catastral",
		"`direcciones`.`coordenadas_latitud`" => "coordenadas_latitud",
		"`direcciones`.`coordenadas_longitud`" => "coordenadas_longitud",
		"`direcciones`.`principal`" => "principal",
		"if(`direcciones`.`fecha_alta`,date_format(`direcciones`.`fecha_alta`,'%d/%m/%Y %H:%i'),'')" => "fecha_alta",
		"if(`direcciones`.`ultima_modificacion`,date_format(`direcciones`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`direcciones`.`direccion_id`" => "Direccion id",
		"`direcciones`.`cliente_id`" => "Cliente id",
		"`direcciones`.`inmueble_id`" => "Inmueble id",
		"`direcciones`.`tipo_direccion`" => "Tipo direccion",
		"`direcciones`.`calle`" => "Calle",
		"`direcciones`.`numero`" => "Numero",
		"`direcciones`.`piso`" => "Piso",
		"`direcciones`.`puerta`" => "Puerta",
		"`direcciones`.`escalera`" => "Escalera",
		"`direcciones`.`codigo_postal`" => "Codigo postal",
		"`direcciones`.`localidad`" => "Localidad",
		"`direcciones`.`provincia`" => "Provincia",
		"`direcciones`.`pais`" => "Pais",
		"`direcciones`.`referencia_catastral`" => "Referencia catastral",
		"`direcciones`.`coordenadas_latitud`" => "Coordenadas latitud",
		"`direcciones`.`coordenadas_longitud`" => "Coordenadas longitud",
		"`direcciones`.`principal`" => "Principal",
		"`direcciones`.`fecha_alta`" => "Fecha alta",
		"`direcciones`.`ultima_modificacion`" => "Ultima modificacion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`direcciones`.`direccion_id`" => "direccion_id",
		"`direcciones`.`cliente_id`" => "cliente_id",
		"`direcciones`.`inmueble_id`" => "inmueble_id",
		"`direcciones`.`tipo_direccion`" => "tipo_direccion",
		"`direcciones`.`calle`" => "calle",
		"`direcciones`.`numero`" => "numero",
		"`direcciones`.`piso`" => "piso",
		"`direcciones`.`puerta`" => "puerta",
		"`direcciones`.`escalera`" => "escalera",
		"`direcciones`.`codigo_postal`" => "codigo_postal",
		"`direcciones`.`localidad`" => "localidad",
		"`direcciones`.`provincia`" => "provincia",
		"`direcciones`.`pais`" => "pais",
		"`direcciones`.`referencia_catastral`" => "referencia_catastral",
		"`direcciones`.`coordenadas_latitud`" => "coordenadas_latitud",
		"`direcciones`.`coordenadas_longitud`" => "coordenadas_longitud",
		"`direcciones`.`principal`" => "principal",
		"if(`direcciones`.`fecha_alta`,date_format(`direcciones`.`fecha_alta`,'%d/%m/%Y %H:%i'),'')" => "fecha_alta",
		"if(`direcciones`.`ultima_modificacion`,date_format(`direcciones`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`direcciones` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'direcciones_view.php';
	$x->TableTitle = 'Direcciones';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`direcciones`.`direccion_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Direccion id', 'Cliente id', 'Inmueble id', 'Tipo direccion', 'Calle', 'Numero', 'Piso', 'Puerta', 'Escalera', 'Codigo postal', 'Localidad', 'Provincia', 'Pais', 'Referencia catastral', 'Coordenadas latitud', 'Coordenadas longitud', 'Principal', 'Fecha alta', 'Ultima modificacion', ];
	$x->ColFieldName = ['direccion_id', 'cliente_id', 'inmueble_id', 'tipo_direccion', 'calle', 'numero', 'piso', 'puerta', 'escalera', 'codigo_postal', 'localidad', 'provincia', 'pais', 'referencia_catastral', 'coordenadas_latitud', 'coordenadas_longitud', 'principal', 'fecha_alta', 'ultima_modificacion', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/direcciones_templateTV.html';
	$x->SelectedTemplate = 'templates/direcciones_templateTVS.html';
	$x->TemplateDV = 'templates/direcciones_templateDV.html';
	$x->TemplateDVP = 'templates/direcciones_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: direcciones_init
	$render = true;
	if(function_exists('direcciones_init')) {
		$args = [];
		$render = direcciones_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: direcciones_header
	$headerCode = '';
	if(function_exists('direcciones_header')) {
		$args = [];
		$headerCode = direcciones_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: direcciones_footer
	$footerCode = '';
	if(function_exists('direcciones_footer')) {
		$args = [];
		$footerCode = direcciones_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
