<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/encargos.php');
	include_once(__DIR__ . '/encargos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('encargos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'encargos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`encargos`.`encargo_id`" => "encargo_id",
		"`encargos`.`referencia`" => "referencia",
		"`encargos`.`inmueble_id`" => "inmueble_id",
		"`encargos`.`propietario_id`" => "propietario_id",
		"`encargos`.`estado_id`" => "estado_id",
		"`encargos`.`estado_contacto_id`" => "estado_contacto_id",
		"`encargos`.`motivo`" => "motivo",
		"`encargos`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`encargos`.`precio`" => "precio",
		"`encargos`.`precio_parking_incluido`" => "precio_parking_incluido",
		"`encargos`.`valoracion`" => "valoracion",
		"`encargos`.`valoracion_solo_inmueble`" => "valoracion_solo_inmueble",
		"`encargos`.`nuda_propiedad`" => "nuda_propiedad",
		"`encargos`.`tratabilidad`" => "tratabilidad",
		"if(`encargos`.`fecha_creacion`,date_format(`encargos`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`encargos`.`fecha_modificacion`,date_format(`encargos`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
		"if(`encargos`.`fecha_cierre`,date_format(`encargos`.`fecha_cierre`,'%d/%m/%Y'),'')" => "fecha_cierre",
		"`encargos`.`motivo_cierre_id`" => "motivo_cierre_id",
		"if(`encargos`.`fecha_ultima_cita`,date_format(`encargos`.`fecha_ultima_cita`,'%d/%m/%Y'),'')" => "fecha_ultima_cita",
		"if(`encargos`.`fecha_ultima_actividad`,date_format(`encargos`.`fecha_ultima_actividad`,'%d/%m/%Y'),'')" => "fecha_ultima_actividad",
		"if(`encargos`.`fecha_ultimo_contacto`,date_format(`encargos`.`fecha_ultimo_contacto`,'%d/%m/%Y'),'')" => "fecha_ultimo_contacto",
		"`encargos`.`nota_privada`" => "nota_privada",
		"`encargos`.`llaves_oficina`" => "llaves_oficina",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`encargos`.`estado_id`',
		6 => '`encargos`.`estado_contacto_id`',
		7 => 7,
		8 => '`encargos`.`tipo_procedencia_id`',
		9 => '`encargos`.`precio`',
		10 => '`encargos`.`precio_parking_incluido`',
		11 => '`encargos`.`valoracion`',
		12 => '`encargos`.`valoracion_solo_inmueble`',
		13 => '`encargos`.`nuda_propiedad`',
		14 => '`encargos`.`tratabilidad`',
		15 => '`encargos`.`fecha_creacion`',
		16 => '`encargos`.`fecha_modificacion`',
		17 => '`encargos`.`fecha_cierre`',
		18 => '`encargos`.`motivo_cierre_id`',
		19 => '`encargos`.`fecha_ultima_cita`',
		20 => '`encargos`.`fecha_ultima_actividad`',
		21 => '`encargos`.`fecha_ultimo_contacto`',
		22 => 22,
		23 => '`encargos`.`llaves_oficina`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`encargos`.`encargo_id`" => "encargo_id",
		"`encargos`.`referencia`" => "referencia",
		"`encargos`.`inmueble_id`" => "inmueble_id",
		"`encargos`.`propietario_id`" => "propietario_id",
		"`encargos`.`estado_id`" => "estado_id",
		"`encargos`.`estado_contacto_id`" => "estado_contacto_id",
		"`encargos`.`motivo`" => "motivo",
		"`encargos`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`encargos`.`precio`" => "precio",
		"`encargos`.`precio_parking_incluido`" => "precio_parking_incluido",
		"`encargos`.`valoracion`" => "valoracion",
		"`encargos`.`valoracion_solo_inmueble`" => "valoracion_solo_inmueble",
		"`encargos`.`nuda_propiedad`" => "nuda_propiedad",
		"`encargos`.`tratabilidad`" => "tratabilidad",
		"if(`encargos`.`fecha_creacion`,date_format(`encargos`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`encargos`.`fecha_modificacion`,date_format(`encargos`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
		"if(`encargos`.`fecha_cierre`,date_format(`encargos`.`fecha_cierre`,'%d/%m/%Y'),'')" => "fecha_cierre",
		"`encargos`.`motivo_cierre_id`" => "motivo_cierre_id",
		"if(`encargos`.`fecha_ultima_cita`,date_format(`encargos`.`fecha_ultima_cita`,'%d/%m/%Y'),'')" => "fecha_ultima_cita",
		"if(`encargos`.`fecha_ultima_actividad`,date_format(`encargos`.`fecha_ultima_actividad`,'%d/%m/%Y'),'')" => "fecha_ultima_actividad",
		"if(`encargos`.`fecha_ultimo_contacto`,date_format(`encargos`.`fecha_ultimo_contacto`,'%d/%m/%Y'),'')" => "fecha_ultimo_contacto",
		"`encargos`.`nota_privada`" => "nota_privada",
		"`encargos`.`llaves_oficina`" => "llaves_oficina",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`encargos`.`encargo_id`" => "Encargo id",
		"`encargos`.`referencia`" => "Referencia",
		"`encargos`.`inmueble_id`" => "Inmueble id",
		"`encargos`.`propietario_id`" => "Propietario id",
		"`encargos`.`estado_id`" => "Estado id",
		"`encargos`.`estado_contacto_id`" => "Estado contacto id",
		"`encargos`.`motivo`" => "Motivo",
		"`encargos`.`tipo_procedencia_id`" => "Tipo procedencia id",
		"`encargos`.`precio`" => "Precio",
		"`encargos`.`precio_parking_incluido`" => "Precio parking incluido",
		"`encargos`.`valoracion`" => "Valoracion",
		"`encargos`.`valoracion_solo_inmueble`" => "Valoracion solo inmueble",
		"`encargos`.`nuda_propiedad`" => "Nuda propiedad",
		"`encargos`.`tratabilidad`" => "Tratabilidad",
		"`encargos`.`fecha_creacion`" => "Fecha creacion",
		"`encargos`.`fecha_modificacion`" => "Fecha modificacion",
		"`encargos`.`fecha_cierre`" => "Fecha cierre",
		"`encargos`.`motivo_cierre_id`" => "Motivo cierre id",
		"`encargos`.`fecha_ultima_cita`" => "Fecha ultima cita",
		"`encargos`.`fecha_ultima_actividad`" => "Fecha ultima actividad",
		"`encargos`.`fecha_ultimo_contacto`" => "Fecha ultimo contacto",
		"`encargos`.`nota_privada`" => "Nota privada",
		"`encargos`.`llaves_oficina`" => "Llaves oficina",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`encargos`.`encargo_id`" => "encargo_id",
		"`encargos`.`referencia`" => "referencia",
		"`encargos`.`inmueble_id`" => "inmueble_id",
		"`encargos`.`propietario_id`" => "propietario_id",
		"`encargos`.`estado_id`" => "estado_id",
		"`encargos`.`estado_contacto_id`" => "estado_contacto_id",
		"`encargos`.`motivo`" => "motivo",
		"`encargos`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`encargos`.`precio`" => "precio",
		"`encargos`.`precio_parking_incluido`" => "precio_parking_incluido",
		"`encargos`.`valoracion`" => "valoracion",
		"`encargos`.`valoracion_solo_inmueble`" => "valoracion_solo_inmueble",
		"`encargos`.`nuda_propiedad`" => "nuda_propiedad",
		"`encargos`.`tratabilidad`" => "tratabilidad",
		"if(`encargos`.`fecha_creacion`,date_format(`encargos`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`encargos`.`fecha_modificacion`,date_format(`encargos`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
		"if(`encargos`.`fecha_cierre`,date_format(`encargos`.`fecha_cierre`,'%d/%m/%Y'),'')" => "fecha_cierre",
		"`encargos`.`motivo_cierre_id`" => "motivo_cierre_id",
		"if(`encargos`.`fecha_ultima_cita`,date_format(`encargos`.`fecha_ultima_cita`,'%d/%m/%Y'),'')" => "fecha_ultima_cita",
		"if(`encargos`.`fecha_ultima_actividad`,date_format(`encargos`.`fecha_ultima_actividad`,'%d/%m/%Y'),'')" => "fecha_ultima_actividad",
		"if(`encargos`.`fecha_ultimo_contacto`,date_format(`encargos`.`fecha_ultimo_contacto`,'%d/%m/%Y'),'')" => "fecha_ultimo_contacto",
		"`encargos`.`nota_privada`" => "nota_privada",
		"`encargos`.`llaves_oficina`" => "llaves_oficina",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`encargos` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'encargos_view.php';
	$x->TableTitle = 'Encargos';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`encargos`.`encargo_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Encargo id', 'Referencia', 'Inmueble id', 'Propietario id', 'Estado id', 'Estado contacto id', 'Motivo', 'Tipo procedencia id', 'Precio', 'Precio parking incluido', 'Valoracion', 'Valoracion solo inmueble', 'Nuda propiedad', 'Tratabilidad', 'Fecha creacion', 'Fecha modificacion', 'Fecha cierre', 'Motivo cierre id', 'Fecha ultima cita', 'Fecha ultima actividad', 'Fecha ultimo contacto', 'Nota privada', 'Llaves oficina', ];
	$x->ColFieldName = ['encargo_id', 'referencia', 'inmueble_id', 'propietario_id', 'estado_id', 'estado_contacto_id', 'motivo', 'tipo_procedencia_id', 'precio', 'precio_parking_incluido', 'valoracion', 'valoracion_solo_inmueble', 'nuda_propiedad', 'tratabilidad', 'fecha_creacion', 'fecha_modificacion', 'fecha_cierre', 'motivo_cierre_id', 'fecha_ultima_cita', 'fecha_ultima_actividad', 'fecha_ultimo_contacto', 'nota_privada', 'llaves_oficina', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/encargos_templateTV.html';
	$x->SelectedTemplate = 'templates/encargos_templateTVS.html';
	$x->TemplateDV = 'templates/encargos_templateDV.html';
	$x->TemplateDVP = 'templates/encargos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: encargos_init
	$render = true;
	if(function_exists('encargos_init')) {
		$args = [];
		$render = encargos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: encargos_header
	$headerCode = '';
	if(function_exists('encargos_header')) {
		$args = [];
		$headerCode = encargos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: encargos_footer
	$footerCode = '';
	if(function_exists('encargos_footer')) {
		$args = [];
		$footerCode = encargos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
