<?php

// Data functions (insert, update, delete, form) for table encargos

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function encargos_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('encargos');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'encargo_id' => Request::val('encargo_id', ''),
		'referencia' => Request::val('referencia', ''),
		'inmueble_id' => Request::val('inmueble_id', ''),
		'propietario_id' => Request::val('propietario_id', ''),
		'estado_id' => Request::val('estado_id', ''),
		'estado_contacto_id' => Request::val('estado_contacto_id', ''),
		'motivo' => Request::val('motivo', ''),
		'tipo_procedencia_id' => Request::val('tipo_procedencia_id', ''),
		'precio' => Request::val('precio', ''),
		'precio_parking_incluido' => Request::val('precio_parking_incluido', '0'),
		'valoracion' => Request::val('valoracion', ''),
		'valoracion_solo_inmueble' => Request::val('valoracion_solo_inmueble', ''),
		'nuda_propiedad' => Request::val('nuda_propiedad', '0'),
		'tratabilidad' => Request::val('tratabilidad', ''),
		'fecha_creacion' => parseCode('<%%creationDateTime%%>curdate()', true, true),
		'fecha_cierre' => Request::dateComponents('fecha_cierre', ''),
		'motivo_cierre_id' => Request::val('motivo_cierre_id', ''),
		'fecha_ultima_cita' => Request::dateComponents('fecha_ultima_cita', ''),
		'fecha_ultima_actividad' => Request::dateComponents('fecha_ultima_actividad', ''),
		'fecha_ultimo_contacto' => Request::dateComponents('fecha_ultimo_contacto', ''),
		'nota_privada' => br2nl(Request::val('nota_privada', '')),
		'llaves_oficina' => Request::val('llaves_oficina', '0'),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('encargos', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		encargos_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function encargos_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function encargos_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('encargos', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: encargos_before_delete
	if(function_exists('encargos_before_delete')) {
		$args = [];
		if(!encargos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `encargos` WHERE `encargo_id`='{$selected_id}'", $eo);

	// hook: encargos_after_delete
	if(function_exists('encargos_after_delete')) {
		$args = [];
		encargos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='encargos' AND `pkValue`='{$selected_id}'", $eo);
}

function encargos_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('encargos', $selected_id, 'edit')) return false;

	$data = [
		'encargo_id' => Request::val('encargo_id', ''),
		'referencia' => Request::val('referencia', ''),
		'inmueble_id' => Request::val('inmueble_id', ''),
		'propietario_id' => Request::val('propietario_id', ''),
		'estado_id' => Request::val('estado_id', ''),
		'estado_contacto_id' => Request::val('estado_contacto_id', ''),
		'motivo' => Request::val('motivo', ''),
		'tipo_procedencia_id' => Request::val('tipo_procedencia_id', ''),
		'precio' => Request::val('precio', ''),
		'precio_parking_incluido' => Request::val('precio_parking_incluido', ''),
		'valoracion' => Request::val('valoracion', ''),
		'valoracion_solo_inmueble' => Request::val('valoracion_solo_inmueble', ''),
		'nuda_propiedad' => Request::val('nuda_propiedad', ''),
		'tratabilidad' => Request::val('tratabilidad', ''),
		'fecha_modificacion' => parseCode('<%%editingDateTime%%>current_timestamp()', false, true),
		'fecha_cierre' => Request::dateComponents('fecha_cierre', ''),
		'motivo_cierre_id' => Request::val('motivo_cierre_id', ''),
		'fecha_ultima_cita' => Request::dateComponents('fecha_ultima_cita', ''),
		'fecha_ultima_actividad' => Request::dateComponents('fecha_ultima_actividad', ''),
		'fecha_ultimo_contacto' => Request::dateComponents('fecha_ultimo_contacto', ''),
		'nota_privada' => br2nl(Request::val('nota_privada', '')),
		'llaves_oficina' => Request::val('llaves_oficina', ''),
	];

	if($data['encargo_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Encargo id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['inmueble_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Inmueble id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['propietario_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Propietario id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['estado_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['motivo'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Motivo': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['precio'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Precio': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('encargos', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: encargos_before_update
	if(function_exists('encargos_before_update')) {
		$args = ['old_data' => $old_data];
		if(!encargos_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'encargos',
		backtick_keys_once($set),
		['`encargo_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="encargos_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['encargo_id'];
	$newID = $data['encargo_id'];

	update_calc_fields('encargos', $data['selectedID'], calculated_fields()['encargos']);

	// hook: encargos_after_update
	if(function_exists('encargos_after_update')) {
		if($row = getRecord('encargos', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['encargo_id'];
		$args = ['old_data' => $old_data];
		if(!encargos_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('encargos', $selected_id);

	// if PK value changed, update ownership and $selected_id
	if($selected_id != $newID) {
		update('membership_userrecords', ['pkValue' => $newID], ['pkValue' => $selected_id, 'tableName' => 'encargos']);
		$selected_id = $newID;
	}
}

function encargos_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('encargos');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('encargos', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('encargos', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('encargos', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: fecha_cierre
	$combo_fecha_cierre = new DateCombo;
	$combo_fecha_cierre->DateFormat = "dmy";
	$combo_fecha_cierre->MinYear = defined('encargos.fecha_cierre.MinYear') ? constant('encargos.fecha_cierre.MinYear') : 1900;
	$combo_fecha_cierre->MaxYear = defined('encargos.fecha_cierre.MaxYear') ? constant('encargos.fecha_cierre.MaxYear') : 2100;
	$combo_fecha_cierre->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_cierre->MonthNames = $Translation['month names'];
	$combo_fecha_cierre->NamePrefix = 'fecha_cierre';
	// combobox: fecha_ultima_cita
	$combo_fecha_ultima_cita = new DateCombo;
	$combo_fecha_ultima_cita->DateFormat = "dmy";
	$combo_fecha_ultima_cita->MinYear = defined('encargos.fecha_ultima_cita.MinYear') ? constant('encargos.fecha_ultima_cita.MinYear') : 1900;
	$combo_fecha_ultima_cita->MaxYear = defined('encargos.fecha_ultima_cita.MaxYear') ? constant('encargos.fecha_ultima_cita.MaxYear') : 2100;
	$combo_fecha_ultima_cita->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_ultima_cita->MonthNames = $Translation['month names'];
	$combo_fecha_ultima_cita->NamePrefix = 'fecha_ultima_cita';
	// combobox: fecha_ultima_actividad
	$combo_fecha_ultima_actividad = new DateCombo;
	$combo_fecha_ultima_actividad->DateFormat = "dmy";
	$combo_fecha_ultima_actividad->MinYear = defined('encargos.fecha_ultima_actividad.MinYear') ? constant('encargos.fecha_ultima_actividad.MinYear') : 1900;
	$combo_fecha_ultima_actividad->MaxYear = defined('encargos.fecha_ultima_actividad.MaxYear') ? constant('encargos.fecha_ultima_actividad.MaxYear') : 2100;
	$combo_fecha_ultima_actividad->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_ultima_actividad->MonthNames = $Translation['month names'];
	$combo_fecha_ultima_actividad->NamePrefix = 'fecha_ultima_actividad';
	// combobox: fecha_ultimo_contacto
	$combo_fecha_ultimo_contacto = new DateCombo;
	$combo_fecha_ultimo_contacto->DateFormat = "dmy";
	$combo_fecha_ultimo_contacto->MinYear = defined('encargos.fecha_ultimo_contacto.MinYear') ? constant('encargos.fecha_ultimo_contacto.MinYear') : 1900;
	$combo_fecha_ultimo_contacto->MaxYear = defined('encargos.fecha_ultimo_contacto.MaxYear') ? constant('encargos.fecha_ultimo_contacto.MaxYear') : 2100;
	$combo_fecha_ultimo_contacto->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_ultimo_contacto->MonthNames = $Translation['month names'];
	$combo_fecha_ultimo_contacto->NamePrefix = 'fecha_ultimo_contacto';

	if($hasSelectedId) {
		if(!($row = getRecord('encargos', $selectedId))) {
			return error_message($Translation['No records found'], 'encargos_view.php', false);
		}
		$combo_fecha_cierre->DefaultDate = $row['fecha_cierre'];
		$combo_fecha_ultima_cita->DefaultDate = $row['fecha_ultima_cita'];
		$combo_fecha_ultima_actividad->DefaultDate = $row['fecha_ultima_actividad'];
		$combo_fecha_ultimo_contacto->DefaultDate = $row['fecha_ultimo_contacto'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/encargos_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/encargos_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#encargo_id').replaceWith('<div class=\"form-control-static\" id=\"encargo_id\">' + (\$j('#encargo_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#referencia').replaceWith('<div class=\"form-control-static\" id=\"referencia\">' + (\$j('#referencia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#inmueble_id').replaceWith('<div class=\"form-control-static\" id=\"inmueble_id\">' + (\$j('#inmueble_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#propietario_id').replaceWith('<div class=\"form-control-static\" id=\"propietario_id\">' + (\$j('#propietario_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado_id').replaceWith('<div class=\"form-control-static\" id=\"estado_id\">' + (\$j('#estado_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado_contacto_id').replaceWith('<div class=\"form-control-static\" id=\"estado_contacto_id\">' + (\$j('#estado_contacto_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#motivo').replaceWith('<div class=\"form-control-static\" id=\"motivo\">' + (\$j('#motivo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#tipo_procedencia_id').replaceWith('<div class=\"form-control-static\" id=\"tipo_procedencia_id\">' + (\$j('#tipo_procedencia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#precio').replaceWith('<div class=\"form-control-static\" id=\"precio\">' + (\$j('#precio').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#precio_parking_incluido').replaceWith('<div class=\"form-control-static\" id=\"precio_parking_incluido\">' + (\$j('#precio_parking_incluido').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#valoracion').replaceWith('<div class=\"form-control-static\" id=\"valoracion\">' + (\$j('#valoracion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#valoracion_solo_inmueble').replaceWith('<div class=\"form-control-static\" id=\"valoracion_solo_inmueble\">' + (\$j('#valoracion_solo_inmueble').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#nuda_propiedad').replaceWith('<div class=\"form-control-static\" id=\"nuda_propiedad\">' + (\$j('#nuda_propiedad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#tratabilidad').replaceWith('<div class=\"form-control-static\" id=\"tratabilidad\">' + (\$j('#tratabilidad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#fecha_cierre').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_cierreDay, #fecha_cierreMonth, #fecha_cierreYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#motivo_cierre_id').replaceWith('<div class=\"form-control-static\" id=\"motivo_cierre_id\">' + (\$j('#motivo_cierre_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#fecha_ultima_cita').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_ultima_citaDay, #fecha_ultima_citaMonth, #fecha_ultima_citaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#fecha_ultima_actividad').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_ultima_actividadDay, #fecha_ultima_actividadMonth, #fecha_ultima_actividadYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#fecha_ultimo_contacto').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_ultimo_contactoDay, #fecha_ultimo_contactoMonth, #fecha_ultimo_contactoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#nota_privada').replaceWith('<div class=\"form-control-static\" id=\"nota_privada\">' + (\$j('#nota_privada').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#llaves_oficina').replaceWith('<div class=\"form-control-static\" id=\"llaves_oficina\">' + (\$j('#llaves_oficina').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(fecha_cierre)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_cierre->GetHTML(true) . '</div>' :
			$combo_fecha_cierre->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_cierre)%%>', $combo_fecha_cierre->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_ultima_cita)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_ultima_cita->GetHTML(true) . '</div>' :
			$combo_fecha_ultima_cita->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_ultima_cita)%%>', $combo_fecha_ultima_cita->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_ultima_actividad)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_ultima_actividad->GetHTML(true) . '</div>' :
			$combo_fecha_ultima_actividad->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_ultima_actividad)%%>', $combo_fecha_ultima_actividad->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_ultimo_contacto)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_ultimo_contacto->GetHTML(true) . '</div>' :
			$combo_fecha_ultimo_contacto->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_ultimo_contacto)%%>', $combo_fecha_ultimo_contacto->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(encargo_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(referencia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(inmueble_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(propietario_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado_contacto_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(motivo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipo_procedencia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(precio)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(precio_parking_incluido)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(valoracion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(valoracion_solo_inmueble)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nuda_propiedad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tratabilidad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_creacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_modificacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_cierre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(motivo_cierre_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_ultima_cita)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_ultima_actividad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_ultimo_contacto)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nota_privada)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(llaves_oficina)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(encargo_id)%%>', safe_html($urow['encargo_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(encargo_id)%%>', html_attr($row['encargo_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(encargo_id)%%>', urlencode($urow['encargo_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', safe_html($urow['referencia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', html_attr($row['referencia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode($urow['referencia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', safe_html($urow['inmueble_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', html_attr($row['inmueble_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode($urow['inmueble_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(propietario_id)%%>', safe_html($urow['propietario_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(propietario_id)%%>', html_attr($row['propietario_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(propietario_id)%%>', urlencode($urow['propietario_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado_id)%%>', safe_html($urow['estado_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado_id)%%>', html_attr($row['estado_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_id)%%>', urlencode($urow['estado_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado_contacto_id)%%>', safe_html($urow['estado_contacto_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado_contacto_id)%%>', html_attr($row['estado_contacto_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_contacto_id)%%>', urlencode($urow['estado_contacto_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(motivo)%%>', safe_html($urow['motivo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(motivo)%%>', html_attr($row['motivo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivo)%%>', urlencode($urow['motivo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipo_procedencia_id)%%>', safe_html($urow['tipo_procedencia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipo_procedencia_id)%%>', html_attr($row['tipo_procedencia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_procedencia_id)%%>', urlencode($urow['tipo_procedencia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(precio)%%>', safe_html($urow['precio']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(precio)%%>', html_attr($row['precio']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precio)%%>', urlencode($urow['precio']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(precio_parking_incluido)%%>', safe_html($urow['precio_parking_incluido']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(precio_parking_incluido)%%>', html_attr($row['precio_parking_incluido']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precio_parking_incluido)%%>', urlencode($urow['precio_parking_incluido']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(valoracion)%%>', safe_html($urow['valoracion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(valoracion)%%>', html_attr($row['valoracion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion)%%>', urlencode($urow['valoracion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(valoracion_solo_inmueble)%%>', safe_html($urow['valoracion_solo_inmueble']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(valoracion_solo_inmueble)%%>', html_attr($row['valoracion_solo_inmueble']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion_solo_inmueble)%%>', urlencode($urow['valoracion_solo_inmueble']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nuda_propiedad)%%>', safe_html($urow['nuda_propiedad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nuda_propiedad)%%>', html_attr($row['nuda_propiedad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nuda_propiedad)%%>', urlencode($urow['nuda_propiedad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tratabilidad)%%>', safe_html($urow['tratabilidad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tratabilidad)%%>', html_attr($row['tratabilidad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tratabilidad)%%>', urlencode($urow['tratabilidad']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_creacion)%%>', app_datetime($row['fecha_creacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_creacion)%%>', urlencode(app_datetime($urow['fecha_creacion'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_modificacion)%%>', app_datetime($row['fecha_modificacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_modificacion)%%>', urlencode(app_datetime($urow['fecha_modificacion'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_cierre)%%>', app_datetime($row['fecha_cierre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_cierre)%%>', urlencode(app_datetime($urow['fecha_cierre'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(motivo_cierre_id)%%>', safe_html($urow['motivo_cierre_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(motivo_cierre_id)%%>', html_attr($row['motivo_cierre_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivo_cierre_id)%%>', urlencode($urow['motivo_cierre_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultima_cita)%%>', app_datetime($row['fecha_ultima_cita']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultima_cita)%%>', urlencode(app_datetime($urow['fecha_ultima_cita'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultima_actividad)%%>', app_datetime($row['fecha_ultima_actividad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultima_actividad)%%>', urlencode(app_datetime($urow['fecha_ultima_actividad'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultimo_contacto)%%>', app_datetime($row['fecha_ultimo_contacto']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultimo_contacto)%%>', urlencode(app_datetime($urow['fecha_ultimo_contacto'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(nota_privada)%%>', safe_html($urow['nota_privada'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nota_privada)%%>', urlencode($urow['nota_privada']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(llaves_oficina)%%>', safe_html($urow['llaves_oficina']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(llaves_oficina)%%>', html_attr($row['llaves_oficina']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(llaves_oficina)%%>', urlencode($urow['llaves_oficina']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(encargo_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(encargo_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(referencia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(inmueble_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(propietario_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(propietario_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado_contacto_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_contacto_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(motivo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipo_procedencia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_procedencia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(precio)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precio)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(precio_parking_incluido)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precio_parking_incluido)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(valoracion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(valoracion_solo_inmueble)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion_solo_inmueble)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nuda_propiedad)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nuda_propiedad)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(tratabilidad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tratabilidad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_creacion)%%>', '<%%creationDateTime%%>curdate()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_creacion)%%>', urlencode('<%%creationDateTime%%>curdate()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_modificacion)%%>', '<%%editingDateTime%%>current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_modificacion)%%>', urlencode('<%%editingDateTime%%>current_timestamp()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_cierre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_cierre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(motivo_cierre_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivo_cierre_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultima_cita)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultima_cita)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultima_actividad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultima_actividad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultimo_contacto)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultimo_contacto)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nota_privada)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nota_privada)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(llaves_oficina)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(llaves_oficina)%%>', urlencode('0'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('encargos');
	if($hasSelectedId) {
		$jdata = get_joined_record('encargos', $selectedId);
		if($jdata === false) $jdata = get_defaults('encargos');
		$rdata = $row;
	}
	$templateCode .= loadView('encargos-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: encargos_dv
	if(function_exists('encargos_dv')) {
		$args = [];
		encargos_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}