<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/estados_noticia.php');
	include_once(__DIR__ . '/estados_noticia_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('estados_noticia');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'estados_noticia';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`estados_noticia`.`estado_noticia_id`" => "estado_noticia_id",
		"`estados_noticia`.`nombre`" => "nombre",
		"`estados_noticia`.`descripcion`" => "descripcion",
		"`estados_noticia`.`orden`" => "orden",
		"`estados_noticia`.`color`" => "color",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`estados_noticia`.`estado_noticia_id`',
		2 => 2,
		3 => 3,
		4 => '`estados_noticia`.`orden`',
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`estados_noticia`.`estado_noticia_id`" => "estado_noticia_id",
		"`estados_noticia`.`nombre`" => "nombre",
		"`estados_noticia`.`descripcion`" => "descripcion",
		"`estados_noticia`.`orden`" => "orden",
		"`estados_noticia`.`color`" => "color",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`estados_noticia`.`estado_noticia_id`" => "Estado noticia id",
		"`estados_noticia`.`nombre`" => "Nombre",
		"`estados_noticia`.`descripcion`" => "Descripcion",
		"`estados_noticia`.`orden`" => "Orden",
		"`estados_noticia`.`color`" => "Color",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`estados_noticia`.`estado_noticia_id`" => "estado_noticia_id",
		"`estados_noticia`.`nombre`" => "nombre",
		"`estados_noticia`.`descripcion`" => "descripcion",
		"`estados_noticia`.`orden`" => "orden",
		"`estados_noticia`.`color`" => "color",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`estados_noticia` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'estados_noticia_view.php';
	$x->TableTitle = 'Estados noticia';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`estados_noticia`.`estado_noticia_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Estado noticia id', 'Nombre', 'Descripcion', 'Orden', 'Color', ];
	$x->ColFieldName = ['estado_noticia_id', 'nombre', 'descripcion', 'orden', 'color', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/estados_noticia_templateTV.html';
	$x->SelectedTemplate = 'templates/estados_noticia_templateTVS.html';
	$x->TemplateDV = 'templates/estados_noticia_templateDV.html';
	$x->TemplateDVP = 'templates/estados_noticia_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: estados_noticia_init
	$render = true;
	if(function_exists('estados_noticia_init')) {
		$args = [];
		$render = estados_noticia_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: estados_noticia_header
	$headerCode = '';
	if(function_exists('estados_noticia_header')) {
		$args = [];
		$headerCode = estados_noticia_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: estados_noticia_footer
	$footerCode = '';
	if(function_exists('estados_noticia_footer')) {
		$args = [];
		$footerCode = estados_noticia_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
