<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/estados_contacto.php');
	include_once(__DIR__ . '/estados_contacto_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('estados_contacto');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'estados_contacto';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`estados_contacto`.`estado_contacto_id`" => "estado_contacto_id",
		"`estados_contacto`.`nombre`" => "nombre",
		"`estados_contacto`.`descripcion`" => "descripcion",
		"`estados_contacto`.`dias_inactividad_min`" => "dias_inactividad_min",
		"`estados_contacto`.`dias_inactividad_max`" => "dias_inactividad_max",
		"`estados_contacto`.`orden`" => "orden",
		"`estados_contacto`.`color`" => "color",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`estados_contacto`.`estado_contacto_id`',
		2 => 2,
		3 => 3,
		4 => '`estados_contacto`.`dias_inactividad_min`',
		5 => '`estados_contacto`.`dias_inactividad_max`',
		6 => '`estados_contacto`.`orden`',
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`estados_contacto`.`estado_contacto_id`" => "estado_contacto_id",
		"`estados_contacto`.`nombre`" => "nombre",
		"`estados_contacto`.`descripcion`" => "descripcion",
		"`estados_contacto`.`dias_inactividad_min`" => "dias_inactividad_min",
		"`estados_contacto`.`dias_inactividad_max`" => "dias_inactividad_max",
		"`estados_contacto`.`orden`" => "orden",
		"`estados_contacto`.`color`" => "color",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`estados_contacto`.`estado_contacto_id`" => "Estado contacto id",
		"`estados_contacto`.`nombre`" => "Nombre",
		"`estados_contacto`.`descripcion`" => "Descripcion",
		"`estados_contacto`.`dias_inactividad_min`" => "Dias inactividad min",
		"`estados_contacto`.`dias_inactividad_max`" => "Dias inactividad max",
		"`estados_contacto`.`orden`" => "Orden",
		"`estados_contacto`.`color`" => "Color",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`estados_contacto`.`estado_contacto_id`" => "estado_contacto_id",
		"`estados_contacto`.`nombre`" => "nombre",
		"`estados_contacto`.`descripcion`" => "descripcion",
		"`estados_contacto`.`dias_inactividad_min`" => "dias_inactividad_min",
		"`estados_contacto`.`dias_inactividad_max`" => "dias_inactividad_max",
		"`estados_contacto`.`orden`" => "orden",
		"`estados_contacto`.`color`" => "color",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`estados_contacto` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'estados_contacto_view.php';
	$x->TableTitle = 'Estados contacto';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`estados_contacto`.`estado_contacto_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Estado contacto id', 'Nombre', 'Descripcion', 'Dias inactividad min', 'Dias inactividad max', 'Orden', 'Color', ];
	$x->ColFieldName = ['estado_contacto_id', 'nombre', 'descripcion', 'dias_inactividad_min', 'dias_inactividad_max', 'orden', 'color', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/estados_contacto_templateTV.html';
	$x->SelectedTemplate = 'templates/estados_contacto_templateTVS.html';
	$x->TemplateDV = 'templates/estados_contacto_templateDV.html';
	$x->TemplateDVP = 'templates/estados_contacto_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: estados_contacto_init
	$render = true;
	if(function_exists('estados_contacto_init')) {
		$args = [];
		$render = estados_contacto_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: estados_contacto_header
	$headerCode = '';
	if(function_exists('estados_contacto_header')) {
		$args = [];
		$headerCode = estados_contacto_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: estados_contacto_footer
	$footerCode = '';
	if(function_exists('estados_contacto_footer')) {
		$args = [];
		$footerCode = estados_contacto_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
