<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/inmuebles.php');
	include_once(__DIR__ . '/inmuebles_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('inmuebles');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'inmuebles';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`inmuebles`.`inmueble_id`" => "inmueble_id",
		"`inmuebles`.`referencia`" => "referencia",
		"`inmuebles`.`propietario_id`" => "propietario_id",
		"`inmuebles`.`estado`" => "estado",
		"`inmuebles`.`tipologia_id`" => "tipologia_id",
		"`inmuebles`.`subtipologia_id`" => "subtipologia_id",
		"`inmuebles`.`direccion_id`" => "direccion_id",
		"`inmuebles`.`zona_id`" => "zona_id",
		"`inmuebles`.`dormitorios`" => "dormitorios",
		"`inmuebles`.`banos`" => "banos",
		"`inmuebles`.`aseos`" => "aseos",
		"`inmuebles`.`m2_utiles`" => "m2_utiles",
		"`inmuebles`.`m2_construidos`" => "m2_construidos",
		"`inmuebles`.`m2_terraza`" => "m2_terraza",
		"`inmuebles`.`altura`" => "altura",
		"`inmuebles`.`orientacion`" => "orientacion",
		"`inmuebles`.`estado_conservacion`" => "estado_conservacion",
		"`inmuebles`.`ano_construccion`" => "ano_construccion",
		"`inmuebles`.`ano_reforma`" => "ano_reforma",
		"`inmuebles`.`ascensor`" => "ascensor",
		"`inmuebles`.`terraza`" => "terraza",
		"`inmuebles`.`balcon`" => "balcon",
		"`inmuebles`.`garaje`" => "garaje",
		"`inmuebles`.`trastero`" => "trastero",
		"`inmuebles`.`calefaccion_tipo`" => "calefaccion_tipo",
		"`inmuebles`.`climatizacion`" => "climatizacion",
		"`inmuebles`.`certificado_energetico`" => "certificado_energetico",
		"`inmuebles`.`consumo_energetico`" => "consumo_energetico",
		"`inmuebles`.`emisiones_co2`" => "emisiones_co2",
		"`inmuebles`.`referencia_catastral`" => "referencia_catastral",
		"if(`inmuebles`.`fecha_alta`,date_format(`inmuebles`.`fecha_alta`,'%d/%m/%Y %H:%i'),'')" => "fecha_alta",
		"if(`inmuebles`.`ultima_modificacion`,date_format(`inmuebles`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
		"`inmuebles`.`llaves_oficina`" => "llaves_oficina",
		"`inmuebles`.`notas_privadas`" => "notas_privadas",
		"`inmuebles`.`observaciones`" => "observaciones",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`inmuebles`.`tipologia_id`',
		6 => '`inmuebles`.`subtipologia_id`',
		7 => '`inmuebles`.`direccion_id`',
		8 => '`inmuebles`.`zona_id`',
		9 => '`inmuebles`.`dormitorios`',
		10 => '`inmuebles`.`banos`',
		11 => '`inmuebles`.`aseos`',
		12 => '`inmuebles`.`m2_utiles`',
		13 => '`inmuebles`.`m2_construidos`',
		14 => '`inmuebles`.`m2_terraza`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => '`inmuebles`.`ano_construccion`',
		19 => '`inmuebles`.`ano_reforma`',
		20 => '`inmuebles`.`ascensor`',
		21 => '`inmuebles`.`terraza`',
		22 => '`inmuebles`.`balcon`',
		23 => '`inmuebles`.`garaje`',
		24 => '`inmuebles`.`trastero`',
		25 => 25,
		26 => 26,
		27 => 27,
		28 => '`inmuebles`.`consumo_energetico`',
		29 => '`inmuebles`.`emisiones_co2`',
		30 => 30,
		31 => '`inmuebles`.`fecha_alta`',
		32 => '`inmuebles`.`ultima_modificacion`',
		33 => '`inmuebles`.`llaves_oficina`',
		34 => 34,
		35 => 35,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`inmuebles`.`inmueble_id`" => "inmueble_id",
		"`inmuebles`.`referencia`" => "referencia",
		"`inmuebles`.`propietario_id`" => "propietario_id",
		"`inmuebles`.`estado`" => "estado",
		"`inmuebles`.`tipologia_id`" => "tipologia_id",
		"`inmuebles`.`subtipologia_id`" => "subtipologia_id",
		"`inmuebles`.`direccion_id`" => "direccion_id",
		"`inmuebles`.`zona_id`" => "zona_id",
		"`inmuebles`.`dormitorios`" => "dormitorios",
		"`inmuebles`.`banos`" => "banos",
		"`inmuebles`.`aseos`" => "aseos",
		"`inmuebles`.`m2_utiles`" => "m2_utiles",
		"`inmuebles`.`m2_construidos`" => "m2_construidos",
		"`inmuebles`.`m2_terraza`" => "m2_terraza",
		"`inmuebles`.`altura`" => "altura",
		"`inmuebles`.`orientacion`" => "orientacion",
		"`inmuebles`.`estado_conservacion`" => "estado_conservacion",
		"`inmuebles`.`ano_construccion`" => "ano_construccion",
		"`inmuebles`.`ano_reforma`" => "ano_reforma",
		"`inmuebles`.`ascensor`" => "ascensor",
		"`inmuebles`.`terraza`" => "terraza",
		"`inmuebles`.`balcon`" => "balcon",
		"`inmuebles`.`garaje`" => "garaje",
		"`inmuebles`.`trastero`" => "trastero",
		"`inmuebles`.`calefaccion_tipo`" => "calefaccion_tipo",
		"`inmuebles`.`climatizacion`" => "climatizacion",
		"`inmuebles`.`certificado_energetico`" => "certificado_energetico",
		"`inmuebles`.`consumo_energetico`" => "consumo_energetico",
		"`inmuebles`.`emisiones_co2`" => "emisiones_co2",
		"`inmuebles`.`referencia_catastral`" => "referencia_catastral",
		"if(`inmuebles`.`fecha_alta`,date_format(`inmuebles`.`fecha_alta`,'%d/%m/%Y %H:%i'),'')" => "fecha_alta",
		"if(`inmuebles`.`ultima_modificacion`,date_format(`inmuebles`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
		"`inmuebles`.`llaves_oficina`" => "llaves_oficina",
		"`inmuebles`.`notas_privadas`" => "notas_privadas",
		"`inmuebles`.`observaciones`" => "observaciones",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`inmuebles`.`inmueble_id`" => "Inmueble id",
		"`inmuebles`.`referencia`" => "Referencia",
		"`inmuebles`.`propietario_id`" => "Propietario id",
		"`inmuebles`.`estado`" => "Estado",
		"`inmuebles`.`tipologia_id`" => "Tipologia id",
		"`inmuebles`.`subtipologia_id`" => "Subtipologia id",
		"`inmuebles`.`direccion_id`" => "Direccion id",
		"`inmuebles`.`zona_id`" => "Zona id",
		"`inmuebles`.`dormitorios`" => "Dormitorios",
		"`inmuebles`.`banos`" => "Banos",
		"`inmuebles`.`aseos`" => "Aseos",
		"`inmuebles`.`m2_utiles`" => "M2 utiles",
		"`inmuebles`.`m2_construidos`" => "M2 construidos",
		"`inmuebles`.`m2_terraza`" => "M2 terraza",
		"`inmuebles`.`altura`" => "Altura",
		"`inmuebles`.`orientacion`" => "Orientacion",
		"`inmuebles`.`estado_conservacion`" => "Estado conservacion",
		"`inmuebles`.`ano_construccion`" => "Ano construccion",
		"`inmuebles`.`ano_reforma`" => "Ano reforma",
		"`inmuebles`.`ascensor`" => "Ascensor",
		"`inmuebles`.`terraza`" => "Terraza",
		"`inmuebles`.`balcon`" => "Balcon",
		"`inmuebles`.`garaje`" => "Garaje",
		"`inmuebles`.`trastero`" => "Trastero",
		"`inmuebles`.`calefaccion_tipo`" => "Calefaccion tipo",
		"`inmuebles`.`climatizacion`" => "Climatizacion",
		"`inmuebles`.`certificado_energetico`" => "Certificado energetico",
		"`inmuebles`.`consumo_energetico`" => "Consumo energetico",
		"`inmuebles`.`emisiones_co2`" => "Emisiones co2",
		"`inmuebles`.`referencia_catastral`" => "Referencia catastral",
		"`inmuebles`.`fecha_alta`" => "Fecha alta",
		"`inmuebles`.`ultima_modificacion`" => "Ultima modificacion",
		"`inmuebles`.`llaves_oficina`" => "Llaves oficina",
		"`inmuebles`.`notas_privadas`" => "Notas privadas",
		"`inmuebles`.`observaciones`" => "Observaciones",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`inmuebles`.`inmueble_id`" => "inmueble_id",
		"`inmuebles`.`referencia`" => "referencia",
		"`inmuebles`.`propietario_id`" => "propietario_id",
		"`inmuebles`.`estado`" => "estado",
		"`inmuebles`.`tipologia_id`" => "tipologia_id",
		"`inmuebles`.`subtipologia_id`" => "subtipologia_id",
		"`inmuebles`.`direccion_id`" => "direccion_id",
		"`inmuebles`.`zona_id`" => "zona_id",
		"`inmuebles`.`dormitorios`" => "dormitorios",
		"`inmuebles`.`banos`" => "banos",
		"`inmuebles`.`aseos`" => "aseos",
		"`inmuebles`.`m2_utiles`" => "m2_utiles",
		"`inmuebles`.`m2_construidos`" => "m2_construidos",
		"`inmuebles`.`m2_terraza`" => "m2_terraza",
		"`inmuebles`.`altura`" => "altura",
		"`inmuebles`.`orientacion`" => "orientacion",
		"`inmuebles`.`estado_conservacion`" => "estado_conservacion",
		"`inmuebles`.`ano_construccion`" => "ano_construccion",
		"`inmuebles`.`ano_reforma`" => "ano_reforma",
		"`inmuebles`.`ascensor`" => "ascensor",
		"`inmuebles`.`terraza`" => "terraza",
		"`inmuebles`.`balcon`" => "balcon",
		"`inmuebles`.`garaje`" => "garaje",
		"`inmuebles`.`trastero`" => "trastero",
		"`inmuebles`.`calefaccion_tipo`" => "calefaccion_tipo",
		"`inmuebles`.`climatizacion`" => "climatizacion",
		"`inmuebles`.`certificado_energetico`" => "certificado_energetico",
		"`inmuebles`.`consumo_energetico`" => "consumo_energetico",
		"`inmuebles`.`emisiones_co2`" => "emisiones_co2",
		"`inmuebles`.`referencia_catastral`" => "referencia_catastral",
		"if(`inmuebles`.`fecha_alta`,date_format(`inmuebles`.`fecha_alta`,'%d/%m/%Y %H:%i'),'')" => "fecha_alta",
		"if(`inmuebles`.`ultima_modificacion`,date_format(`inmuebles`.`ultima_modificacion`,'%d/%m/%Y %H:%i'),'')" => "ultima_modificacion",
		"`inmuebles`.`llaves_oficina`" => "llaves_oficina",
		"`inmuebles`.`notas_privadas`" => "notas_privadas",
		"`inmuebles`.`observaciones`" => "observaciones",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`inmuebles` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'inmuebles_view.php';
	$x->TableTitle = 'Inmuebles';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`inmuebles`.`inmueble_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Inmueble id', 'Referencia', 'Propietario id', 'Estado', 'Tipologia id', 'Subtipologia id', 'Direccion id', 'Zona id', 'Dormitorios', 'Banos', 'Aseos', 'M2 utiles', 'M2 construidos', 'M2 terraza', 'Altura', 'Orientacion', 'Estado conservacion', 'Ano construccion', 'Ano reforma', 'Ascensor', 'Terraza', 'Balcon', 'Garaje', 'Trastero', 'Calefaccion tipo', 'Climatizacion', 'Certificado energetico', 'Consumo energetico', 'Emisiones co2', 'Referencia catastral', 'Fecha alta', 'Ultima modificacion', 'Llaves oficina', 'Notas privadas', 'Observaciones', ];
	$x->ColFieldName = ['inmueble_id', 'referencia', 'propietario_id', 'estado', 'tipologia_id', 'subtipologia_id', 'direccion_id', 'zona_id', 'dormitorios', 'banos', 'aseos', 'm2_utiles', 'm2_construidos', 'm2_terraza', 'altura', 'orientacion', 'estado_conservacion', 'ano_construccion', 'ano_reforma', 'ascensor', 'terraza', 'balcon', 'garaje', 'trastero', 'calefaccion_tipo', 'climatizacion', 'certificado_energetico', 'consumo_energetico', 'emisiones_co2', 'referencia_catastral', 'fecha_alta', 'ultima_modificacion', 'llaves_oficina', 'notas_privadas', 'observaciones', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/inmuebles_templateTV.html';
	$x->SelectedTemplate = 'templates/inmuebles_templateTVS.html';
	$x->TemplateDV = 'templates/inmuebles_templateDV.html';
	$x->TemplateDVP = 'templates/inmuebles_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: inmuebles_init
	$render = true;
	if(function_exists('inmuebles_init')) {
		$args = [];
		$render = inmuebles_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: inmuebles_header
	$headerCode = '';
	if(function_exists('inmuebles_header')) {
		$args = [];
		$headerCode = inmuebles_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: inmuebles_footer
	$footerCode = '';
	if(function_exists('inmuebles_footer')) {
		$args = [];
		$footerCode = inmuebles_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
