<?php

// Data functions (insert, update, delete, form) for table inmuebles

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function inmuebles_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('inmuebles');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'inmueble_id' => Request::val('inmueble_id', ''),
		'referencia' => Request::val('referencia', ''),
		'propietario_id' => Request::val('propietario_id', ''),
		'estado' => Request::val('estado', 'Disponible'),
		'tipologia_id' => Request::val('tipologia_id', ''),
		'subtipologia_id' => Request::val('subtipologia_id', ''),
		'direccion_id' => Request::val('direccion_id', ''),
		'zona_id' => Request::val('zona_id', ''),
		'dormitorios' => Request::val('dormitorios', ''),
		'banos' => Request::val('banos', ''),
		'aseos' => Request::val('aseos', ''),
		'm2_utiles' => Request::val('m2_utiles', ''),
		'm2_construidos' => Request::val('m2_construidos', ''),
		'm2_terraza' => Request::val('m2_terraza', ''),
		'altura' => Request::val('altura', ''),
		'orientacion' => Request::val('orientacion', ''),
		'estado_conservacion' => Request::val('estado_conservacion', ''),
		'ano_construccion' => Request::val('ano_construccion', ''),
		'ano_reforma' => Request::val('ano_reforma', ''),
		'ascensor' => Request::val('ascensor', '0'),
		'terraza' => Request::val('terraza', '0'),
		'balcon' => Request::val('balcon', '0'),
		'garaje' => Request::val('garaje', '0'),
		'trastero' => Request::val('trastero', '0'),
		'calefaccion_tipo' => Request::val('calefaccion_tipo', ''),
		'climatizacion' => Request::val('climatizacion', ''),
		'certificado_energetico' => Request::val('certificado_energetico', ''),
		'consumo_energetico' => Request::val('consumo_energetico', ''),
		'emisiones_co2' => Request::val('emisiones_co2', ''),
		'referencia_catastral' => Request::val('referencia_catastral', ''),
		'fecha_alta' => parseCode('<%%creationDateTime%%>curdate()', true, true),
		'llaves_oficina' => Request::val('llaves_oficina', '0'),
		'notas_privadas' => br2nl(Request::val('notas_privadas', '')),
		'observaciones' => br2nl(Request::val('observaciones', '')),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('inmuebles', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		inmuebles_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function inmuebles_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function inmuebles_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('inmuebles', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: inmuebles_before_delete
	if(function_exists('inmuebles_before_delete')) {
		$args = [];
		if(!inmuebles_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `inmuebles` WHERE `inmueble_id`='{$selected_id}'", $eo);

	// hook: inmuebles_after_delete
	if(function_exists('inmuebles_after_delete')) {
		$args = [];
		inmuebles_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='inmuebles' AND `pkValue`='{$selected_id}'", $eo);
}

function inmuebles_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('inmuebles', $selected_id, 'edit')) return false;

	$data = [
		'inmueble_id' => Request::val('inmueble_id', ''),
		'referencia' => Request::val('referencia', ''),
		'propietario_id' => Request::val('propietario_id', ''),
		'estado' => Request::val('estado', ''),
		'tipologia_id' => Request::val('tipologia_id', ''),
		'subtipologia_id' => Request::val('subtipologia_id', ''),
		'direccion_id' => Request::val('direccion_id', ''),
		'zona_id' => Request::val('zona_id', ''),
		'dormitorios' => Request::val('dormitorios', ''),
		'banos' => Request::val('banos', ''),
		'aseos' => Request::val('aseos', ''),
		'm2_utiles' => Request::val('m2_utiles', ''),
		'm2_construidos' => Request::val('m2_construidos', ''),
		'm2_terraza' => Request::val('m2_terraza', ''),
		'altura' => Request::val('altura', ''),
		'orientacion' => Request::val('orientacion', ''),
		'estado_conservacion' => Request::val('estado_conservacion', ''),
		'ano_construccion' => Request::val('ano_construccion', ''),
		'ano_reforma' => Request::val('ano_reforma', ''),
		'ascensor' => Request::val('ascensor', ''),
		'terraza' => Request::val('terraza', ''),
		'balcon' => Request::val('balcon', ''),
		'garaje' => Request::val('garaje', ''),
		'trastero' => Request::val('trastero', ''),
		'calefaccion_tipo' => Request::val('calefaccion_tipo', ''),
		'climatizacion' => Request::val('climatizacion', ''),
		'certificado_energetico' => Request::val('certificado_energetico', ''),
		'consumo_energetico' => Request::val('consumo_energetico', ''),
		'emisiones_co2' => Request::val('emisiones_co2', ''),
		'referencia_catastral' => Request::val('referencia_catastral', ''),
		'ultima_modificacion' => parseCode('<%%editingDateTime%%>current_timestamp()', false, true),
		'llaves_oficina' => Request::val('llaves_oficina', ''),
		'notas_privadas' => br2nl(Request::val('notas_privadas', '')),
		'observaciones' => br2nl(Request::val('observaciones', '')),
	];

	if($data['inmueble_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Inmueble id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('inmuebles', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: inmuebles_before_update
	if(function_exists('inmuebles_before_update')) {
		$args = ['old_data' => $old_data];
		if(!inmuebles_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'inmuebles',
		backtick_keys_once($set),
		['`inmueble_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="inmuebles_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['inmueble_id'];
	$newID = $data['inmueble_id'];

	update_calc_fields('inmuebles', $data['selectedID'], calculated_fields()['inmuebles']);

	// hook: inmuebles_after_update
	if(function_exists('inmuebles_after_update')) {
		if($row = getRecord('inmuebles', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['inmueble_id'];
		$args = ['old_data' => $old_data];
		if(!inmuebles_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('inmuebles', $selected_id);

	// if PK value changed, update ownership and $selected_id
	if($selected_id != $newID) {
		update('membership_userrecords', ['pkValue' => $newID], ['pkValue' => $selected_id, 'tableName' => 'inmuebles']);
		$selected_id = $newID;
	}
}

function inmuebles_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('inmuebles');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('inmuebles', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('inmuebles', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('inmuebles', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: estado
	$combo_estado = new Combo;
	$combo_estado->ListType = 0;
	$combo_estado->MultipleSeparator = ', ';
	$combo_estado->ListBoxHeight = 10;
	$combo_estado->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/inmuebles.estado.csv')) {
		$estado_data = addslashes(implode('', @file(__DIR__ . '/hooks/inmuebles.estado.csv')));
		$combo_estado->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($estado_data))));
		$combo_estado->ListData = $combo_estado->ListItem;
	} else {
		$combo_estado->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Disponible;;Reservado;;Vendido;;Alquilado;;En construcci&#243;n;;En reforma;;Baja temporal;;Retirado del mercado;;Pendiente de firma;;Bloqueado;;En negociaci&#243;n;;Cancelado;;Inactivo;;Ocupado;;Libre;;Habitable;;Ruina;;Amueblado;;Sin amueblar"))));
		$combo_estado->ListData = $combo_estado->ListItem;
	}
	$combo_estado->SelectName = 'estado';

	if($hasSelectedId) {
		if(!($row = getRecord('inmuebles', $selectedId))) {
			return error_message($Translation['No records found'], 'inmuebles_view.php', false);
		}
		$combo_estado->SelectedData = $row['estado'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_estado->SelectedText = (isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8('Disponible'));
	}
	$combo_estado->Render();

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/inmuebles_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/inmuebles_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#inmueble_id').replaceWith('<div class=\"form-control-static\" id=\"inmueble_id\">' + (\$j('#inmueble_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#referencia').replaceWith('<div class=\"form-control-static\" id=\"referencia\">' + (\$j('#referencia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#propietario_id').replaceWith('<div class=\"form-control-static\" id=\"propietario_id\">' + (\$j('#propietario_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado').replaceWith('<div class=\"form-control-static\" id=\"estado\">' + (\$j('#estado').val() || '') + '</div>'); \$j('#estado-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#tipologia_id').replaceWith('<div class=\"form-control-static\" id=\"tipologia_id\">' + (\$j('#tipologia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#subtipologia_id').replaceWith('<div class=\"form-control-static\" id=\"subtipologia_id\">' + (\$j('#subtipologia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#direccion_id').replaceWith('<div class=\"form-control-static\" id=\"direccion_id\">' + (\$j('#direccion_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#zona_id').replaceWith('<div class=\"form-control-static\" id=\"zona_id\">' + (\$j('#zona_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#dormitorios').replaceWith('<div class=\"form-control-static\" id=\"dormitorios\">' + (\$j('#dormitorios').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#banos').replaceWith('<div class=\"form-control-static\" id=\"banos\">' + (\$j('#banos').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#aseos').replaceWith('<div class=\"form-control-static\" id=\"aseos\">' + (\$j('#aseos').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#m2_utiles').replaceWith('<div class=\"form-control-static\" id=\"m2_utiles\">' + (\$j('#m2_utiles').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#m2_construidos').replaceWith('<div class=\"form-control-static\" id=\"m2_construidos\">' + (\$j('#m2_construidos').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#m2_terraza').replaceWith('<div class=\"form-control-static\" id=\"m2_terraza\">' + (\$j('#m2_terraza').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#altura').replaceWith('<div class=\"form-control-static\" id=\"altura\">' + (\$j('#altura').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#orientacion').replaceWith('<div class=\"form-control-static\" id=\"orientacion\">' + (\$j('#orientacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado_conservacion').replaceWith('<div class=\"form-control-static\" id=\"estado_conservacion\">' + (\$j('#estado_conservacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ano_construccion').replaceWith('<div class=\"form-control-static\" id=\"ano_construccion\">' + (\$j('#ano_construccion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ano_reforma').replaceWith('<div class=\"form-control-static\" id=\"ano_reforma\">' + (\$j('#ano_reforma').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ascensor').replaceWith('<div class=\"form-control-static\" id=\"ascensor\">' + (\$j('#ascensor').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#terraza').replaceWith('<div class=\"form-control-static\" id=\"terraza\">' + (\$j('#terraza').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#balcon').replaceWith('<div class=\"form-control-static\" id=\"balcon\">' + (\$j('#balcon').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#garaje').replaceWith('<div class=\"form-control-static\" id=\"garaje\">' + (\$j('#garaje').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#trastero').replaceWith('<div class=\"form-control-static\" id=\"trastero\">' + (\$j('#trastero').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#calefaccion_tipo').replaceWith('<div class=\"form-control-static\" id=\"calefaccion_tipo\">' + (\$j('#calefaccion_tipo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#climatizacion').replaceWith('<div class=\"form-control-static\" id=\"climatizacion\">' + (\$j('#climatizacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#certificado_energetico').replaceWith('<div class=\"form-control-static\" id=\"certificado_energetico\">' + (\$j('#certificado_energetico').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#consumo_energetico').replaceWith('<div class=\"form-control-static\" id=\"consumo_energetico\">' + (\$j('#consumo_energetico').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#emisiones_co2').replaceWith('<div class=\"form-control-static\" id=\"emisiones_co2\">' + (\$j('#emisiones_co2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#referencia_catastral').replaceWith('<div class=\"form-control-static\" id=\"referencia_catastral\">' + (\$j('#referencia_catastral').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#llaves_oficina').replaceWith('<div class=\"form-control-static\" id=\"llaves_oficina\">' + (\$j('#llaves_oficina').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#notas_privadas').replaceWith('<div class=\"form-control-static\" id=\"notas_privadas\">' + (\$j('#notas_privadas').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#observaciones').replaceWith('<div class=\"form-control-static\" id=\"observaciones\">' + (\$j('#observaciones').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(estado)%%>', $combo_estado->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(estado)%%>', $combo_estado->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(inmueble_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(referencia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(propietario_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipologia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(subtipologia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(direccion_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(zona_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(dormitorios)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(banos)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(aseos)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(m2_utiles)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(m2_construidos)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(m2_terraza)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(altura)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(orientacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado_conservacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ano_construccion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ano_reforma)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ascensor)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(terraza)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(balcon)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(garaje)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(trastero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(calefaccion_tipo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(climatizacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(certificado_energetico)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(consumo_energetico)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(emisiones_co2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(referencia_catastral)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_alta)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ultima_modificacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(llaves_oficina)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(notas_privadas)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(observaciones)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', safe_html($urow['inmueble_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', html_attr($row['inmueble_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode($urow['inmueble_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', safe_html($urow['referencia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', html_attr($row['referencia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode($urow['referencia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(propietario_id)%%>', safe_html($urow['propietario_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(propietario_id)%%>', html_attr($row['propietario_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(propietario_id)%%>', urlencode($urow['propietario_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado)%%>', safe_html($urow['estado']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado)%%>', html_attr($row['estado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado)%%>', urlencode($urow['estado']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipologia_id)%%>', safe_html($urow['tipologia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipologia_id)%%>', html_attr($row['tipologia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipologia_id)%%>', urlencode($urow['tipologia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(subtipologia_id)%%>', safe_html($urow['subtipologia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(subtipologia_id)%%>', html_attr($row['subtipologia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subtipologia_id)%%>', urlencode($urow['subtipologia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(direccion_id)%%>', safe_html($urow['direccion_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(direccion_id)%%>', html_attr($row['direccion_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(direccion_id)%%>', urlencode($urow['direccion_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(zona_id)%%>', safe_html($urow['zona_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(zona_id)%%>', html_attr($row['zona_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(zona_id)%%>', urlencode($urow['zona_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(dormitorios)%%>', safe_html($urow['dormitorios']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(dormitorios)%%>', html_attr($row['dormitorios']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dormitorios)%%>', urlencode($urow['dormitorios']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(banos)%%>', safe_html($urow['banos']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(banos)%%>', html_attr($row['banos']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(banos)%%>', urlencode($urow['banos']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(aseos)%%>', safe_html($urow['aseos']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(aseos)%%>', html_attr($row['aseos']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(aseos)%%>', urlencode($urow['aseos']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(m2_utiles)%%>', safe_html($urow['m2_utiles']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(m2_utiles)%%>', html_attr($row['m2_utiles']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(m2_utiles)%%>', urlencode($urow['m2_utiles']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(m2_construidos)%%>', safe_html($urow['m2_construidos']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(m2_construidos)%%>', html_attr($row['m2_construidos']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(m2_construidos)%%>', urlencode($urow['m2_construidos']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(m2_terraza)%%>', safe_html($urow['m2_terraza']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(m2_terraza)%%>', html_attr($row['m2_terraza']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(m2_terraza)%%>', urlencode($urow['m2_terraza']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(altura)%%>', safe_html($urow['altura']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(altura)%%>', html_attr($row['altura']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(altura)%%>', urlencode($urow['altura']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(orientacion)%%>', safe_html($urow['orientacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(orientacion)%%>', html_attr($row['orientacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(orientacion)%%>', urlencode($urow['orientacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado_conservacion)%%>', safe_html($urow['estado_conservacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado_conservacion)%%>', html_attr($row['estado_conservacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_conservacion)%%>', urlencode($urow['estado_conservacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ano_construccion)%%>', safe_html($urow['ano_construccion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ano_construccion)%%>', html_attr($row['ano_construccion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ano_construccion)%%>', urlencode($urow['ano_construccion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ano_reforma)%%>', safe_html($urow['ano_reforma']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ano_reforma)%%>', html_attr($row['ano_reforma']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ano_reforma)%%>', urlencode($urow['ano_reforma']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ascensor)%%>', safe_html($urow['ascensor']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ascensor)%%>', html_attr($row['ascensor']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ascensor)%%>', urlencode($urow['ascensor']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(terraza)%%>', safe_html($urow['terraza']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(terraza)%%>', html_attr($row['terraza']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(terraza)%%>', urlencode($urow['terraza']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(balcon)%%>', safe_html($urow['balcon']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(balcon)%%>', html_attr($row['balcon']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balcon)%%>', urlencode($urow['balcon']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(garaje)%%>', safe_html($urow['garaje']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(garaje)%%>', html_attr($row['garaje']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(garaje)%%>', urlencode($urow['garaje']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(trastero)%%>', safe_html($urow['trastero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(trastero)%%>', html_attr($row['trastero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(trastero)%%>', urlencode($urow['trastero']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(calefaccion_tipo)%%>', safe_html($urow['calefaccion_tipo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(calefaccion_tipo)%%>', html_attr($row['calefaccion_tipo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calefaccion_tipo)%%>', urlencode($urow['calefaccion_tipo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(climatizacion)%%>', safe_html($urow['climatizacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(climatizacion)%%>', html_attr($row['climatizacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(climatizacion)%%>', urlencode($urow['climatizacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(certificado_energetico)%%>', safe_html($urow['certificado_energetico']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(certificado_energetico)%%>', html_attr($row['certificado_energetico']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(certificado_energetico)%%>', urlencode($urow['certificado_energetico']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(consumo_energetico)%%>', safe_html($urow['consumo_energetico']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(consumo_energetico)%%>', html_attr($row['consumo_energetico']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(consumo_energetico)%%>', urlencode($urow['consumo_energetico']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(emisiones_co2)%%>', safe_html($urow['emisiones_co2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(emisiones_co2)%%>', html_attr($row['emisiones_co2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(emisiones_co2)%%>', urlencode($urow['emisiones_co2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(referencia_catastral)%%>', safe_html($urow['referencia_catastral']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(referencia_catastral)%%>', html_attr($row['referencia_catastral']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia_catastral)%%>', urlencode($urow['referencia_catastral']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_alta)%%>', app_datetime($row['fecha_alta'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_alta)%%>', urlencode(app_datetime($urow['fecha_alta'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(ultima_modificacion)%%>', app_datetime($row['ultima_modificacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ultima_modificacion)%%>', urlencode(app_datetime($urow['ultima_modificacion'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(llaves_oficina)%%>', safe_html($urow['llaves_oficina']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(llaves_oficina)%%>', html_attr($row['llaves_oficina']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(llaves_oficina)%%>', urlencode($urow['llaves_oficina']), $templateCode);
		$templateCode = str_replace('<%%VALUE(notas_privadas)%%>', safe_html($urow['notas_privadas'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(notas_privadas)%%>', urlencode($urow['notas_privadas']), $templateCode);
		$templateCode = str_replace('<%%VALUE(observaciones)%%>', safe_html($urow['observaciones'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(observaciones)%%>', urlencode($urow['observaciones']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(inmueble_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(referencia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(propietario_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(propietario_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado)%%>', 'Disponible', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado)%%>', urlencode('Disponible'), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipologia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipologia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(subtipologia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subtipologia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(direccion_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(direccion_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(zona_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(zona_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(dormitorios)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dormitorios)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(banos)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(banos)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(aseos)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(aseos)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(m2_utiles)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(m2_utiles)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(m2_construidos)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(m2_construidos)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(m2_terraza)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(m2_terraza)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(altura)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(altura)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(orientacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(orientacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado_conservacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_conservacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ano_construccion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ano_construccion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ano_reforma)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ano_reforma)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ascensor)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ascensor)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(terraza)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(terraza)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(balcon)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balcon)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(garaje)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(garaje)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(trastero)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(trastero)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(calefaccion_tipo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calefaccion_tipo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(climatizacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(climatizacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(certificado_energetico)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(certificado_energetico)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(consumo_energetico)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(consumo_energetico)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(emisiones_co2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(emisiones_co2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(referencia_catastral)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia_catastral)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_alta)%%>', '<%%creationDateTime%%>curdate()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_alta)%%>', urlencode('<%%creationDateTime%%>curdate()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(ultima_modificacion)%%>', '<%%editingDateTime%%>current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ultima_modificacion)%%>', urlencode('<%%editingDateTime%%>current_timestamp()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(llaves_oficina)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(llaves_oficina)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(notas_privadas)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(notas_privadas)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(observaciones)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(observaciones)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('inmuebles');
	if($hasSelectedId) {
		$jdata = get_joined_record('inmuebles', $selectedId);
		if($jdata === false) $jdata = get_defaults('inmuebles');
		$rdata = $row;
	}
	$templateCode .= loadView('inmuebles-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: inmuebles_dv
	if(function_exists('inmuebles_dv')) {
		$args = [];
		inmuebles_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}