<?php

/*

Si deseas traducir tu aplicación AppGini, ¡este es
el archivo correcto para modificar! Sin embargo, por favor revisa esta página
primero ya que podrías encontrar una traducción existente
que puedas actualizar en lugar de comenzar desde cero:

https://bigprof.com/appgini/download-language-files

IMPORTANTE:
==========
Al traducir, solo traduce las cadenas que están
A LA DERECHA de la flecha (=>).

NO traduzcas las cadenas entre corchetes ([])
Tampoco modifiques el texto entre < y >.
Además, deja la cadena especial %s tal cual, sin traducir.

=====================================================
NOTA IMPORTANTE:
============
Cuando se lanza una nueva versión de AppGini, se pueden agregar
nuevas cadenas al archivo "defaultLang.php". Para traducirlas,
simplemente cópialas a este archivo ("language.php") y
tradúcelas aquí. NO las traduzcas directamente en
el archivo "defaultLang.php".
=====================================================

Para evitar mensajes de error, asegúrate de:

1. Agregar una coma al final de cada línea si aún no está.
2. Dejar la última línea de este archivo así:
];

*/

$Translation = [
	'language' => 'español',
	'membership management' => 'Gestión de Membresía',
	'password mismatch' => 'La contraseña no coincide.',
	'error' => 'Error',
	'invalid email' => 'Dirección de correo electrónico inválida',
	'sending mails' => "El envío de correos puede tomar algún tiempo. Por favor no cierre esta página hasta ver el mensaje 'Finalizado'.",
	'complete step 4' => 'Complete el paso 4 seleccionando el miembro al que desea transferir los registros.',
	'info' => 'Información',
	'sure move member' => "¿Está seguro que desea mover al miembro '<MEMBER>' y sus datos del grupo '<OLDGROUP>' al grupo '<NEWGROUP>'?",
	'sure move data of member' => "¿Está seguro que desea mover los datos del miembro '<OLDMEMBER>' del grupo '<OLDGROUP>' al miembro '<NEWMEMBER>' del grupo '<NEWGROUP>'?",
	'sure move all members' => "¿Está seguro que desea mover todos los miembros y datos del grupo '<OLDGROUP>' al grupo '<NEWGROUP>'?",
	'sure move data of all members' => "¿Está seguro que desea mover los datos de todos los miembros del grupo '<OLDGROUP>' al miembro '<MEMBER>' del grupo '<NEWGROUP>'?",
	'toggle navigation' => 'Alternar navegación',
	'admin area' => 'Área de Administración',
	'groups' => 'Grupos',
	'view groups' => 'Ver Grupos',
	'add group' => 'Agregar Grupo',
	'edit anonymous permissions' => 'Editar Permisos Anónimos',
	'members' => 'Miembros',
	'view members' => 'Ver Miembros',
	'add member' => 'Agregar Miembro',
	"view members' records" => "Ver Registros de Miembros",
	'utilities' => 'Utilidades',
	'admin settings' => 'Configuración de Administrador',
	'rebuild thumbnails' => 'Reconstruir miniaturas',
	'rebuild fields' => 'Puedes intentar solucionar este problema desde el Área de Administración: Menú Utilidades: Ver/Reconstruir Campos.',
	'import CSV' => 'Importar datos CSV',
	'batch transfer' => 'Asistente de Transferencia Masiva',
	'mail all users' => 'Enviar Correo a Todos los Usuarios',
	'AppGini forum' => 'Foro de la Comunidad AppGini',
	"user's area" => "Área de Usuario",
	'sign out' => 'Cerrar Sesión',
	'attention' => '¡Atención!',
	'security risk admin' => 'Estás usando el nombre de usuario y contraseña predeterminados del admin. Esto es un gran riesgo de seguridad. Por favor cambia al menos la contraseña del admin desde la página de <a href="pageSettings.php">Configuración de Administrador</a> <em>inmediatamente</em>.',
	'security risk' => 'Estás usando la contraseña predeterminada del admin. Esto es un gran riesgo de seguridad. Por favor cambia la contraseña del admin desde la página de <a href="pageSettings.php">Configuración de Administrador</a> <em>inmediatamente</em>.',
	'plugins' => 'Plugins',
	'assigned table records to group' => "Asignados <NUMBER> registros de la tabla '<TABLE>' al grupo '<GROUP>'",
	'assigned table records to group and member' => "Asignados <NUMBER> registros de la tabla '<TABLE>' al grupo '<GROUP>', miembro '<MEMBERID>'",
	'data ownership assign' => 'Asignar dueño a datos sin propietario',
	'records ownership done' => "Todos los registros en todas las tablas ahora tienen dueños.<br>Volver a <a href='pageHome.php'>página principal de administración</a>.",
	'select group' => 'Seleccionar grupo',
	'data ownership' => 'En ocasiones, puedes tener tablas con datos ingresados antes de implementar este sistema de membresía de AppGini, o ingresados usando otras aplicaciones que no manejan el sistema de propiedad de AppGini. Estos datos actualmente no tienen dueños. Esta página te permite asignar grupos y miembros dueños a estos datos.',
	'table' => 'Tabla',
	'records with no owners' => 'Registros sin dueños',
	'new owner group' => 'Nuevo grupo dueño',
	'new owner member' => 'Nuevo miembro dueño*',
	'cancel' => 'Cancelar',
	'assign new owners' => 'Asignar nuevos dueños',
	'please wait' => 'Por favor espere',
	'if no owner member assigned' => '* Si no asignas un miembro dueño aquí, aún puedes usar el <a href="pageTransferOwnership.php">Asistente de Transferencia Masiva</a> más tarde para hacerlo.',
	'can not delete group remove members' => "No se puede eliminar este grupo. Por favor elimina los miembros primero.",
	'can not delete group transfer records' => "No se puede eliminar este grupo. Por favor transfiere sus registros de datos a otro grupo primero.",
	'group exists error' => 'Error: El nombre del grupo ya existe. Debes elegir un nombre único.',
	'group not found error' => 'Error: ¡Grupo no encontrado!',
	'edit group' => "Editar Grupo '<GROUPNAME>'",
	'add new group' => 'Agregar Nuevo Grupo',
	'anonymous group attention' => '¡Atención! Este es el grupo anónimo.',
	'show tool tips' => 'Mostrar consejos al pasar el mouse sobre opciones',
	'group name' => 'Nombre del grupo',
	'readonly group name' => 'El nombre del grupo anónimo es de solo lectura aquí.',
	'anonymous group name' => "Si nombras al grupo '<ANONYMOUSGROUP>', será considerado el grupo anónimo<br>que define los permisos de visitantes invitados que no inician sesión.",
	'description' => 'Descripción',
	'allow visitors sign up' => '¿Permitir que los visitantes se registren?',
	'admin add users' => 'No. Solo el admin puede agregar usuarios.',
	'admin approve users' => 'Sí, y el admin debe aprobarlos.',
	'automatically approve users' => 'Sí, y aprobarlos automáticamente.',
	'group table permissions' => 'Permisos de tabla para este grupo',
	'no' => 'No',
	'owner' => 'Dueño',
	'group' => 'Grupo',
	'all' => 'Todos',
	'insert' => 'Insertar',
	'view' => 'Ver',
	'edit' => 'Editar',
	'delete' => 'Eliminar',
	'save changes' => 'Guardar cambios',
	'username error' => 'Error: El nombre de usuario ya existe o es inválido. Asegúrate de proveer un nombre con 4 a 20 caracteres válidos.',
	'member not found' => 'Error: ¡Miembro no encontrado!',
	'user has special permissions' => 'Este usuario tiene permisos especiales que sobreescriben los de su grupo.',
	'user has group permissions' => 'Este usuario hereda los <a href="pageEditGroup.php?groupID=<GROUPID>">permisos de su grupo</a>.',
	'set user special permissions' => 'Establecer permisos especiales para este usuario',
	'sure continue' => 'Si realizaste cambios en este miembro y no los guardaste, se perderán si continúas. ¿Estás seguro de continuar?',
	'edit member' => 'Editar Miembro <MEMBERID>',
	'add new member' => 'Agregar Nuevo Miembro',
	'anonymous guest member' => '¡Atención! Este es el miembro anónimo (invitado).',
	'admin member' => '¡Atención! Este es el miembro admin. No puedes cambiar el nombre de usuario, contraseña o email aquí, pero puedes hacerlo en la página de <a href="pageSettings.php">configuración del admin</a>.',
	'member username' => 'Nombre de usuario del miembro',
	'check availability' => 'Verificar disponibilidad de este nombre',
	'read only username' => 'El nombre de usuario del invitado es de solo lectura.',
	'password' => 'Contraseña',
	'change password' => "Escribe una contraseña solo si deseas cambiar la contraseña<br>de este miembro. De lo contrario, deja este campo vacío.",
	'confirm password' => 'Confirmar Contraseña',
	'email' => 'Dirección de Correo',
	'approved' => '¿Aprobado?',
	'banned' => '¿Bloqueado?',
	'comments' => 'Comentarios',
	'back to members' => 'Volver a miembros',
	'member added' => 'Miembro <USERNAME> agregado exitosamente',
	'member permissions saved' => 'Permisos del miembro guardados exitosamente.',
	'member permissions reset' => 'Los permisos del miembro se han restablecido a los de su grupo.',
	'user table permissions' => "Permisos de tabla para el usuario <a href='pageEditMember.php?memberID=<MEMBER>' title='Ver detalles del miembro'><MEMBERID></a> del grupo <a href='pageEditGroup.php?groupID=<GROUPID>' title='Ver detalles y permisos del grupo'><GROUP></a>",
	'no member permissions' => "Este miembro no tiene permisos especiales actualmente. Esta lista muestra los permisos de su grupo.",
	'reset member permissions' => 'Restablecer permisos del miembro',
	'remove special permissions' => 'Esto eliminará todos los permisos especiales de este usuario y heredará los de su grupo. ¿Estás seguro?',
	'invalid table' => 'Tabla inválida.',
	'invalid primary key' => 'Valor de clave primaria inválido',
	'record not found' => 'Registro no encontrado... Si fue importado externamente, intenta asignar un dueño desde el área de admin.',
	'invalid username' => 'Nombre de usuario inválido',
	'record not found error' => 'Error: ¡Registro no encontrado!',
	'edit Record Ownership' => 'Editar Propiedad del Registro',
	'owner group' => 'Grupo dueño',
	'view all records by group' => 'Ver todos los registros de este grupo',
	'owner member' => 'Miembro dueño',
	'view all records by member' => 'Ver todos los registros de este miembro',
	'switch record ownership' => 'Si deseas cambiar la propiedad de este registro a un miembro de otro grupo, primero debes cambiar el grupo dueño y guardar los cambios.',
	'record created on' => 'Registro creado el',
	'record modified on' => 'Registro modificado el',
	'view all records of table' => 'Ver todos los registros de esta tabla',
	'record data' => 'Datos del registro',
	'print' => 'Imprimir',
	'could not retrieve field list' => "No se pudo obtener la lista de campos de '<TABLENAME>'",
	'field name' => 'Nombre del campo',
	'value' => 'Valor',
	'visitor sign up' => '<a href="../membership_signup.php" target="_blank">El registro de visitantes</a> está deshabilitado porque actualmente no hay grupos que permitan registrarse. Para habilitarlo, configura al menos un grupo para permitir registro.',
	'table data without owner' => 'Tienes datos en una o más tablas que no tienen dueño. Para asignar un grupo dueño, <a href="pageAssignOwners.php">haz clic aquí</a>.',
	'membership management homepage' => 'Página Principal de Gestión de Membresía',
	'newest updates' => 'Actualizaciones Recientes',
	'view record details' => 'Ver detalles del registro',
	'newest entries' => 'Entradas Recientes',
	'available add-ons' => 'Complementos Disponibles',
	'more info' => 'Más información',
	'close' => 'Cerrar',
	'view add-ons' => 'Ver todos los complementos',
	'top members' => 'Miembros Destacados',
	'edit member details' => 'Editar detalles del miembro',
	'view member records' => "Ver registros de datos del miembro",
	'records' => 'registros',
	'members stats' => 'Estadísticas de Miembros',
	'total groups' => 'Total de grupos',
	'active members' => 'Miembros activos',
	'view active members' => 'Ver miembros activos',
	'members awaiting approval' => 'Miembros pendientes de aprobación',
	'view members awaiting approval' => 'Ver miembros pendientes de aprobación',
	'banned members' => 'Miembros bloqueados',
	'view banned members' => 'Ver miembros bloqueados',
	'total members' => 'Total de miembros',
	'view all members' => 'Ver todos los miembros',
	'BigProf tweets' => 'Tweets de BigProf Software',
	'follow BigProf' => 'Seguir a @bigprof',
	'loading bigprof feed' => 'Cargando feed de @bigprof ...',
	'remove feed' => 'Eliminar este feed',
	'can not send mail' => "No puedes enviar correos actualmente. La dirección de correo del remitente no es válida. Por favor <a href='pageSettings.php'>corrígela</a> e intenta de nuevo.",
	'all groups' => 'Todos los grupos',
	'no recipient' => "No se encontró el destinatario. Asegúrate de proveer uno válido.",
	'invalid subject line' => 'Línea de asunto inválida.',
	'no recipient found' => "No se encontraron destinatarios. Asegúrate de proveer uno válido.",
	'mail queue not saved' => "No se pudo guardar la cola de correos. Asegúrate que el directorio '<CURRDIR>' tenga permisos de escritura (chmod 755 o 777).",
	'send mail' => 'Enviar correo a un miembro/grupo',
	'send mail to all members' => "Estás enviando un correo a todos los miembros. Esto puede tomar tiempo y afectar el rendimiento del servidor. Si tienes muchos miembros, no recomendamos enviar correos a todos a la vez.",
	'from' => 'De',
	'change setting' => 'Cambiar esta configuración',
	'to' => 'Para',
	'subject' => 'Asunto',
	'message' => 'Mensaje',
	'send message' => 'Enviar Mensaje',
	'record details' => 'Gestión de Membresía - Detalles del Registro',
	'table name' => 'Tabla: <TABLENAME>',
	'create or update table' => 'Se intentó <ACTION> el campo <i><FIELD></i> en la tabla <i><TABLE></i> ejecutando la consulta: <pre><QUERY></pre> Resultados abajo.',
	'view or rebuild fields' => 'Ver/Reconstruir campos',
	'show deviations only' => 'Mostrar solo desviaciones',
	'show all fields' => 'Mostrar todos los campos',
	'compare tables page' => 'Esta página compara la estructura de tablas y campos diseñada en AppGini con la base de datos actual, permitiendo corregir desviaciones.',
	'field' => 'Campo',
	'AppGini definition' => 'Definición en AppGini',
	'database definition' => 'Definición actual en la base de datos',
	'table name title' => 'Tabla <TABLENAME>',
	'does not exist' => "¡No existe!",
	'create field' => 'Crear el campo ejecutando una consulta ADD COLUMN.',
	'create it' => 'Crearlo',
	'fix field' => 'Corregir el campo ejecutando ALTER COLUMN para igualar la definición de AppGini.',
	'fix it' => 'Corregirlo',
	'field update warning' => '¡PELIGRO! En algunos casos, esto puede causar pérdida o corrupción de datos. A veces es mejor actualizar el campo en AppGini para que coincida con la base de datos. ¿Continuar?',
	'no deviations found' => 'No se encontraron desviaciones. ¡Todos los campos están bien!',
	'error fields' => 'Se encontraron <CREATENUM> campos inexistentes por crear.<br>Se encontraron <UPDATENUM> campos desviados que necesitan actualización.',
	'thumbnails utility' => "Usa esta utilidad si tienes campos de imagen sin miniaturas o con dimensiones incorrectas.",
	'rebuild thumbnails of table' => 'Reconstruir miniaturas de la tabla',
	'rebuild' => 'Reconstruir',
	'rebuild thumbnails of table_name' => "Reconstruyendo miniaturas de la tabla '<i><TABLENAME></i>' ...",
	'do not close page message' => "No cierres esta página hasta ver el mensaje de confirmación de que todas las miniaturas se han construido.",
	'rebuild thumbnails status' => 'Estado: reconstruyendo miniaturas, por favor espera ...',
	'building field thumbnails' => "Construyendo miniaturas para el campo '<i><FIELD></i>'...",
	'done' => 'Listo.',
	'finished status' => 'Estado: finalizado. Puedes cerrar esta página ahora.',
	'invalid mail queue' => 'Cola de correo inválida.',
	'sending message failed' => " -- Falló enviar mensaje a '<EMAIL>'.",
	'sending message ok' => " -- Mensaje enviado a '<EMAIL>': Correcto.",
	'done!' => '¡Listo!',
	'close page' => 'Puedes cerrar esta página o navegar a otra.',
	'mail log' => 'Registro de correos:',
	'invalid security token' => '¡Token de seguridad inválido! Por favor <a href="pageSettings.php">recarga la página</a> e intenta de nuevo.',
	'unique admin username error' => 'El nuevo nombre de usuario del admin ya existe. Asegúrate que sea único.',
	'unique anonymous username error' => 'El nuevo nombre de usuario anónimo ya existe. Asegúrate que sea único.',
	'unique anonymous group name error' => 'El nuevo nombre de grupo anónimo ya existe. Asegúrate que sea único.',
	'admin password mismatch' => 'La "Contraseña de admin" y "Confirmar contraseña" no coinciden.',
	'invalid sender email' => 'Correo del remitente inválido.',
	'errors occurred' => 'Ocurrieron los siguientes errores:',
	'go back' => 'Por favor <a href="pageSettings.php" onclick="history.go(-1); return false;">regresa</a> para corregir los errores e intenta de nuevo.',
	'record updated automatically' => 'Registro actualizado automáticamente el <DATE>',
	'admin settings saved' => 'Configuración del admin guardada.<br>Volver a <a href="pageSettings.php">Configuración de admin</a>.',
	'admin settings not saved' => 'La configuración del admin NO se guardó. Razón: <ERROR><br>Volver a <a href="pageSettings.php" onclick="history.go(-1); return false;">Configuración de admin</a>.',
	'admin username' => 'Nombre de usuario del admin',
	'admin password' => 'Contraseña del admin',
	'change admin password' => 'Escribe una contraseña solo si deseas cambiar la del admin.',
	'sender email' => 'Correo del remitente',
	'sender name and email' => "Nombre y correo del remitente usados en el campo 'De' al enviar",
	'email messages' => 'correos a grupos o miembros.',
	'admin notifications' => 'Notificaciones al admin',
	'no email notifications' => 'Sin notificaciones por correo al admin.',
	'member waiting approval' => 'Notificar al admin solo cuando un nuevo miembro espera aprobación.',
	'new sign-ups' => 'Notificar al admin por todos los nuevos registros.',
	'sender name' => 'Nombre del remitente',
	'members custom field 1' => 'Campo personalizado 1 de miembros',
	'members custom field 2' => 'Campo personalizado 2 de miembros',
	'members custom field 3' => 'Campo personalizado 3 de miembros',
	'members custom field 4' => 'Campo personalizado 4 de miembros',
	'member approval email subject' => 'Asunto del correo de aprobación de miembro',
	'member approval email subject control' => 'Cuando el admin aprueba un miembro, se le notifica por correo. Puedes controlar el asunto aquí y el contenido abajo.',
	'member approval email message' => 'Mensaje del correo de aprobación de miembro',
	'MySQL date' => 'Cadena de formato de fecha MySQL',
	'MySQL reference' => 'Consulta <a href="https://dev.mysql.com/doc/refman/5.0/en/date-and-time-functions.html#function_date-format" target="_blank">la referencia de MySQL</a> para formatos posibles.',
	'PHP short date' => 'Cadena de formato de fecha corta PHP',
	'PHP manual' => 'Consulta <a href="https://www.php.net/manual/en/function.date.php" target="_blank">el manual de PHP</a> para formatos posibles.',
	'PHP long date' => 'Cadena de formato de fecha larga PHP',
	'groups per page' => 'Grupos por página',
	'members per page' => 'Miembros por página',
	'records per page' => 'Registros por página',
	'default sign-up mode' => 'Modo de registro predeterminado para nuevos grupos',
	'no sign-up allowed' => 'Registro no permitido. Solo el admin puede agregar miembros.',
	'admin approve members' => 'Registro permitido, pero el admin debe aprobar miembros.',
	'automatically approve members' => 'Registro permitido y aprobación automática.',
	'anonymous group' => 'Nombre del grupo anónimo',
	'anonymous user name' => 'Nombre del usuario anónimo',
	'hide twitter feed' => '¿Ocultar el feed de Twitter en la página de admin?',
	'twitter feed' => 'Nuestro feed de Twitter te mantiene informado de noticias, recursos, lanzamientos y consejos útiles.',
	'invalid source member' => 'Miembro de origen inválido.',
	'invalid destination member' => 'Miembro de destino inválido.',
	'moving member' => "Moviendo miembro '<MEMBERID>' y sus datos del grupo '<SOURCEGROUP>' al grupo '<DESTINATIONGROUP>' ...",
	'data records transferred' => "El miembro '<MEMBERID>' ahora pertenece al grupo '<NEWGROUP>'. Registros transferidos: <DATARECORDS>.",
	'moving data' => "Moviendo datos del miembro '<SOURCEMEMBER>' del grupo '<SOURCEGROUP>' al miembro '<DESTINATIONMEMBER>' del grupo '<DESTINATIONGROUP>' ...",
	'member records status' => "El miembro '<SOURCEMEMBER>' del grupo '<SOURCEGROUP>' tenía <DATABEFORE> registros. <TRANSFERSTATUS> al miembro '<DESTINATIONMEMBER>' del grupo '<DESTINATIONGROUP>'.",
	'moving all group members' => "Moviendo todos los miembros y datos del grupo '<SOURCEGROUP>' al grupo '<DESTINATIONGROUP>' ...",
	'failed transferring group members' => "Error. No se transfirieron miembros del grupo '<SOURCEGROUP>' a '<DESTINATIONGROUP>'.",
	'group members transferred' => "Todos los miembros de '<SOURCEGROUP>' ahora pertenecen a '<DESTINATIONGROUP>'. ",
	'failed transfer data records' => 'Sin embargo, falló la transferencia de registros.',
	'data records were transferred' => 'Se transfirieron <DATABEFORE> registros.',
	'moving group data to member' => "Moviendo datos de todos los miembros del grupo '<SOURCEGROUP>' al miembro '<DESTINATIONMEMBER>' del grupo '<DESTINATIONGROUP>' ...",
	'moving group data to member status' => "<NUMBER> registro(s) transferidos del grupo '<SOURCEGROUP>' al miembro '<DESTINATIONMEMBER>' del grupo '<DESTINATIONGROUP>'",
	'status' => 'ESTADO:',
	'batch transfer link' => 'Para repetir esta transferencia, puedes <a href= "pageTransferOwnership.php?sourceGroupID=<SOURCEGROUP>&amp;sourceMemberID=<SOURCEMEMBER>&amp;destinationGroupID=<DESTINATIONGROUP>&amp;destinationMemberID=<DESTINATIONMEMBER>&amp;moveMembers=<MOVEMEMBERS>">guardar o copiar este enlace</a>.',
	'ownership batch transfer' => 'Transferencia Masiva de Propiedad',
	'step 1' => 'PASO 1:',
	'batch transfer wizard' => 'Este asistente permite transferir registros de uno o todos los miembros de un grupo (grupo origen) a un miembro de otro grupo (miembro destino).',
	'source group' => 'Grupo origen',
	'update' => 'Actualizar',
	'next step' => 'Siguiente Paso',
	'group statistics' => 'Este grupo tiene <MEMBERS> miembros y <RECORDS> registros.',
	'step 2' => 'PASO 2:',
	'source member message' => 'El miembro origen puede ser uno o todos los miembros del grupo origen.',
	'source member' => 'Miembro origen',
	'all group members' => "Todos los miembros de '<GROUPNAME>'",
	'member statistics' => 'Este miembro tiene <RECORDS> registros.',
	'step 3' => 'PASO 3:',
	'destination group message' => 'El grupo destino puede ser igual o diferente al origen. Solo se listan grupos con miembros.',
	'destination group' => 'Grupo destino',
	'step 4' => 'PASO 4:',
	'destination member message' => 'El miembro destino será el nuevo dueño de los registros del miembro origen.',
	'destination member' => 'Miembro destino',
	'begin transfer' => 'Comenzar Transferencia',
	'move records' => 'Puedes mover registros del miembro origen a un miembro del grupo destino, o mover los miembros origen con sus datos al grupo destino.',
	'move data records to member' => 'Mover registros a este miembro:',
	'move source member to group' => "Mover miembro(s) origen y sus datos al grupo '<GROUPNAME>'.",
	'file not found error' => "Error: Archivo '<FILENAME>' no encontrado.",
	'preview and confirm CSV data' => 'Previsualizar y confirmar datos CSV',
	'display csv file rows' => 'Mostrando las primeras 10 filas del archivo CSV ...',
	'change CSV settings' => 'Cambiar configuración CSV',
	'import CSV data' => 'Confirmar e importar datos CSV &gt;',
	'apply CSV settings' => 'Aplicar Configuración CSV',
	'importing CSV data' => 'Importando datos CSV ...',
	'start at estimated record' => 'Iniciando en registro <RECORDNUMBER> de <RECORDS> estimados ...',
	'table backed up' => "Tabla '<TABLE>' respaldada como '<TABLENAME>'.",
	'table backup not done' => "La tabla '<TABLE>' está vacía, no se hizo respaldo.",
	'importing batch' => 'Importando lote <BATCH> de <BATCHNUM>: ',
	'ok' => 'Ok',
	'records inserted or updated successfully' => '<RECORDS> registros insertados/actualizados en <SECONDS> segundos.',
	'mission accomplished' => '¡Misión cumplida!',
	'assign a records owner' => 'Asignar dueño a los registros importados &gt;',
	'please wait and do not close' => "Por favor espera y no cierres esta página ...",
	'hide advanced options' => 'Ocultar opciones avanzadas',
	'show advanced options' => 'Mostrar opciones avanzadas',
	'import CSV to database' => 'Importar archivo CSV a la base de datos',
	'import CSV to database page' => 'Esta página permite subir un archivo CSV (ej. generado desde Excel) e importarlo a una tabla de la base de datos.',
	'populate table from CSV' => 'Esta es la tabla que deseas poblar con datos del CSV.',
	'CSV file' => 'Archivo CSV',
	'preview CSV data' => 'Previsualizar datos CSV &gt;',
	'no table name provided' => 'No se proporcionó nombre de tabla.',
	'can not open CSV' => "No se pudo abrir el archivo CSV '<FILENAME>'.",
	'empty CSV file' => "El archivo CSV '<FILENAME>' está vacío.",
	'no CSV file data' => "El archivo CSV '<FILENAME>' no tiene datos.",
	'field separator' => 'Separador de campos',
	'default comma' => 'Por defecto es coma (,)',
	'field delimiter' => 'Delimitador de campos',
	'default double-quote' => 'Por defecto es comillas dobles (")',
	'maximum characters per line' => 'Máximo de caracteres por línea',
	'trouble importing CSV' => 'Si tienes problemas importando, intenta aumentar este valor.',
	'ignore lines number' => 'Número de líneas a ignorar',
	'skip lines number' => 'Cambia este valor para saltar líneas al inicio del CSV.',
	'first line field names' => 'La primera línea contiene nombres de campos',
	'field names must match' => 'Los nombres DEBEN coincidir exactamente con los de la base de datos.',
	'update table records' => 'Actualizar registros existentes (usando clave primaria).',
	'ignore CSV table records' => 'Si no se marca, los registros del CSV con claves existentes serán ignorados.',
	'back up the table' => 'Respaldar la tabla antes de importar.',
	'no matching results found' => 'No se encontraron resultados.',
	'search groups' => 'Buscar grupos',
	'find' => 'Buscar',
	'reset' => 'Reiniciar',
	'members count' => 'Cantidad de miembros',
	'Edit group' => 'Editar grupo',
	'confirm delete group' => '¿Estás seguro de eliminar este grupo?',
	'delete group' => 'Eliminar grupo',
	'view group records' => 'Ver registros del grupo',
	'view group members' => 'Ver miembros del grupo',
	'send message to group' => 'Enviar mensaje al grupo',
	'previous' => 'Anterior',
	'displaying groups' => 'Mostrando grupos <GROUPNUM1> a <GROUPNUM2> de <GROUPS>',
	'next' => 'Siguiente',
	'key' => 'Clave:',
	'edit group details' => 'Editar detalles y permisos del grupo.',
	'add member to group' => 'Agregar nuevo miembro al grupo.',
	'view data records' => "Ver todos los registros ingresados por el grupo.",
	'list group members' => 'Listar todos los miembros del grupo.',
	'send email to all members' => 'Enviar correo a todos los miembros del grupo.',
	'search members' => 'Buscar miembros <SEARCH> en <HTMLSELECT>',
	'all fields' => 'Todos los campos',
	'any' => 'Cualquiera',
	'waiting approval' => 'Pendiente de aprobación',
	'active' => 'Activo',
	'Banned' => 'Bloqueado',
	'username' => 'Nombre de usuario',
	'sign up date' => 'Fecha de registro',
	'Status' => 'Estado',
	'Edit member' => 'Editar miembro',
	'sure delete user' => "¿Estás seguro de eliminar al usuario '<USERNAME>'?",
	'delete member' => 'Eliminar miembro',
	'approve this member' => 'Aprobar este miembro',
	'unban this member' => 'Desbloquear este miembro',
	'ban this member' => 'Bloquear este miembro',
	'View member records' => "Ver registros del miembro",
	'send message to member' => 'Enviar mensaje al miembro',
	'displaying members' => 'Mostrando miembros <MEMBERNUM1> a <MEMBERNUM2> de <MEMBERS>',
	'activate member' => 'Activar nuevo miembro/bloqueado.',
	'ban member' => 'Bloquear (suspender) miembro.',
	'view entered member records' => 'Ver todos los registros ingresados por el miembro.',
	'send email to member' => 'Enviar correo al miembro.',
	'data records' => 'Registros de Datos',
	'show records' => 'Mostrar registros de',
	'all tables' => 'Todas las tablas',
	'sort records' => 'Ordenar registros por',
	'date created' => 'Fecha de creación',
	'date modified' => 'Fecha de modificación',
	'newer first' => 'Más nuevos primero',
	'older first' => 'Más antiguos primero',
	'created' => 'Creado',
	'modified' => 'Modificado',
	'data' => 'Datos',
	'change record ownership' => 'Cambiar dueño de este registro',
	'sure delete record' => '¿Estás seguro de eliminar este registro?',
	'delete record' => 'Eliminar registro',
	'displaying records' => 'Mostrando registros <RECORDNUM1> a <RECORDNUM2> de <RECORDS>',
	'maintenance mode admin notification' => '¡El modo mantenimiento está activado! Puedes desactivarlo desde la página principal del admin.',
	'maintenance mode message' => 'Mensaje de modo mantenimiento',
	'maintenance mode' => 'Modo Mantenimiento',
	'OFF' => 'APAGADO',
	'ON' => 'ENCENDIDO',
	'enable maintenance mode?' => '¿Activar modo mantenimiento? Solo los admins podrán acceder.',
	'disable maintenance mode?' => '¿Desactivar modo mantenimiento? Todos los usuarios podrán acceder.',
	'csv file upload error' => 'Error procesando el archivo CSV.',
	'back and retry' => 'Regresar e intentar de nuevo',
	'upload or choose csv file' => 'Subir un archivo CSV o abrir uno existente',
	'choose csv upload' => 'Seleccionar archivo CSV para subir',
	'no file chosen yet' => 'Aún no se ha seleccionado archivo',
	'start upload' => 'Iniciar subida',
	'select a table' => 'Seleccionar una tabla',
	'error reading csv data' => 'Error leyendo datos CSV. Verifica la configuración.',
	'belongs to' => 'Pertenece a',
	'skip column' => 'Saltar esta columna',
	'connection failed retrying' => 'Conexión fallida. Reintentando en <SECONDS> segundos ...',
	'connection failed timeout' => 'Tiempo de espera agotado. Intenta más tarde.',
	'sure delete csv' => '¿Eliminar el archivo CSV [CSVFILE] del servidor?',
	'invalid csv file selected' => 'Archivo inválido. Debe ser CSV.',
	'couldnt delete csv file' => "No se pudo eliminar el archivo CSV.",
	'error backing up table' => "Error: No se pudo respaldar la tabla <TABLE>.",
	'no columns selected' => 'Selecciona al menos una columna única para importar.',
	'csrf token expired or invalid' => '¡Oops! Algo salió mal. Por favor recarga la página.',
	'back to groups' => 'Volver a grupos',
	'member updated' => 'Miembro <USERNAME> actualizado exitosamente',
	'fix errors before submitting' => '¡Corrige los errores resaltados antes de enviar!',
	'mail_function' => 'Método de envío de correos',
	'smtp_server' => 'Servidor SMTP',
	'smtp_encryption' => 'Cifrado SMTP',
	'smtp_port' => 'Puerto SMTP',
	'smtp_port_hint' => 'Valores típicos: 25 (sin cifrar), 465 (SSL), 587 (TLS)',
	'smtp_user' => 'Usuario SMTP',
	'smtp_pass' => 'Contraseña SMTP',
	'configure mail settings' => 'Configurar opciones de correo',
	'display debugging info' => 'Mostrar información de depuración',
	'debugging info hint' => 'Útil para resolver problemas de envío SMTP.',
	'create backup file' => 'Crear Respaldo',
	'database backups' => 'Respaldos de Base de Datos',
	'no backups found' => 'No hay respaldos. Crea uno nuevo.',
	'available backups' => 'Respaldos Disponibles',
	'restore backup' => 'Restaurar',
	'delete backup' => 'Eliminar',
	'backup restored' => 'Respaldo restaurado exitosamente.',
	'backup deleted' => 'Respaldo eliminado exitosamente.',
	'restore error' => 'Error al restaurar respaldo.',
	'backup delete error' => 'Error al eliminar respaldo.',
	'confirm delete backup' => '¿Eliminar este respaldo?',
	'confirm restore' => 'Restaurar sobreescribirá todos los datos actuales. ¿Continuar?',
	'confirm backup' => 'Se activará modo mantenimiento durante el respaldo. ¿Continuar?',
	'cant create backup folder' => "Error: No se pudo crear/escribir en la carpeta 'admin/backups'. Verifica permisos.",
	'fix all' => 'CORREGIR TODOS LOS CAMPOS',
	'backup before fix' => "Se recomienda respaldar antes de realizar correcciones.",
	'about backups' => 'Los respaldos usan mysqldump. Si fallan, verifica permisos del servidor.',
	'server status disabled' => 'El estado del servidor está deshabilitado. Habilita la opción al regenerar la app.',
	'server status' => 'Estado del Servidor',
	'db status' => 'Estado de la Base de Datos',
	'generated by' => 'Esta aplicación fue generada por AppGini <VERSION> el <DATETIME>.',
	'column table name' => 'Nombre de tabla',
	'db storage' => 'Almacenamiento de BD',
	'column size kb' => 'Tamaño (KB)',
	'total' => 'Total',
	'php info' => 'Info de PHP',
	'files' => 'archivos',
	'uploads info' => 'Info de Subidas',
	'quick search' => 'Búsqueda Rápida',
	'records x to y of z' => 'Registros <FirstRecord> a <LastRecord> de <RecordCount>',
	'filters' => 'Filtros',
	'filter' => 'Filtrar',
	'filtered field' => 'Campo filtrado',
	'comparison operator' => 'Operador de comparación',
	'comparison value' => 'Valor de comparación',
	'and' => 'Y',
	'or' => 'O',
	'equal to' => 'Igual a',
	'not equal to' => 'No igual a',
	'greater than' => 'Mayor que',
	'greater than or equal to' => 'Mayor o igual que',
	'less than' => 'Menor que',
	'less than or equal to' => 'Menor o igual que',
	'like' => 'Como',
	'not like' => 'No como',
	'is empty' => 'Está vacío',
	'is not empty' => 'No está vacío',
	'apply filters' => 'Aplicar filtros',
	'save filters' => 'Guardar y aplicar filtros',
	'saved filters title' => 'Código HTML para los filtros aplicados',
	'saved filters instructions' => 'Copia este código en un archivo HTML para guardar los filtros y acceder luego.',
	'hide code' => 'Ocultar código',
	'printer friendly view' => 'Vista para imprimir',
	'save as csv' => 'Descargar como CSV',
	'edit filters' => 'Editar filtros',
	'clear filters' => 'Limpiar filtros',
	'order by' => 'Ordenar por',
	'go to page' => 'Ir a página:',
	'none' => 'Ninguno',
	'Select all records' => 'Seleccionar todos los registros',
	'With selected records' => 'Con los registros seleccionados',
	'Print Preview Detail View' => 'Vista Previa Detallada para Imprimir',
	'Print Preview Table View' => 'Vista Previa de Tabla para Imprimir',
	'Print' => 'Imprimir',
	'Cancel Printing' => 'Cancelar Impresión',
	'Cancel Selection' => 'Cancelar Selección',
	'Maximum records allowed to enable this feature is' => 'Máximo de registros permitidos para esta función es',
	'No matches found!' => '¡No se encontraron coincidencias!',
	'Start typing to get suggestions' => 'Escribe para obtener sugerencias.',
	'are you sure?' => '¿Estás seguro de eliminar este registro?',
	'add new record' => 'Agregar nuevo registro',
	'update record' => 'Actualizar registro',
	'deselect record' => 'Deseleccionar registro',
	"couldn't delete" => 'No se pudo eliminar debido a <RelatedRecords> registros relacionados en [<TableName>]',
	'confirm delete' => 'Este registro tiene <RelatedRecords> relacionados en [<TableName>]. ¿Eliminar? <Delete> &nbsp; <Cancel>',
	'yes' => 'Sí',
	'pkfield empty' => ' es campo clave primaria y no puede estar vacío.',
	'upload image' => 'Subir nuevo archivo ',
	'select image' => 'Seleccionar imagen ',
	'remove image' => 'Eliminar archivo',
	'month names' => 'Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre',
	'field not null' => 'Este campo no puede estar vacío.',
	'*' => '*',
	'today' => 'Hoy',
	'Hold CTRL key to select multiple items from the above list.' => 'Mantén CTRL para seleccionar múltiples elementos.',
	'Save New' => 'Guardar Nuevo',
	'Save As Copy' => 'Guardar Como Copia',
	'Deselect' => 'Cancelar',
	'Add New' => 'Agregar Nuevo',
	'Delete' => 'Eliminar',
	'Cancel' => 'Cancelar',
	'Print Preview' => 'Vista Previa',
	'Save Changes' => 'Guardar Cambios',
	'CSV' => 'Guardar CSV',
	'Reset Filters' => 'Mostrar Todos',
	'Find It' => 'Buscar',
	'Previous' => 'Anterior',
	'Next' => 'Siguiente',
	'Back' => 'Atrás',
	'homepage' => 'Página Principal',
	'error:' => 'Error:',
	'sql error:' => 'Error SQL:',
	'query:' => 'Consulta:',
	'< back' => 'Atrás',
	"if you haven't set up" => "Si no has configurado la base de datos, hazlo <a href='setup.php'>aquí</a>.",
	'file too large' => 'Error: El archivo excede el tamaño máximo de <MaxSize> KB',
	'invalid file type' => 'Error: Tipo de archivo no permitido. Solo <FileTypes>.',
	'goto start page' => 'Volver a la página inicial',
	'no db connection' => "No se pudo conectar a la base de datos.",
	'no db name' => "No se pudo acceder a la base de datos '<DBName>'.",
	'provide connection data' => 'Provee los siguientes datos para conectarte:',
	'mysql server' => 'Servidor MySQL (host)',
	'mysql username' => 'Usuario MySQL',
	'mysql password' => 'Contraseña MySQL',
	'mysql db' => 'Nombre de la base de datos',
	'connect' => 'Conectar',
	'setup performed' => 'Configuración realizada el',
	'delete md5' => "Para forzar la configuración nuevamente, elimina el archivo 'setup.md5'.",
	'table exists' => 'Tabla <b><TableName></b> existe, con <NumRecords> registros.',
	'failed' => 'Falló',
	'mysql said' => 'MySQL dijo:',
	'table uptodate' => 'La tabla está actualizada.',
	'couldnt count' => "No se pudo contar registros en <b><TableName></b>",
	'creating table' => 'Creando tabla <b><TableName></b> ... ',
	'tableAccessDenied' => "No tienes permiso para acceder a esta tabla. Contacta al admin.",
	'not signed in' => 'No has iniciado sesión',
	'sign in' => 'Iniciar Sesión',
	'signed as' => 'Sesión iniciada como',
	'admin setup needed' => 'La configuración del admin no se ha realizado. Inicia sesión en el <a href=admin/>panel de control</a>.',
	'db setup needed' => 'La configuración no se ha realizado. Accede a <a href=setup.php>setup.php</a>.',
	'new record saved' => 'El nuevo registro se guardó exitosamente.',
	'record updated' => 'Los cambios se guardaron exitosamente.',
	'login failed' => 'Inicio de sesión fallido. Intenta de nuevo.',
	'sign in here' => 'Iniciar Sesión Aquí',
	'remember me' => 'Recordarme',
	'go to signup' => "¿No tienes usuario? <br>&nbsp; <a href=membership_signup.php>Regístrate aquí</a>",
	'forgot password' => '¿Olvidaste tu contraseña? <a href=membership_passwordReset.php>Haz clic aquí</a>',
	'no table access' => "No tienes permisos suficientes. Inicia sesión primero.",
	'signup' => 'Registrarse',
	'user already exists' => "El usuario '<MemberID>' ya existe. Prueba otro nombre.",
	'user available' => "El usuario '<MemberID>' está disponible.",
	'empty user' => "Escribe un nombre de usuario y haz clic en 'Verificar disponibilidad'.",
	'thanks' => '¡Gracias por registrarte!',
	'sign in no approval' => "Si elegiste un grupo sin aprobación, puedes iniciar sesión <a href=index.php?signIn=1>aquí</a>.",
	'sign in wait approval' => "Si elegiste un grupo con aprobación, espera un correo de confirmación.",
	'username empty' => 'Debes proveer un nombre de usuario.',
	'password invalid' => 'La contraseña debe tener al menos 4 caracteres sin espacios.',
	'password no match' => 'Las contraseñas no coinciden.',
	'username exists' => 'El nombre de usuario ya existe. Elige otro.',
	'email invalid' => 'Correo electrónico inválido.',
	'group invalid' => 'Grupo inválido.',
	'sign up here' => '¡Regístrate Aquí!',
	'registered? sign in' => '¿Ya registrado? <a href=index.php?signIn=1>Inicia sesión aquí</a>.',
	'sign up disabled' => '¡El registro está temporalmente deshabilitado!',
	'groups *' => "Los grupos marcados con * requieren aprobación del admin para iniciar sesión.",
	'sign up' => 'Registrarse',
	'password reset' => 'Restablecer Contraseña',
	'password reset details' => "Ingresa tu usuario o correo. Enviaremos un enlace para restablecer tu contraseña.",
	'password reset subject' => 'Instrucciones para restablecer contraseña',
	'password reset message' => "Estimado miembro, \n Si solicitaste restablecer tu contraseña, haz clic aquí: \n <ResetLink> \n\n Si no lo solicitaste, ignora este mensaje. \n\n Saludos.",
	'password reset ready' => "Se envió un correo con instrucciones. Si no lo recibes en 5 minutos, inténtalo de nuevo.",
	'password reset invalid' => 'Usuario o correo inválido. <a href=membership_passwordReset.php>Intenta de nuevo</a>.',
	'password change' => 'Cambiar Contraseña',
	'new password' => 'Nueva contraseña',
	'password reset done' => 'Contraseña cambiada. <a href=index.php?signOut=1>Inicia sesión aquí</a>.',
	'Loading ...' => 'Cargando ...',
	'No records found' => 'No se encontraron registros',
	'You can add children records after saving the main record first' => 'Puedes agregar registros hijos después de guardar el principal.',
	'ascending' => 'Ascendente',
	'descending' => 'Descendente',
	'then by' => 'Luego por',
	'Legend' => 'Leyenda',
	'Table' => 'Tabla',
	'Edit' => 'Editar',
	'View' => 'Ver',
	'Only your own records' => 'Solo tus registros',
	'All records owned by your group' => 'Todos los registros de tu grupo',
	'All records' => 'Todos los registros',
	'Not allowed' => 'No permitido',
	'Your info' => 'Tu información',
	'Hello user' => '¡Hola %s!',
	'Your access permissions' => 'Tus permisos de acceso',
	'Update profile' => 'Actualizar perfil',
	'Update password' => 'Cambiar contraseña',
	'Change your password' => 'Cambiar tu contraseña',
	'Old password' => 'Contraseña Anterior',
	'Password strength: weak' => 'Seguridad de contraseña: débil',
	'Password strength: good' => 'Seguridad de contraseña: buena',
	'Password strength: strong' => 'Seguridad de contraseña: fuerte',
	'Wrong password' => 'Contraseña incorrecta',
	'Your profile was updated successfully' => 'Perfil actualizado exitosamente',
	'Your password was changed successfully' => 'Contraseña cambiada exitosamente',
	'Your IP address' => 'Tu dirección IP',
	'Records to display' => 'Registros a mostrar',
	'Setup Data' => 'Datos de Configuración',
	'Database Information' => 'Información de la Base de Datos',
	'Admin Information' => 'Información del Administrador',
	'setup intro 1' => "No hay archivo de configuración. Esta página te ayudará a crearlo. En algunos servidores, es posible que debas ajustar permisos o crearlo manualmente.",
	'setup intro 2' => "¡Bienvenido a tu aplicación AppGini! Necesitamos información sobre tu base de datos: servidor, nombre, usuario y contraseña.",
	'setup finished' => '<b>¡Éxito!</b><br><br>Sugerencias para comenzar:',
	'setup next 1' => 'Usa la aplicación para agregar o trabajar con datos.',
	'setup next 2' => 'Importa datos desde un archivo CSV.',
	'setup next 3' => 'Visita el panel de admin para más configuraciones.',
	'db_name help' => 'Nombre de la base de datos para tu aplicación.',
	'db_server help' => 'Normalmente "localhost". Consulta con tu proveedor.',
	'db_username help' => 'Tu usuario de MySQL.',
	'db_password help' => 'Tu contraseña de MySQL.',
	'username help' => "Nombre de usuario para acceder al área de admin (mínimo 4 caracteres).",
	'password help' => 'Contraseña segura para el admin.',
	'email help' => 'Correo para notificaciones del admin.',
	'Continue' => 'Continuar ...',
	'Lets go' => "¡Comencemos!",
	'Submit' => 'Enviar',
	'Hide' => 'Ocultar ayuda',
	'Database info is correct' => '&#10003; ¡Información correcta!',
	'Database connection error' => '&#10007; ¡Error de conexión!',
	'The following errors occurred' => 'Ocurrieron los siguientes errores',
	'failed to create config instructions' => 'Copia este código en un archivo "config.php" y súbelo a %s.',
	'Only show records having filterer' => 'Mostrar solo registros donde %s es %s',
	"You don't have enough permissions to delete this record" => "No tienes permiso para eliminar este registro",
	"Couldn't delete this record" => "No se pudo eliminar este registro",
	'The record has been deleted successfully' => 'Registro eliminado exitosamente',
	"Couldn't save changes to the record" => "No se pudieron guardar los cambios",
	"Couldn't save the new record" => "No se pudo guardar el nuevo registro",
	'More' => 'Más',
	'Confirm deleting multiple records' => 'Confirmar eliminación múltiple',
	'<n> records will be deleted. Are you sure you want to do this?' => '¿Eliminar <n> registros? ¿Continuar?',
	'Yes, delete them!' => '¡Sí, eliminar!',
	'No, keep them.' => 'No, conservar.',
	'Deleting record <i> of <n>' => 'Eliminando registro <i> de <n>',
	'Delete progress' => 'Progreso de eliminación',
	'Show/hide details' => 'Mostrar/ocultar detalles',
	'Connection error' => 'Error de conexión',
	'Add more actions' => 'Agregar más acciones',
	'Update progress' => 'Progreso de actualización',
	'Change owner' => 'Cambiar dueño',
	'Updating record <i> of <n>' => 'Actualizando registro <i> de <n>',
	'Change owner of <n> selected records to' => 'Cambiar dueño de <n> registros seleccionados a',
	'username invalid' => 'Usuario <MemberID> ya existe o es inválido. Usa 4-20 caracteres válidos.',
	'permalink' => 'Enlace permanente',
	'invalid provider' => '¡Proveedor inválido!',
	'invalid url' => '¡URL inválida!',
	'cant retrieve coordinates from url' => "No se pudieron obtener coordenadas de la URL.",
	'unique field error' => 'Este valor ya existe o es inválido. Usa uno único.',
	'show all user records from table' => 'Mostrar todos los registros de este usuario en "<tablename>"',
	'show all group records from table' => 'Mostrar todos los registros de este grupo en "<tablename>"',
	'email this user' => 'Enviar correo a este usuario',
	'email this group' => 'Enviar correo a este grupo',
	'last modified' => 'Última modificación',
	'record has no owner' => 'Este registro no tiene dueño asignado. Asigna uno desde el área de admin.',
	'admin-only info' => "Esta información es visible solo para el super admin.",
	'discard changes confirm' => '¿Descartar cambios en este registro?',
	'hide/show columns' => 'Ocultar/Mostrar columnas',
	'next column' => 'Siguiente columna',
	'previous column' => 'Columna anterior',
	'hide all' => 'Ocultar todas',
	'toggle' => 'Alternar',
	'datetimepicker locale' => 'es',
	'account token theft warning' => 'Alguien intentó acceder a tu cuenta. Por seguridad, debes volver a iniciar sesión.',
	'group added successfully' => 'Grupo agregado exitosamente',
	'group updated successfully' => 'Cambios en el grupo guardados exitosamente',
	'saved filter link' => 'Enlace de filtro guardado',
	'app documentation' => 'Documentación de la aplicación',
	'back to top' => 'Volver arriba',
	'check all' => 'Marcar todos',
	'uncheck all' => 'Desmarcar todos',
	'invert checks' => 'Invertir marcas',
	'set all to x' => 'Establecer todos a <x>',
	'tip check csv for errors' => 'Sugerencia: Verifica errores en tu CSV usando <a href="https://csvlint.io/" target="_blank">csvlint.io</a>',
	'keyboard shortcuts' => 'Atajos de teclado',
	'keyboard shortcuts disabled' => 'Atajos deshabilitados',
	'keyboard shortcuts enabled' => 'Atajos habilitados',
	'Enable' => 'Habilitar',
	'Disable' => 'Deshabilitar',
	'display this help window' => 'Mostrar esta ventana de ayuda',
	'close this window' => 'Cerrar esta ventana',
	'open x navigation menu' => 'Abrir menú de navegación <b><x></b>',
	'user profile' => 'Perfil de usuario',
	'clear search' => 'Limpiar búsqueda',
	'navigate between sections of page' => 'Navegar entre secciones de la página',
	'open admin info menu' => 'Abrir menú de información del admin',
	'navigate between sections of child records' => 'Navegar entre secciones de registros hijos',
	'old php version' => "Estás usando PHP <PHP_VERSION>. La versión mínima requerida es <minPHP>. Actualiza PHP o instala en otro servidor.",
	'extension not enabled' => "La extensión <EXTENSION> no está habilitada. Habilítala en php.ini y reinicia el servidor.",
	'error reading csv file' => 'Error leyendo archivo CSV. Verifica que exista y la configuración sea correcta.',
	'clean csv dir error' => 'No se pudo crear o escribir en el directorio "import-csv".',
	'Invalid import job' => 'Trabajo de importación inválido',
	'Previous record' => 'Registro anterior',
	'Next record' => 'Registro siguiente',
	'job in progress by another process' => 'El trabajo ya está en curso por otro proceso',
	'invalid clean csv file' => 'Archivo CSV limpio inválido o no listo',
	'invalid csv map' => 'Mapeo CSV inválido',
	'invalid field separator' => 'Separador de campos inválido',
	'import csv file' => 'Importar archivo CSV a una tabla',
	'import another csv file' => 'Importar otro archivo CSV',
	'file upload error' => 'Error subiendo archivo',
	'to use tab' => 'Para usar TAB como separador, escribe TAB',
	'field qualifier' => 'Calificador de campo (delimitador)',
	'auto-detect csv columns' => 'Detectar columnas automáticamente según la tabla seleccionada.',
	'nothing to import' => 'Nada para importar. Selecciona al menos una columna.',
	'multiple columns mapped to same field' => "No puedes mapear múltiples columnas al mismo campo.",
	'uploading in x seconds' => 'La subida comenzará en [SECONDS] segundos.',
	'cancel and back to csv upload' => 'Cancelar y elegir otro archivo CSV',
	'confirm importing csv' => 'Confirmar importación de datos CSV a la tabla seleccionada',
	'total records' => 'Total de registros',
	'imported records' => 'Registros importados',
	'remaining' => 'Restantes',
	'ETA' => 'Tiempo estimado',
	'import finished' => 'Importación finalizada. Accede a los registros en la tabla especificada.',
	'import job taking long keep page open permalink' => 'Esta importación está tomando tiempo. Puedes mantener esta página abierta y trabajar en otra pestaña. Copia el enlace para continuar luego.',
	'pause' => 'Pausar',
	'resume' => 'Reanudar',
	'new' => 'Nuevo',
	'updated' => 'Actualizado',
	'skipped' => 'Omitido',
	'fast import mode' => 'Modo rápido (más veloz, estadísticas menos precisas, dueño asignado después)',
	'assign owner for n records in table' => 'Asignar dueño para [n] registros sin dueño en esta tabla',
	'no update missing pk field in csv' => "Actualizar deshabilitado: falta clave primaria en CSV o sin permisos de edición.",
	'no insert update only' => "No tienes permiso para insertar nuevos registros. Solo actualizaciones permitidas.",
	'allow importing CSV files' => 'Permitir importar archivos CSV',
	'description of import CSV files option' => 'Permite a usuarios importar CSV en tablas donde tengan permisos de inserción/edición.',
	'admin group attention' => '¡Atención! Este es el grupo admin.',
	'toggle import logs' => 'Mostrar/ocultar registros de importación',
	'admin csv warning' => 'Esta página será eliminada en futuras versiones. Usa la nueva página de importación CSV.',
	'Jump to' => 'Saltar a ...',
	'check username availability' => 'Verificar disponibilidad de este nombre de usuario',
	'try rebuild fields' => 'Intenta solucionar desde el Área de Admin: Utilidades > Ver/Reconstruir Campos.',
	'click continue if slow' => 'Si esta página tarda en cargar, [a]haz clic para continuar[/a].',

	// Añadido en 5.91
	'keyboard shorcuts reference' => 'Referencia de atajos de teclado',

	// Añadido en 5.93
	'google API key' => 'Clave de API de Google',
	'google API key instructions' => '¿Cómo obtener y configurar tu clave de API de Google?',
	'base upload path' => 'Ruta base de subidas',
	'base upload path change warning' => 'Cambiar esta ruta hará inaccesibles archivos existentes hasta moverlos a la nueva ubicación.',
	'base upload path instructions' => 'Ruta donde se almacenan archivos subidos. Relativa a la aplicación o fuera usando "../".',
	'invalid upload path' => 'La ruta de subida especificada no existe y no pudo crearse.',
	'Appearance' => 'Apariencia',
	'Mail' => 'Correo',
	'Preconfigured users and groups' => 'Usuarios y grupos preconfigurados',
	'Application' => 'Aplicación',

	// Añadido en 5.97
	'Query logs' => 'Registros de consultas',
	'Query log table does not exist' => 'Error creando tabla appgini_query_log. Verifica permisos de usuario.',
	'slow queries' => 'Consultas lentas',
	'error queries' => 'Consultas con error',
	'date/time' => 'Fecha/hora',
	'duration (sec)' => 'Duración (seg)',
	'page address' => 'Dirección de la página',
	'query' => 'Consulta',
	'page x of y' => 'Página <x> de <y>',
	'total # queries' => 'Total de consultas.',

	// Añadido en 6.0
	'Interactive SQL queries tool' => 'Herramienta interactiva de consultas SQL',
	'Enter SQL query' => 'Ingresar consulta SQL',
	'Query must start with select' => 'La consulta debe comenzar con %s',
	'Display results' => 'Mostrar resultados',
	'Update results as you type' => 'Actualizar resultados al escribir',
	'Use cache' => 'Usar caché',
	'results truncated' => 'Los resultados pueden estar truncados a %s registros por rendimiento.',
	'Results will be displayed here' => 'Los resultados se mostrarán aquí.',
	'Bookmark this query' => 'Guardar esta consulta',
	'Query name' => 'Nombre de la consulta',
	'Manage bookmarked queries' => 'Administrar consultas guardadas',

	// Añadido en 22.11
	'continue browsing as guest' => 'Continuar navegando como invitado',
	'translation tool' => 'Herramienta de traducción',

	// Añadido en 22.12
	'query logs older than 2 month auto cleared' => 'Los registros de consultas mayores a 2 meses se borran automáticamente. Puedes borrarlos manualmente con los botones abajo.',
	'clear slow queries' => 'Borrar consultas lentas',
	'clear error queries' => 'Borrar consultas con error',
	'confirm clear logs' => '¿Confirmas borrar estos registros?',
	'query logs cleared' => 'Registros de <TYPE> borrados.',
	'unicode error' => 'Error de configuración Unicode',
	'unicode needs fixing' => 'La codificación Unicode de la base de datos y/o algunas tablas necesita corrección.',
	'unicode fix details' => 'Las tablas en codificación utf8 se ajustarán a utf8mb4 para soportar todos los caracteres Unicode.',
	'fix unicode' => 'Corregir Unicode',
	'Messages' => 'Mensajes',

	// Añadido en 22.13
	'mysql port' => 'Puerto MySQL',
	'db_port help' => 'Si MySQL usa un puerto diferente al predeterminado %s, ingrésalo.',
	'checking database info' => 'Verificando información de la base de datos ...',
	'if error persists check query log' => 'Si el error persiste, revisa el registro de consultas para más detalles',

	// Añadido en 23.14
	'send mail to too many members' => "Estás enviando un correo a demasiados miembros. Esto puede afectar el rendimiento. No recomendado para muchos miembros.",
	'n recipients' => '%s destinatarios',
	'messages plugin cta' => 'Escapa del caos del correo. Experimenta la comunicación eficiente con el Plugin de Mensajes para AppGini.',
	'update calculated fields' => 'Actualizar campos calculados',
	'no tables with calculated fields' => 'No se encontraron tablas con campos calculados.',
	'description for updating calculated fields' => 'Esta herramienta actualiza campos calculados en todos los registros. Útil al agregar nuevos campos o cambiar fórmulas.',
	'cli tool for updating calculated fields' => 'Existe una herramienta de línea de comandos para automatizar esta tarea. Ejecuta en terminal:',
	'start updating' => 'Comenzar actualización',
	'captcha label' => 'Ingresa los caracteres de la imagen',

	// Añadido en 23.17
	'Explore more plugins' => 'Explora más plugins',
	'Install a plugin' => 'Instalar un plugin',
	'invalid order number' => 'Número de pedido inválido',
	'invalid order login' => 'No se encontró un pedido con el número y correo proporcionados.',
	'order number' => 'Número de Pedido',
	'view available plugins' => 'Ver plugins disponibles',
	'plugin check instructions' => 'Ingresa tu correo y número de pedido para verificar plugins disponibles.',
	'no plugins available' => 'No hay plugins disponibles para este pedido.',
	'install selected plugins' => 'Instalar plugins seleccionados',
	'select plugins to install' => 'Seleccionar plugins para instalar',
	'plugins install progress' => 'Progreso de instalación',
	'already installed' => 'ya instalado el %s (marca para reinstalar)',
	'plugin install failed' => '¡Instalación fallida!',
	'plugin installed successfully' => '¡Plugin instalado! Haz clic para iniciar.',
	'missing dependencies' => 'Errores o dependencias faltantes',

	// Añadido en 24.10
	'fix record owners' => 'Corregir dueños de registros',
	'record owner not configured for this table' => 'Dueño de registro no configurado para esta tabla.',
	'start' => 'Iniciar',
	'fixing record owners' => 'Corrigiendo dueños de registros ...',
	'number of runs' => 'Número de ejecuciones',
	'no tables to fix record owners' => 'No hay tablas con dueños configurados. Nada que corregir.',
	'fix record owners description' => 'Actualiza dueños de registros en tablas con configuración reciente de dueños.',
	'records updated:' => 'Registros actualizados: ',
	'ldap disable user signup' => 'Deshabilitar (solo admins pueden agregar usuarios)',
	'ldap settings' => 'Configuración LDAP',
	'login method' => 'Método de inicio de sesión',
	'default' => 'Predeterminado',
	'ldap' => 'LDAP',
	'ldap server' => 'Servidor LDAP',
	'ldap version' => 'Versión LDAP',
	'ldap username prefix' => 'Prefijo de usuario LDAP',
	'ldap username suffix' => 'Sufijo de usuario LDAP',
	'ldap default user group' => 'Grupo predeterminado para nuevos usuarios LDAP',
	'Examples: ' => 'Ejemplos: ',
	'Example: ' => 'Ejemplo: ',
	'ldap admin user warning' => 'Antes de habilitar LDAP, asegúrate que el usuario admin %s exista en el servidor LDAP.',

	// Añadido en 24.11
	'SQL' => 'SQL',
	'click to copy' => 'Haz clic para copiar',
	'copied' => '¡Copiado!',

	// Añadido en 24.13
	'db server status' => 'Estado del servidor de base de datos',
	'db client status' => 'Estado del cliente de base de datos',
	'date and time info' => 'Información de fecha y hora',

	// Añadido en 24.14
	'Copy permissions from another group' => 'Copiar permisos de otro grupo',
	'revert permissions' => 'Restablecer permisos',

	// Añadido en 24.18
	'Capture my location' => 'Capturar mi ubicación',
	'Could not capture your location' => 'No se pudo capturar tu ubicación',
	'You must allow the browser to capture your location' => 'Debes permitir que el navegador capture tu ubicación',
	'restrict API key' => '¡IMPORTANTE! Restringe tu clave de API por IP o sitio web para evitar abusos.',

	// Añadido en 24.19
	'no insert permission' => 'No tienes permiso para insertar registros en esta tabla.',

	// Añadido en 25.10
	'download' => 'Descargar',
	
	// Añadido en 25.11
	'offline mode' => 'Modo sin conexión',
	'offline mode message' => 'Estás desconectado del servidor. Por favor, comprueba tu conexión a internet e inténtalo de nuevo.',
	'retry' => 'Reintentar',
	'install mobile app' => 'Instalar aplicación móvil',
	'match all above conditions' => 'Cumplir todas las condiciones anteriores',
	'all of the following conditions' => 'Se aplican todas las siguientes condiciones',
	'any of the following conditions' => 'Se aplica cualquiera de las siguientes condiciones',
	'find records that match' => 'Buscar %s que cumplan:',
	'match all groups' => 'Cumplir todos los grupos',
	'add another condition group' => 'Añadir otro grupo de condiciones',
	'add another condition to this group' => 'Añadir otra condición a este grupo',
	'remove this condition' => 'Eliminar esta condición',
	'invalid theme' => 'Tema no válido',
	'theme selector' => 'Selector de temas',
	'large text' => 'Texto grande',
	'small text' => 'Texto pequeño',
	'update theme' => 'Actualizar tema',
	'default theme' => 'Tema predeterminado',
	'your theme was updated successfully' => 'Tu tema se actualizó correctamente',
	'my account' => 'Mi cuenta',
];