<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/modalidades_contacto.php');
	include_once(__DIR__ . '/modalidades_contacto_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('modalidades_contacto');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'modalidades_contacto';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`modalidades_contacto`.`modalidad_contacto_id`" => "modalidad_contacto_id",
		"`modalidades_contacto`.`nombre`" => "nombre",
		"`modalidades_contacto`.`descripcion`" => "descripcion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`modalidades_contacto`.`modalidad_contacto_id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`modalidades_contacto`.`modalidad_contacto_id`" => "modalidad_contacto_id",
		"`modalidades_contacto`.`nombre`" => "nombre",
		"`modalidades_contacto`.`descripcion`" => "descripcion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`modalidades_contacto`.`modalidad_contacto_id`" => "Modalidad contacto id",
		"`modalidades_contacto`.`nombre`" => "Nombre",
		"`modalidades_contacto`.`descripcion`" => "Descripcion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`modalidades_contacto`.`modalidad_contacto_id`" => "modalidad_contacto_id",
		"`modalidades_contacto`.`nombre`" => "nombre",
		"`modalidades_contacto`.`descripcion`" => "descripcion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`modalidades_contacto` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'modalidades_contacto_view.php';
	$x->TableTitle = 'Modalidades contacto';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`modalidades_contacto`.`modalidad_contacto_id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Modalidad contacto id', 'Nombre', 'Descripcion', ];
	$x->ColFieldName = ['modalidad_contacto_id', 'nombre', 'descripcion', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/modalidades_contacto_templateTV.html';
	$x->SelectedTemplate = 'templates/modalidades_contacto_templateTVS.html';
	$x->TemplateDV = 'templates/modalidades_contacto_templateDV.html';
	$x->TemplateDVP = 'templates/modalidades_contacto_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: modalidades_contacto_init
	$render = true;
	if(function_exists('modalidades_contacto_init')) {
		$args = [];
		$render = modalidades_contacto_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: modalidades_contacto_header
	$headerCode = '';
	if(function_exists('modalidades_contacto_header')) {
		$args = [];
		$headerCode = modalidades_contacto_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: modalidades_contacto_footer
	$footerCode = '';
	if(function_exists('modalidades_contacto_footer')) {
		$args = [];
		$footerCode = modalidades_contacto_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
