<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/motivos_cierre.php');
	include_once(__DIR__ . '/motivos_cierre_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('motivos_cierre');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'motivos_cierre';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`motivos_cierre`.`motivo_cierre_id`" => "motivo_cierre_id",
		"`motivos_cierre`.`nombre`" => "nombre",
		"`motivos_cierre`.`descripcion`" => "descripcion",
		"`motivos_cierre`.`es_positivo`" => "es_positivo",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`motivos_cierre`.`motivo_cierre_id`',
		2 => 2,
		3 => 3,
		4 => '`motivos_cierre`.`es_positivo`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`motivos_cierre`.`motivo_cierre_id`" => "motivo_cierre_id",
		"`motivos_cierre`.`nombre`" => "nombre",
		"`motivos_cierre`.`descripcion`" => "descripcion",
		"`motivos_cierre`.`es_positivo`" => "es_positivo",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`motivos_cierre`.`motivo_cierre_id`" => "Motivo cierre id",
		"`motivos_cierre`.`nombre`" => "Nombre",
		"`motivos_cierre`.`descripcion`" => "Descripcion",
		"`motivos_cierre`.`es_positivo`" => "Es positivo",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`motivos_cierre`.`motivo_cierre_id`" => "motivo_cierre_id",
		"`motivos_cierre`.`nombre`" => "nombre",
		"`motivos_cierre`.`descripcion`" => "descripcion",
		"`motivos_cierre`.`es_positivo`" => "es_positivo",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`motivos_cierre` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'motivos_cierre_view.php';
	$x->TableTitle = 'Motivos cierre';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`motivos_cierre`.`motivo_cierre_id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Motivo cierre id', 'Nombre', 'Descripcion', 'Es positivo', ];
	$x->ColFieldName = ['motivo_cierre_id', 'nombre', 'descripcion', 'es_positivo', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/motivos_cierre_templateTV.html';
	$x->SelectedTemplate = 'templates/motivos_cierre_templateTVS.html';
	$x->TemplateDV = 'templates/motivos_cierre_templateDV.html';
	$x->TemplateDVP = 'templates/motivos_cierre_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: motivos_cierre_init
	$render = true;
	if(function_exists('motivos_cierre_init')) {
		$args = [];
		$render = motivos_cierre_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: motivos_cierre_header
	$headerCode = '';
	if(function_exists('motivos_cierre_header')) {
		$args = [];
		$headerCode = motivos_cierre_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: motivos_cierre_footer
	$footerCode = '';
	if(function_exists('motivos_cierre_footer')) {
		$args = [];
		$footerCode = motivos_cierre_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
