<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/noticias.php');
	include_once(__DIR__ . '/noticias_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('noticias');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'noticias';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`noticias`.`noticia_id`" => "noticia_id",
		"`noticias`.`referencia`" => "referencia",
		"`noticias`.`inmueble_id`" => "inmueble_id",
		"`noticias`.`cliente_id`" => "cliente_id",
		"`noticias`.`colaborador_id`" => "colaborador_id",
		"`noticias`.`estado_noticia_id`" => "estado_noticia_id",
		"`noticias`.`estado_contacto_id`" => "estado_contacto_id",
		"`noticias`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`noticias`.`detalle_procedencia_id`" => "detalle_procedencia_id",
		"`noticias`.`motivacion`" => "motivacion",
		"`noticias`.`valoracion`" => "valoracion",
		"`noticias`.`valoracion_solo_inmueble`" => "valoracion_solo_inmueble",
		"`noticias`.`precio_pedido`" => "precio_pedido",
		"if(`noticias`.`fecha_valoracion`,date_format(`noticias`.`fecha_valoracion`,'%d/%m/%Y'),'')" => "fecha_valoracion",
		"if(`noticias`.`fecha_estimacion_interna`,date_format(`noticias`.`fecha_estimacion_interna`,'%d/%m/%Y'),'')" => "fecha_estimacion_interna",
		"if(`noticias`.`fecha_ultima_cita`,date_format(`noticias`.`fecha_ultima_cita`,'%d/%m/%Y'),'')" => "fecha_ultima_cita",
		"if(`noticias`.`fecha_ultimo_contacto`,date_format(`noticias`.`fecha_ultimo_contacto`,'%d/%m/%Y'),'')" => "fecha_ultimo_contacto",
		"if(`noticias`.`fecha_cierre`,date_format(`noticias`.`fecha_cierre`,'%d/%m/%Y'),'')" => "fecha_cierre",
		"`noticias`.`motivo_cierre_id`" => "motivo_cierre_id",
		"`noticias`.`nota`" => "nota",
		"if(`noticias`.`fecha_creacion`,date_format(`noticias`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`noticias`.`fecha_modificacion`,date_format(`noticias`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`noticias`.`estado_noticia_id`',
		7 => '`noticias`.`estado_contacto_id`',
		8 => '`noticias`.`tipo_procedencia_id`',
		9 => '`noticias`.`detalle_procedencia_id`',
		10 => 10,
		11 => '`noticias`.`valoracion`',
		12 => '`noticias`.`valoracion_solo_inmueble`',
		13 => '`noticias`.`precio_pedido`',
		14 => '`noticias`.`fecha_valoracion`',
		15 => '`noticias`.`fecha_estimacion_interna`',
		16 => '`noticias`.`fecha_ultima_cita`',
		17 => '`noticias`.`fecha_ultimo_contacto`',
		18 => '`noticias`.`fecha_cierre`',
		19 => '`noticias`.`motivo_cierre_id`',
		20 => 20,
		21 => '`noticias`.`fecha_creacion`',
		22 => '`noticias`.`fecha_modificacion`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`noticias`.`noticia_id`" => "noticia_id",
		"`noticias`.`referencia`" => "referencia",
		"`noticias`.`inmueble_id`" => "inmueble_id",
		"`noticias`.`cliente_id`" => "cliente_id",
		"`noticias`.`colaborador_id`" => "colaborador_id",
		"`noticias`.`estado_noticia_id`" => "estado_noticia_id",
		"`noticias`.`estado_contacto_id`" => "estado_contacto_id",
		"`noticias`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`noticias`.`detalle_procedencia_id`" => "detalle_procedencia_id",
		"`noticias`.`motivacion`" => "motivacion",
		"`noticias`.`valoracion`" => "valoracion",
		"`noticias`.`valoracion_solo_inmueble`" => "valoracion_solo_inmueble",
		"`noticias`.`precio_pedido`" => "precio_pedido",
		"if(`noticias`.`fecha_valoracion`,date_format(`noticias`.`fecha_valoracion`,'%d/%m/%Y'),'')" => "fecha_valoracion",
		"if(`noticias`.`fecha_estimacion_interna`,date_format(`noticias`.`fecha_estimacion_interna`,'%d/%m/%Y'),'')" => "fecha_estimacion_interna",
		"if(`noticias`.`fecha_ultima_cita`,date_format(`noticias`.`fecha_ultima_cita`,'%d/%m/%Y'),'')" => "fecha_ultima_cita",
		"if(`noticias`.`fecha_ultimo_contacto`,date_format(`noticias`.`fecha_ultimo_contacto`,'%d/%m/%Y'),'')" => "fecha_ultimo_contacto",
		"if(`noticias`.`fecha_cierre`,date_format(`noticias`.`fecha_cierre`,'%d/%m/%Y'),'')" => "fecha_cierre",
		"`noticias`.`motivo_cierre_id`" => "motivo_cierre_id",
		"`noticias`.`nota`" => "nota",
		"if(`noticias`.`fecha_creacion`,date_format(`noticias`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`noticias`.`fecha_modificacion`,date_format(`noticias`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`noticias`.`noticia_id`" => "Noticia id",
		"`noticias`.`referencia`" => "Referencia",
		"`noticias`.`inmueble_id`" => "Inmueble id",
		"`noticias`.`cliente_id`" => "Cliente id",
		"`noticias`.`colaborador_id`" => "Colaborador id",
		"`noticias`.`estado_noticia_id`" => "Estado noticia id",
		"`noticias`.`estado_contacto_id`" => "Estado contacto id",
		"`noticias`.`tipo_procedencia_id`" => "Tipo procedencia id",
		"`noticias`.`detalle_procedencia_id`" => "Detalle procedencia id",
		"`noticias`.`motivacion`" => "Motivacion",
		"`noticias`.`valoracion`" => "Valoracion",
		"`noticias`.`valoracion_solo_inmueble`" => "Valoracion solo inmueble",
		"`noticias`.`precio_pedido`" => "Precio pedido",
		"`noticias`.`fecha_valoracion`" => "Fecha valoracion",
		"`noticias`.`fecha_estimacion_interna`" => "Fecha estimacion interna",
		"`noticias`.`fecha_ultima_cita`" => "Fecha ultima cita",
		"`noticias`.`fecha_ultimo_contacto`" => "Fecha ultimo contacto",
		"`noticias`.`fecha_cierre`" => "Fecha cierre",
		"`noticias`.`motivo_cierre_id`" => "Motivo cierre id",
		"`noticias`.`nota`" => "Nota",
		"`noticias`.`fecha_creacion`" => "Fecha creacion",
		"`noticias`.`fecha_modificacion`" => "Fecha modificacion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`noticias`.`noticia_id`" => "noticia_id",
		"`noticias`.`referencia`" => "referencia",
		"`noticias`.`inmueble_id`" => "inmueble_id",
		"`noticias`.`cliente_id`" => "cliente_id",
		"`noticias`.`colaborador_id`" => "colaborador_id",
		"`noticias`.`estado_noticia_id`" => "estado_noticia_id",
		"`noticias`.`estado_contacto_id`" => "estado_contacto_id",
		"`noticias`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`noticias`.`detalle_procedencia_id`" => "detalle_procedencia_id",
		"`noticias`.`motivacion`" => "motivacion",
		"`noticias`.`valoracion`" => "valoracion",
		"`noticias`.`valoracion_solo_inmueble`" => "valoracion_solo_inmueble",
		"`noticias`.`precio_pedido`" => "precio_pedido",
		"if(`noticias`.`fecha_valoracion`,date_format(`noticias`.`fecha_valoracion`,'%d/%m/%Y'),'')" => "fecha_valoracion",
		"if(`noticias`.`fecha_estimacion_interna`,date_format(`noticias`.`fecha_estimacion_interna`,'%d/%m/%Y'),'')" => "fecha_estimacion_interna",
		"if(`noticias`.`fecha_ultima_cita`,date_format(`noticias`.`fecha_ultima_cita`,'%d/%m/%Y'),'')" => "fecha_ultima_cita",
		"if(`noticias`.`fecha_ultimo_contacto`,date_format(`noticias`.`fecha_ultimo_contacto`,'%d/%m/%Y'),'')" => "fecha_ultimo_contacto",
		"if(`noticias`.`fecha_cierre`,date_format(`noticias`.`fecha_cierre`,'%d/%m/%Y'),'')" => "fecha_cierre",
		"`noticias`.`motivo_cierre_id`" => "motivo_cierre_id",
		"`noticias`.`nota`" => "nota",
		"if(`noticias`.`fecha_creacion`,date_format(`noticias`.`fecha_creacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_creacion",
		"if(`noticias`.`fecha_modificacion`,date_format(`noticias`.`fecha_modificacion`,'%d/%m/%Y %H:%i'),'')" => "fecha_modificacion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`noticias` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'noticias_view.php';
	$x->TableTitle = 'Noticias';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`noticias`.`noticia_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Noticia id', 'Referencia', 'Inmueble id', 'Cliente id', 'Colaborador id', 'Estado noticia id', 'Estado contacto id', 'Tipo procedencia id', 'Detalle procedencia id', 'Motivacion', 'Valoracion', 'Valoracion solo inmueble', 'Precio pedido', 'Fecha valoracion', 'Fecha estimacion interna', 'Fecha ultima cita', 'Fecha ultimo contacto', 'Fecha cierre', 'Motivo cierre id', 'Nota', 'Fecha creacion', 'Fecha modificacion', ];
	$x->ColFieldName = ['noticia_id', 'referencia', 'inmueble_id', 'cliente_id', 'colaborador_id', 'estado_noticia_id', 'estado_contacto_id', 'tipo_procedencia_id', 'detalle_procedencia_id', 'motivacion', 'valoracion', 'valoracion_solo_inmueble', 'precio_pedido', 'fecha_valoracion', 'fecha_estimacion_interna', 'fecha_ultima_cita', 'fecha_ultimo_contacto', 'fecha_cierre', 'motivo_cierre_id', 'nota', 'fecha_creacion', 'fecha_modificacion', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/noticias_templateTV.html';
	$x->SelectedTemplate = 'templates/noticias_templateTVS.html';
	$x->TemplateDV = 'templates/noticias_templateDV.html';
	$x->TemplateDVP = 'templates/noticias_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: noticias_init
	$render = true;
	if(function_exists('noticias_init')) {
		$args = [];
		$render = noticias_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: noticias_header
	$headerCode = '';
	if(function_exists('noticias_header')) {
		$args = [];
		$headerCode = noticias_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: noticias_footer
	$footerCode = '';
	if(function_exists('noticias_footer')) {
		$args = [];
		$footerCode = noticias_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
