<?php

// Data functions (insert, update, delete, form) for table noticias

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function noticias_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('noticias');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'noticia_id' => Request::val('noticia_id', ''),
		'referencia' => Request::val('referencia', ''),
		'inmueble_id' => Request::val('inmueble_id', ''),
		'cliente_id' => Request::val('cliente_id', ''),
		'colaborador_id' => Request::val('colaborador_id', ''),
		'estado_noticia_id' => Request::val('estado_noticia_id', ''),
		'estado_contacto_id' => Request::val('estado_contacto_id', ''),
		'tipo_procedencia_id' => Request::val('tipo_procedencia_id', ''),
		'detalle_procedencia_id' => Request::val('detalle_procedencia_id', ''),
		'motivacion' => Request::val('motivacion', ''),
		'valoracion' => Request::val('valoracion', ''),
		'valoracion_solo_inmueble' => Request::val('valoracion_solo_inmueble', ''),
		'precio_pedido' => Request::val('precio_pedido', ''),
		'fecha_valoracion' => Request::dateComponents('fecha_valoracion', ''),
		'fecha_estimacion_interna' => Request::dateComponents('fecha_estimacion_interna', ''),
		'fecha_ultima_cita' => Request::dateComponents('fecha_ultima_cita', ''),
		'fecha_ultimo_contacto' => Request::dateComponents('fecha_ultimo_contacto', ''),
		'fecha_cierre' => Request::dateComponents('fecha_cierre', ''),
		'motivo_cierre_id' => Request::val('motivo_cierre_id', ''),
		'nota' => br2nl(Request::val('nota', '')),
		'fecha_creacion' => parseCode('<%%creationDateTime%%>curdate()', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('noticias', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		noticias_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function noticias_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function noticias_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('noticias', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: noticias_before_delete
	if(function_exists('noticias_before_delete')) {
		$args = [];
		if(!noticias_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `noticias` WHERE `noticia_id`='{$selected_id}'", $eo);

	// hook: noticias_after_delete
	if(function_exists('noticias_after_delete')) {
		$args = [];
		noticias_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='noticias' AND `pkValue`='{$selected_id}'", $eo);
}

function noticias_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('noticias', $selected_id, 'edit')) return false;

	$data = [
		'noticia_id' => Request::val('noticia_id', ''),
		'referencia' => Request::val('referencia', ''),
		'inmueble_id' => Request::val('inmueble_id', ''),
		'cliente_id' => Request::val('cliente_id', ''),
		'colaborador_id' => Request::val('colaborador_id', ''),
		'estado_noticia_id' => Request::val('estado_noticia_id', ''),
		'estado_contacto_id' => Request::val('estado_contacto_id', ''),
		'tipo_procedencia_id' => Request::val('tipo_procedencia_id', ''),
		'detalle_procedencia_id' => Request::val('detalle_procedencia_id', ''),
		'motivacion' => Request::val('motivacion', ''),
		'valoracion' => Request::val('valoracion', ''),
		'valoracion_solo_inmueble' => Request::val('valoracion_solo_inmueble', ''),
		'precio_pedido' => Request::val('precio_pedido', ''),
		'fecha_valoracion' => Request::dateComponents('fecha_valoracion', ''),
		'fecha_estimacion_interna' => Request::dateComponents('fecha_estimacion_interna', ''),
		'fecha_ultima_cita' => Request::dateComponents('fecha_ultima_cita', ''),
		'fecha_ultimo_contacto' => Request::dateComponents('fecha_ultimo_contacto', ''),
		'fecha_cierre' => Request::dateComponents('fecha_cierre', ''),
		'motivo_cierre_id' => Request::val('motivo_cierre_id', ''),
		'nota' => br2nl(Request::val('nota', '')),
		'fecha_modificacion' => parseCode('<%%editingDateTime%%>current_timestamp()', false, true),
	];

	if($data['noticia_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Noticia id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['cliente_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cliente id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['estado_noticia_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado noticia id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['motivacion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Motivacion': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('noticias', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: noticias_before_update
	if(function_exists('noticias_before_update')) {
		$args = ['old_data' => $old_data];
		if(!noticias_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'noticias',
		backtick_keys_once($set),
		['`noticia_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="noticias_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['noticia_id'];
	$newID = $data['noticia_id'];

	update_calc_fields('noticias', $data['selectedID'], calculated_fields()['noticias']);

	// hook: noticias_after_update
	if(function_exists('noticias_after_update')) {
		if($row = getRecord('noticias', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['noticia_id'];
		$args = ['old_data' => $old_data];
		if(!noticias_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('noticias', $selected_id);

	// if PK value changed, update ownership and $selected_id
	if($selected_id != $newID) {
		update('membership_userrecords', ['pkValue' => $newID], ['pkValue' => $selected_id, 'tableName' => 'noticias']);
		$selected_id = $newID;
	}
}

function noticias_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('noticias');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('noticias', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('noticias', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('noticias', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: motivacion
	$combo_motivacion = new Combo;
	$combo_motivacion->ListType = 0;
	$combo_motivacion->MultipleSeparator = ', ';
	$combo_motivacion->ListBoxHeight = 10;
	$combo_motivacion->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/noticias.motivacion.csv')) {
		$motivacion_data = addslashes(implode('', @file(__DIR__ . '/hooks/noticias.motivacion.csv')));
		$combo_motivacion->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($motivacion_data))));
		$combo_motivacion->ListData = $combo_motivacion->ListItem;
	} else {
		$combo_motivacion->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Motivaci&#243;n intr&#237;nseca;;Motivaci&#243;n extr&#237;nseca;;Motivaci&#243;n positiva;;Motivaci&#243;n negativa;;Motivaci&#243;n personal;;Motivaci&#243;n social;;Motivaci&#243;n econ&#243;mica;;Motivaci&#243;n profesional;;Motivaci&#243;n acad&#233;mica;;Motivaci&#243;n pol&#237;tica"))));
		$combo_motivacion->ListData = $combo_motivacion->ListItem;
	}
	$combo_motivacion->SelectName = 'motivacion';
	$combo_motivacion->AllowNull = false;
	// combobox: fecha_valoracion
	$combo_fecha_valoracion = new DateCombo;
	$combo_fecha_valoracion->DateFormat = "dmy";
	$combo_fecha_valoracion->MinYear = defined('noticias.fecha_valoracion.MinYear') ? constant('noticias.fecha_valoracion.MinYear') : 1900;
	$combo_fecha_valoracion->MaxYear = defined('noticias.fecha_valoracion.MaxYear') ? constant('noticias.fecha_valoracion.MaxYear') : 2100;
	$combo_fecha_valoracion->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_valoracion->MonthNames = $Translation['month names'];
	$combo_fecha_valoracion->NamePrefix = 'fecha_valoracion';
	// combobox: fecha_estimacion_interna
	$combo_fecha_estimacion_interna = new DateCombo;
	$combo_fecha_estimacion_interna->DateFormat = "dmy";
	$combo_fecha_estimacion_interna->MinYear = defined('noticias.fecha_estimacion_interna.MinYear') ? constant('noticias.fecha_estimacion_interna.MinYear') : 1900;
	$combo_fecha_estimacion_interna->MaxYear = defined('noticias.fecha_estimacion_interna.MaxYear') ? constant('noticias.fecha_estimacion_interna.MaxYear') : 2100;
	$combo_fecha_estimacion_interna->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_estimacion_interna->MonthNames = $Translation['month names'];
	$combo_fecha_estimacion_interna->NamePrefix = 'fecha_estimacion_interna';
	// combobox: fecha_ultima_cita
	$combo_fecha_ultima_cita = new DateCombo;
	$combo_fecha_ultima_cita->DateFormat = "dmy";
	$combo_fecha_ultima_cita->MinYear = defined('noticias.fecha_ultima_cita.MinYear') ? constant('noticias.fecha_ultima_cita.MinYear') : 1900;
	$combo_fecha_ultima_cita->MaxYear = defined('noticias.fecha_ultima_cita.MaxYear') ? constant('noticias.fecha_ultima_cita.MaxYear') : 2100;
	$combo_fecha_ultima_cita->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_ultima_cita->MonthNames = $Translation['month names'];
	$combo_fecha_ultima_cita->NamePrefix = 'fecha_ultima_cita';
	// combobox: fecha_ultimo_contacto
	$combo_fecha_ultimo_contacto = new DateCombo;
	$combo_fecha_ultimo_contacto->DateFormat = "dmy";
	$combo_fecha_ultimo_contacto->MinYear = defined('noticias.fecha_ultimo_contacto.MinYear') ? constant('noticias.fecha_ultimo_contacto.MinYear') : 1900;
	$combo_fecha_ultimo_contacto->MaxYear = defined('noticias.fecha_ultimo_contacto.MaxYear') ? constant('noticias.fecha_ultimo_contacto.MaxYear') : 2100;
	$combo_fecha_ultimo_contacto->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_ultimo_contacto->MonthNames = $Translation['month names'];
	$combo_fecha_ultimo_contacto->NamePrefix = 'fecha_ultimo_contacto';
	// combobox: fecha_cierre
	$combo_fecha_cierre = new DateCombo;
	$combo_fecha_cierre->DateFormat = "dmy";
	$combo_fecha_cierre->MinYear = defined('noticias.fecha_cierre.MinYear') ? constant('noticias.fecha_cierre.MinYear') : 1900;
	$combo_fecha_cierre->MaxYear = defined('noticias.fecha_cierre.MaxYear') ? constant('noticias.fecha_cierre.MaxYear') : 2100;
	$combo_fecha_cierre->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_cierre->MonthNames = $Translation['month names'];
	$combo_fecha_cierre->NamePrefix = 'fecha_cierre';

	if($hasSelectedId) {
		if(!($row = getRecord('noticias', $selectedId))) {
			return error_message($Translation['No records found'], 'noticias_view.php', false);
		}
		$combo_motivacion->SelectedData = $row['motivacion'];
		$combo_fecha_valoracion->DefaultDate = $row['fecha_valoracion'];
		$combo_fecha_estimacion_interna->DefaultDate = $row['fecha_estimacion_interna'];
		$combo_fecha_ultima_cita->DefaultDate = $row['fecha_ultima_cita'];
		$combo_fecha_ultimo_contacto->DefaultDate = $row['fecha_ultimo_contacto'];
		$combo_fecha_cierre->DefaultDate = $row['fecha_cierre'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_motivacion->SelectedText = (isset($filterField[1]) && $filterField[1] == '10' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_motivacion->Render();

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/noticias_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/noticias_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#noticia_id').replaceWith('<div class=\"form-control-static\" id=\"noticia_id\">' + (\$j('#noticia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#referencia').replaceWith('<div class=\"form-control-static\" id=\"referencia\">' + (\$j('#referencia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#inmueble_id').replaceWith('<div class=\"form-control-static\" id=\"inmueble_id\">' + (\$j('#inmueble_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#cliente_id').replaceWith('<div class=\"form-control-static\" id=\"cliente_id\">' + (\$j('#cliente_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#colaborador_id').replaceWith('<div class=\"form-control-static\" id=\"colaborador_id\">' + (\$j('#colaborador_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado_noticia_id').replaceWith('<div class=\"form-control-static\" id=\"estado_noticia_id\">' + (\$j('#estado_noticia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#estado_contacto_id').replaceWith('<div class=\"form-control-static\" id=\"estado_contacto_id\">' + (\$j('#estado_contacto_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#tipo_procedencia_id').replaceWith('<div class=\"form-control-static\" id=\"tipo_procedencia_id\">' + (\$j('#tipo_procedencia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#detalle_procedencia_id').replaceWith('<div class=\"form-control-static\" id=\"detalle_procedencia_id\">' + (\$j('#detalle_procedencia_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#motivacion').replaceWith('<div class=\"form-control-static\" id=\"motivacion\">' + (\$j('#motivacion').val() || '') + '</div>'); \$j('#motivacion-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#valoracion').replaceWith('<div class=\"form-control-static\" id=\"valoracion\">' + (\$j('#valoracion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#valoracion_solo_inmueble').replaceWith('<div class=\"form-control-static\" id=\"valoracion_solo_inmueble\">' + (\$j('#valoracion_solo_inmueble').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#precio_pedido').replaceWith('<div class=\"form-control-static\" id=\"precio_pedido\">' + (\$j('#precio_pedido').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#fecha_valoracion').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_valoracionDay, #fecha_valoracionMonth, #fecha_valoracionYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#fecha_estimacion_interna').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_estimacion_internaDay, #fecha_estimacion_internaMonth, #fecha_estimacion_internaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#fecha_ultima_cita').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_ultima_citaDay, #fecha_ultima_citaMonth, #fecha_ultima_citaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#fecha_ultimo_contacto').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_ultimo_contactoDay, #fecha_ultimo_contactoMonth, #fecha_ultimo_contactoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#fecha_cierre').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#fecha_cierreDay, #fecha_cierreMonth, #fecha_cierreYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#motivo_cierre_id').replaceWith('<div class=\"form-control-static\" id=\"motivo_cierre_id\">' + (\$j('#motivo_cierre_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#nota').replaceWith('<div class=\"form-control-static\" id=\"nota\">' + (\$j('#nota').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(motivacion)%%>', $combo_motivacion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(motivacion)%%>', $combo_motivacion->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_valoracion)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_valoracion->GetHTML(true) . '</div>' :
			$combo_fecha_valoracion->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_valoracion)%%>', $combo_fecha_valoracion->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_estimacion_interna)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_estimacion_interna->GetHTML(true) . '</div>' :
			$combo_fecha_estimacion_interna->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_estimacion_interna)%%>', $combo_fecha_estimacion_interna->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_ultima_cita)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_ultima_cita->GetHTML(true) . '</div>' :
			$combo_fecha_ultima_cita->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_ultima_cita)%%>', $combo_fecha_ultima_cita->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_ultimo_contacto)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_ultimo_contacto->GetHTML(true) . '</div>' :
			$combo_fecha_ultimo_contacto->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_ultimo_contacto)%%>', $combo_fecha_ultimo_contacto->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(fecha_cierre)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_fecha_cierre->GetHTML(true) . '</div>' :
			$combo_fecha_cierre->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_cierre)%%>', $combo_fecha_cierre->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(noticia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(referencia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(inmueble_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cliente_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(colaborador_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado_noticia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado_contacto_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipo_procedencia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(detalle_procedencia_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(motivacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(valoracion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(valoracion_solo_inmueble)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(precio_pedido)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_valoracion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_estimacion_interna)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_ultima_cita)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_ultimo_contacto)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_cierre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(motivo_cierre_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nota)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_creacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_modificacion)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(noticia_id)%%>', safe_html($urow['noticia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(noticia_id)%%>', html_attr($row['noticia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(noticia_id)%%>', urlencode($urow['noticia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', safe_html($urow['referencia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(referencia)%%>', html_attr($row['referencia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode($urow['referencia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', safe_html($urow['inmueble_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(inmueble_id)%%>', html_attr($row['inmueble_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode($urow['inmueble_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', safe_html($urow['cliente_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cliente_id)%%>', html_attr($row['cliente_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode($urow['cliente_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(colaborador_id)%%>', safe_html($urow['colaborador_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(colaborador_id)%%>', html_attr($row['colaborador_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(colaborador_id)%%>', urlencode($urow['colaborador_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado_noticia_id)%%>', safe_html($urow['estado_noticia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado_noticia_id)%%>', html_attr($row['estado_noticia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_noticia_id)%%>', urlencode($urow['estado_noticia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado_contacto_id)%%>', safe_html($urow['estado_contacto_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado_contacto_id)%%>', html_attr($row['estado_contacto_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_contacto_id)%%>', urlencode($urow['estado_contacto_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipo_procedencia_id)%%>', safe_html($urow['tipo_procedencia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipo_procedencia_id)%%>', html_attr($row['tipo_procedencia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_procedencia_id)%%>', urlencode($urow['tipo_procedencia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(detalle_procedencia_id)%%>', safe_html($urow['detalle_procedencia_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(detalle_procedencia_id)%%>', html_attr($row['detalle_procedencia_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(detalle_procedencia_id)%%>', urlencode($urow['detalle_procedencia_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(motivacion)%%>', safe_html($urow['motivacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(motivacion)%%>', html_attr($row['motivacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivacion)%%>', urlencode($urow['motivacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(valoracion)%%>', safe_html($urow['valoracion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(valoracion)%%>', html_attr($row['valoracion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion)%%>', urlencode($urow['valoracion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(valoracion_solo_inmueble)%%>', safe_html($urow['valoracion_solo_inmueble']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(valoracion_solo_inmueble)%%>', html_attr($row['valoracion_solo_inmueble']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion_solo_inmueble)%%>', urlencode($urow['valoracion_solo_inmueble']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(precio_pedido)%%>', safe_html($urow['precio_pedido']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(precio_pedido)%%>', html_attr($row['precio_pedido']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precio_pedido)%%>', urlencode($urow['precio_pedido']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_valoracion)%%>', app_datetime($row['fecha_valoracion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_valoracion)%%>', urlencode(app_datetime($urow['fecha_valoracion'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_estimacion_interna)%%>', app_datetime($row['fecha_estimacion_interna']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_estimacion_interna)%%>', urlencode(app_datetime($urow['fecha_estimacion_interna'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultima_cita)%%>', app_datetime($row['fecha_ultima_cita']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultima_cita)%%>', urlencode(app_datetime($urow['fecha_ultima_cita'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultimo_contacto)%%>', app_datetime($row['fecha_ultimo_contacto']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultimo_contacto)%%>', urlencode(app_datetime($urow['fecha_ultimo_contacto'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_cierre)%%>', app_datetime($row['fecha_cierre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_cierre)%%>', urlencode(app_datetime($urow['fecha_cierre'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(motivo_cierre_id)%%>', safe_html($urow['motivo_cierre_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(motivo_cierre_id)%%>', html_attr($row['motivo_cierre_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivo_cierre_id)%%>', urlencode($urow['motivo_cierre_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(nota)%%>', safe_html($urow['nota'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nota)%%>', urlencode($urow['nota']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_creacion)%%>', app_datetime($row['fecha_creacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_creacion)%%>', urlencode(app_datetime($urow['fecha_creacion'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_modificacion)%%>', app_datetime($row['fecha_modificacion'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_modificacion)%%>', urlencode(app_datetime($urow['fecha_modificacion'], 'dt')), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(noticia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(noticia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(referencia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(referencia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(inmueble_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inmueble_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cliente_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(colaborador_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(colaborador_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado_noticia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_noticia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado_contacto_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado_contacto_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipo_procedencia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_procedencia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(detalle_procedencia_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(detalle_procedencia_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(motivacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(valoracion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(valoracion_solo_inmueble)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(valoracion_solo_inmueble)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(precio_pedido)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precio_pedido)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_valoracion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_valoracion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_estimacion_interna)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_estimacion_interna)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultima_cita)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultima_cita)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_ultimo_contacto)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_ultimo_contacto)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_cierre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_cierre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(motivo_cierre_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motivo_cierre_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nota)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nota)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_creacion)%%>', '<%%creationDateTime%%>curdate()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_creacion)%%>', urlencode('<%%creationDateTime%%>curdate()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_modificacion)%%>', '<%%editingDateTime%%>current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_modificacion)%%>', urlencode('<%%editingDateTime%%>current_timestamp()'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('noticias');
	if($hasSelectedId) {
		$jdata = get_joined_record('noticias', $selectedId);
		if($jdata === false) $jdata = get_defaults('noticias');
		$rdata = $row;
	}
	$templateCode .= loadView('noticias-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: noticias_dv
	if(function_exists('noticias_dv')) {
		$args = [];
		noticias_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}