<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/tipologias_inmueble.php');
	include_once(__DIR__ . '/tipologias_inmueble_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('tipologias_inmueble');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tipologias_inmueble';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tipologias_inmueble`.`tipologia_id`" => "tipologia_id",
		"`tipologias_inmueble`.`nombre`" => "nombre",
		"`tipologias_inmueble`.`descripcion`" => "descripcion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tipologias_inmueble`.`tipologia_id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tipologias_inmueble`.`tipologia_id`" => "tipologia_id",
		"`tipologias_inmueble`.`nombre`" => "nombre",
		"`tipologias_inmueble`.`descripcion`" => "descripcion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tipologias_inmueble`.`tipologia_id`" => "Tipologia id",
		"`tipologias_inmueble`.`nombre`" => "Nombre",
		"`tipologias_inmueble`.`descripcion`" => "Descripcion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tipologias_inmueble`.`tipologia_id`" => "tipologia_id",
		"`tipologias_inmueble`.`nombre`" => "nombre",
		"`tipologias_inmueble`.`descripcion`" => "descripcion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`tipologias_inmueble` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tipologias_inmueble_view.php';
	$x->TableTitle = 'Tipologias inmueble';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`tipologias_inmueble`.`tipologia_id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Tipologia id', 'Nombre', 'Descripcion', ];
	$x->ColFieldName = ['tipologia_id', 'nombre', 'descripcion', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tipologias_inmueble_templateTV.html';
	$x->SelectedTemplate = 'templates/tipologias_inmueble_templateTVS.html';
	$x->TemplateDV = 'templates/tipologias_inmueble_templateDV.html';
	$x->TemplateDVP = 'templates/tipologias_inmueble_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tipologias_inmueble_init
	$render = true;
	if(function_exists('tipologias_inmueble_init')) {
		$args = [];
		$render = tipologias_inmueble_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tipologias_inmueble_header
	$headerCode = '';
	if(function_exists('tipologias_inmueble_header')) {
		$args = [];
		$headerCode = tipologias_inmueble_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tipologias_inmueble_footer
	$footerCode = '';
	if(function_exists('tipologias_inmueble_footer')) {
		$args = [];
		$footerCode = tipologias_inmueble_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
