<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/tipos_procedencia.php');
	include_once(__DIR__ . '/tipos_procedencia_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('tipos_procedencia');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tipos_procedencia';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tipos_procedencia`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`tipos_procedencia`.`nombre`" => "nombre",
		"`tipos_procedencia`.`descripcion`" => "descripcion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tipos_procedencia`.`tipo_procedencia_id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tipos_procedencia`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`tipos_procedencia`.`nombre`" => "nombre",
		"`tipos_procedencia`.`descripcion`" => "descripcion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tipos_procedencia`.`tipo_procedencia_id`" => "Tipo procedencia id",
		"`tipos_procedencia`.`nombre`" => "Nombre",
		"`tipos_procedencia`.`descripcion`" => "Descripcion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tipos_procedencia`.`tipo_procedencia_id`" => "tipo_procedencia_id",
		"`tipos_procedencia`.`nombre`" => "nombre",
		"`tipos_procedencia`.`descripcion`" => "descripcion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`tipos_procedencia` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tipos_procedencia_view.php';
	$x->TableTitle = 'Tipos procedencia';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`tipos_procedencia`.`tipo_procedencia_id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Tipo procedencia id', 'Nombre', 'Descripcion', ];
	$x->ColFieldName = ['tipo_procedencia_id', 'nombre', 'descripcion', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tipos_procedencia_templateTV.html';
	$x->SelectedTemplate = 'templates/tipos_procedencia_templateTVS.html';
	$x->TemplateDV = 'templates/tipos_procedencia_templateDV.html';
	$x->TemplateDVP = 'templates/tipos_procedencia_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tipos_procedencia_init
	$render = true;
	if(function_exists('tipos_procedencia_init')) {
		$args = [];
		$render = tipos_procedencia_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tipos_procedencia_header
	$headerCode = '';
	if(function_exists('tipos_procedencia_header')) {
		$args = [];
		$headerCode = tipos_procedencia_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tipos_procedencia_footer
	$footerCode = '';
	if(function_exists('tipos_procedencia_footer')) {
		$args = [];
		$footerCode = tipos_procedencia_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
