<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/tipos_actividad.php');
	include_once(__DIR__ . '/tipos_actividad_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('tipos_actividad');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tipos_actividad';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tipos_actividad`.`tipo_actividad_id`" => "tipo_actividad_id",
		"`tipos_actividad`.`nombre`" => "nombre",
		"`tipos_actividad`.`descripcion`" => "descripcion",
		"`tipos_actividad`.`requiere_resultado`" => "requiere_resultado",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tipos_actividad`.`tipo_actividad_id`',
		2 => 2,
		3 => 3,
		4 => '`tipos_actividad`.`requiere_resultado`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tipos_actividad`.`tipo_actividad_id`" => "tipo_actividad_id",
		"`tipos_actividad`.`nombre`" => "nombre",
		"`tipos_actividad`.`descripcion`" => "descripcion",
		"`tipos_actividad`.`requiere_resultado`" => "requiere_resultado",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tipos_actividad`.`tipo_actividad_id`" => "Tipo actividad id",
		"`tipos_actividad`.`nombre`" => "Nombre",
		"`tipos_actividad`.`descripcion`" => "Descripcion",
		"`tipos_actividad`.`requiere_resultado`" => "Requiere resultado",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tipos_actividad`.`tipo_actividad_id`" => "tipo_actividad_id",
		"`tipos_actividad`.`nombre`" => "nombre",
		"`tipos_actividad`.`descripcion`" => "descripcion",
		"`tipos_actividad`.`requiere_resultado`" => "requiere_resultado",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`tipos_actividad` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tipos_actividad_view.php';
	$x->TableTitle = 'Tipos actividad';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`tipos_actividad`.`tipo_actividad_id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Tipo actividad id', 'Nombre', 'Descripcion', 'Requiere resultado', ];
	$x->ColFieldName = ['tipo_actividad_id', 'nombre', 'descripcion', 'requiere_resultado', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tipos_actividad_templateTV.html';
	$x->SelectedTemplate = 'templates/tipos_actividad_templateTVS.html';
	$x->TemplateDV = 'templates/tipos_actividad_templateDV.html';
	$x->TemplateDVP = 'templates/tipos_actividad_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tipos_actividad_init
	$render = true;
	if(function_exists('tipos_actividad_init')) {
		$args = [];
		$render = tipos_actividad_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tipos_actividad_header
	$headerCode = '';
	if(function_exists('tipos_actividad_header')) {
		$args = [];
		$headerCode = tipos_actividad_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tipos_actividad_footer
	$footerCode = '';
	if(function_exists('tipos_actividad_footer')) {
		$args = [];
		$footerCode = tipos_actividad_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
