<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/usuarios.php');
	include_once(__DIR__ . '/usuarios_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('usuarios');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'usuarios';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`usuarios`.`usuario_id`" => "usuario_id",
		"`usuarios`.`nombre`" => "nombre",
		"`usuarios`.`apellidos`" => "apellidos",
		"`usuarios`.`nombre_completo`" => "nombre_completo",
		"`usuarios`.`email`" => "email",
		"`usuarios`.`telefono`" => "telefono",
		"`usuarios`.`puesto`" => "puesto",
		"`usuarios`.`agencia_id`" => "agencia_id",
		"`usuarios`.`activo`" => "activo",
		"if(`usuarios`.`fecha_alta`,date_format(`usuarios`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"if(`usuarios`.`ultima_conexion`,date_format(`usuarios`.`ultima_conexion`,'%d/%m/%Y %H:%i'),'')" => "ultima_conexion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`usuarios`.`activo`',
		10 => '`usuarios`.`fecha_alta`',
		11 => '`usuarios`.`ultima_conexion`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`usuarios`.`usuario_id`" => "usuario_id",
		"`usuarios`.`nombre`" => "nombre",
		"`usuarios`.`apellidos`" => "apellidos",
		"`usuarios`.`nombre_completo`" => "nombre_completo",
		"`usuarios`.`email`" => "email",
		"`usuarios`.`telefono`" => "telefono",
		"`usuarios`.`puesto`" => "puesto",
		"`usuarios`.`agencia_id`" => "agencia_id",
		"`usuarios`.`activo`" => "activo",
		"if(`usuarios`.`fecha_alta`,date_format(`usuarios`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"if(`usuarios`.`ultima_conexion`,date_format(`usuarios`.`ultima_conexion`,'%d/%m/%Y %H:%i'),'')" => "ultima_conexion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`usuarios`.`usuario_id`" => "Usuario id",
		"`usuarios`.`nombre`" => "Nombre",
		"`usuarios`.`apellidos`" => "Apellidos",
		"`usuarios`.`nombre_completo`" => "Nombre completo",
		"`usuarios`.`email`" => "Email",
		"`usuarios`.`telefono`" => "Telefono",
		"`usuarios`.`puesto`" => "Puesto",
		"`usuarios`.`agencia_id`" => "Agencia id",
		"`usuarios`.`activo`" => "Activo",
		"`usuarios`.`fecha_alta`" => "Fecha alta",
		"`usuarios`.`ultima_conexion`" => "Ultima conexion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`usuarios`.`usuario_id`" => "usuario_id",
		"`usuarios`.`nombre`" => "nombre",
		"`usuarios`.`apellidos`" => "apellidos",
		"`usuarios`.`nombre_completo`" => "nombre_completo",
		"`usuarios`.`email`" => "email",
		"`usuarios`.`telefono`" => "telefono",
		"`usuarios`.`puesto`" => "puesto",
		"`usuarios`.`agencia_id`" => "agencia_id",
		"`usuarios`.`activo`" => "activo",
		"if(`usuarios`.`fecha_alta`,date_format(`usuarios`.`fecha_alta`,'%d/%m/%Y'),'')" => "fecha_alta",
		"if(`usuarios`.`ultima_conexion`,date_format(`usuarios`.`ultima_conexion`,'%d/%m/%Y %H:%i'),'')" => "ultima_conexion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`usuarios` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'usuarios_view.php';
	$x->TableTitle = 'Usuarios';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`usuarios`.`usuario_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Usuario id', 'Nombre', 'Apellidos', 'Nombre completo', 'Email', 'Telefono', 'Puesto', 'Agencia id', 'Activo', 'Fecha alta', 'Ultima conexion', ];
	$x->ColFieldName = ['usuario_id', 'nombre', 'apellidos', 'nombre_completo', 'email', 'telefono', 'puesto', 'agencia_id', 'activo', 'fecha_alta', 'ultima_conexion', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/usuarios_templateTV.html';
	$x->SelectedTemplate = 'templates/usuarios_templateTVS.html';
	$x->TemplateDV = 'templates/usuarios_templateDV.html';
	$x->TemplateDVP = 'templates/usuarios_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: usuarios_init
	$render = true;
	if(function_exists('usuarios_init')) {
		$args = [];
		$render = usuarios_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: usuarios_header
	$headerCode = '';
	if(function_exists('usuarios_header')) {
		$args = [];
		$headerCode = usuarios_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: usuarios_footer
	$footerCode = '';
	if(function_exists('usuarios_footer')) {
		$args = [];
		$footerCode = usuarios_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
